//! Target zensim-A ↔ encoder-quality mapping.
//!
//! The calibration here is a per-encoder anchor table mapping
//! `(encoder, source_quality_in_native_scale)` → estimated zensim-A
//! against an unknown original reference. Today the table is a coarse
//! initial guess pulled from
//! `crate::detect::reencode::estimated_source_ba` (which itself was
//! calibrated on 10 gb82 images) and a linear BA→zensim-A approximation.
//!
//! Replacing these constants with the full corpus sweep is the
//! `zjr-calibrate` job. Until then the [`Confidence::Approximate`] field
//! on the probe signals callers to widen tolerances.

use crate::detect::{EncoderFamily, QualityEstimate, QualityScale};

/// Convert a target zensim-A to the encoder-quality value to pass
/// into `crate::encoder::EncoderConfig::ycbcr(...)`.
///
/// **Corpus-fitted (2026-05-28).** Anchors derived from the
/// `cid22_15img_seed_sweep_2026-05-28.tsv` measurements (510
/// Tuned-strategy cells). For each row the measured `cumulative
/// zensim-A vs reference` was paired with the encoder-quality input
/// that produced the recompressed JPEG, then the relationship was
/// inverted to get target→input. The fit accounts for `auto_optimize`
/// being ON in the Tuned strategy (which lifts the achievable
/// zensim-A by ~3-5 points at the high end). See
/// `benchmarks/INDEX.md` for the underlying TSV.
pub fn target_zensim_a_to_ijg_q(target_zensim_a: f32) -> u8 {
    // Anchors derived from the corpus sweep + auto_optimize lift:
    // measured(input=50, auto_optimize=on) ≈ 56
    // measured(input=70) ≈ 70
    // measured(input=85) ≈ 78
    // measured(input=95) ≈ 84
    // Inverting: target=50 → input=44; target=70 → input=70;
    // target=80 → input=87; target=85 → input=94; target=90 → input=100.
    const ANCHORS: &[(f32, u8)] = &[
        (30.0, 25),
        (40.0, 35),
        (50.0, 44),
        (55.0, 50),
        (60.0, 58),
        (65.0, 64),
        (70.0, 70),
        (75.0, 78),
        (80.0, 87),
        (85.0, 94),
        (90.0, 100),
        (95.0, 100),
        (100.0, 100),
    ];
    interp_u8(target_zensim_a, ANCHORS)
}

/// Convert a target zensim-A to a target butteraugli distance for use
/// with jpegli-family encoders.
///
/// Anchors derived from inverting `encoder_quality_to_estimated_zensim_a`
/// on the jpegli branch.
pub fn target_zensim_a_to_ba_distance(target_zensim_a: f32) -> f32 {
    const ANCHORS: &[(f32, f32)] = &[
        (98.0, 0.5),
        (95.0, 0.8),
        (90.0, 1.2),
        (85.0, 1.7),
        (80.0, 2.3),
        (75.0, 2.9),
        (70.0, 3.5),
        (60.0, 5.0),
        (50.0, 7.0),
        (40.0, 9.0),
    ];
    interp_f32(target_zensim_a, ANCHORS)
}

/// Coarse: estimated zensim-A of the source vs an (unknown) original
/// reference. The mapping conditions only on `encoder` + native quality.
///
/// **Calibration provenance.** Anchors below are placeholders; the
/// proper fit comes from `zjr-calibrate` against the codec-corpus +
/// cid22 sweep. The router's CI widens for cells flagged
/// [`crate::detect::Confidence::Approximate`].
pub fn encoder_quality_to_estimated_zensim_a(
    encoder: &EncoderFamily,
    quality: &QualityEstimate,
) -> f32 {
    match quality.scale {
        QualityScale::ButteraugliDistance => ba_to_zensim_a(quality.value),
        QualityScale::IjgQuality | QualityScale::MozjpegQuality => {
            ijg_q_to_zensim_a(encoder, quality.value)
        }
        // `QualityScale` is `#[non_exhaustive]`. Treat any future variant
        // as an IJG-quality-ish best-effort estimate so we never refuse
        // to recompress on a new scale we haven't calibrated yet.
        _ => ijg_q_to_zensim_a(encoder, quality.value),
    }
}

fn ba_to_zensim_a(ba: f32) -> f32 {
    // Same table inverted from `target_zensim_a_to_ba_distance`.
    const ANCHORS: &[(f32, f32)] = &[
        (0.5, 98.0),
        (0.8, 95.0),
        (1.2, 90.0),
        (1.7, 85.0),
        (2.3, 80.0),
        (2.9, 75.0),
        (3.5, 70.0),
        (5.0, 60.0),
        (7.0, 50.0),
        (9.0, 40.0),
    ];
    interp_f32(ba, ANCHORS)
}

fn ijg_q_to_zensim_a(encoder: &EncoderFamily, q: f32) -> f32 {
    // MEASURED per-encoder IJG-Q → cumulative-zensim-A-vs-original
    // anchors, median over 50 CID22-512 references at 4:2:0, q step 5
    // (raw sweep + sha256 in
    // benchmarks/calibration-n50-2026-05-29.pointer.md → /mnt/v,
    // `zen-metrics zensim-gpu`; regenerated by scripts/recalibrate.sh
    // stage 2 on pinned turbo-3.1.0 + mozjpeg-4.1.5 + cjpegli). These
    // replace the earlier shared anchor + additive-shift model, which
    // over-estimated turbo/mozjpeg source quality by ~10 zensim-A and
    // caused 75-76% under-target delivery on those sources (vs 4% on
    // jpegli). The two encoders' curves differ in *shape*, not just
    // offset (mozjpeg + turbo both plateau ~q55→q65), so a single
    // shifted table cannot fit both. n=50 (was n=6) tightens the
    // medians; end-to-end under-target dropped turbo 13.2%→8.6%,
    // mozjpeg 8.3%→7.0% (jpegli ~3.6%), zero size regressions.
    match encoder {
        EncoderFamily::Mozjpeg => {
            const MOZ: &[(f32, f32)] = &[
                (20.0, 26.5),
                (25.0, 34.0),
                (30.0, 42.1),
                (35.0, 48.6),
                (40.0, 53.0),
                (45.0, 55.1),
                (50.0, 58.6),
                (55.0, 63.2),
                (60.0, 63.8),
                (65.0, 64.1),
                (70.0, 65.7),
                (75.0, 71.4),
                (80.0, 77.4),
                (85.0, 80.5),
                (90.0, 88.3),
                (95.0, 90.8),
            ];
            interp_f32(q, MOZ)
        }
        EncoderFamily::CjpegliYcbcr | EncoderFamily::CjpegliXyb => {
            // jpegli's quality is reported on the BA-distance scale;
            // estimated quality for those encoders comes through the BA
            // branch, not here. Fallback if reached.
            92.0
        }
        // libjpeg-turbo, IJG, Pillow, ImageMagick — all IJG-table
        // encoders; use the measured turbo curve.
        _ => {
            const TURBO: &[(f32, f32)] = &[
                (20.0, 32.9),
                (25.0, 41.5),
                (30.0, 47.3),
                (35.0, 53.1),
                (40.0, 56.1),
                (45.0, 58.8),
                (50.0, 62.5),
                (55.0, 63.9),
                (60.0, 64.1),
                (65.0, 64.4),
                (70.0, 69.2),
                (75.0, 73.2),
                (80.0, 76.5),
                (85.0, 79.9),
                (90.0, 83.3),
                (95.0, 85.4),
            ];
            interp_f32(q, TURBO)
        }
    }
}

fn interp_f32(x: f32, anchors: &[(f32, f32)]) -> f32 {
    if x <= anchors[0].0 {
        return anchors[0].1;
    }
    if x >= anchors[anchors.len() - 1].0 {
        return anchors[anchors.len() - 1].1;
    }
    for w in anchors.windows(2) {
        let (x0, y0) = w[0];
        let (x1, y1) = w[1];
        if x >= x0 && x <= x1 {
            let t = (x - x0) / (x1 - x0);
            return y0 + t * (y1 - y0);
        }
    }
    anchors[anchors.len() - 1].1
}

fn interp_u8(x: f32, anchors: &[(f32, u8)]) -> u8 {
    if x <= anchors[0].0 {
        return anchors[0].1;
    }
    if x >= anchors[anchors.len() - 1].0 {
        return anchors[anchors.len() - 1].1;
    }
    for w in anchors.windows(2) {
        let (x0, y0) = w[0];
        let (x1, y1) = w[1];
        if x >= x0 && x <= x1 {
            let t = (x - x0) / (x1 - x0);
            let y = y0 as f32 + t * (y1 as f32 - y0 as f32);
            return y.round().clamp(1.0, 100.0) as u8;
        }
    }
    anchors[anchors.len() - 1].1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ijg_q_inversion_is_monotone() {
        let mut prev = 0.0_f32;
        for t in [
            40.0_f32, 55.0, 65.0, 75.0, 82.0, 88.0, 92.0, 95.0, 97.0, 98.5,
        ] {
            let q = target_zensim_a_to_ijg_q(t);
            assert!(q as f32 >= prev, "monotone IJG inversion: t={t}, q={q}");
            prev = q as f32;
        }
    }

    #[test]
    fn ba_distance_monotone_decreasing() {
        let mut prev = 100.0_f32;
        for t in [98.0_f32, 95.0, 90.0, 85.0, 80.0, 70.0, 60.0, 50.0] {
            let d = target_zensim_a_to_ba_distance(t);
            assert!(d >= 0.0, "BA distance non-negative");
            let z = ba_to_zensim_a(d);
            assert!(
                z <= prev + 0.6,
                "BA→zensim-A round-trip near monotone: t={t}, d={d}, z={z}, prev={prev}"
            );
            prev = z;
        }
    }
}
