//! Generate Rust source code for corpus-trained Huffman tables.
//!
//! Reads aggregated frequency JSON from a previous `gather_corpus_frequencies`
//! run and emits a Rust module with `const` table data.
//!
//! Run with:
//!   cargo run --release -p zenjpeg --example generate_corpus_table_source
//!
//! Writes to: /mnt/v/output/zenjpeg/huffman-freq/corpus_tables.rs

use std::fs;
use std::io::Write;
use std::path::Path;

use zenjpeg::encode::HuffmanSymbolFrequencies;
use zenjpeg::huffman::optimize::{FrequencyCounter, HuffmanTableSet, OptimizedTable};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

fn freq_dir() -> std::path::PathBuf {
    zenjpeg_bench_utils::zenjpeg_output_dir().join("huffman-freq/aggregated")
}
fn output_file() -> std::path::PathBuf {
    zenjpeg_bench_utils::zenjpeg_output_dir().join("huffman-freq/corpus_tables.rs")
}

const QUALITY_TIERS: &[u8] = &[
    0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 89, 90, 91, 92, 93, 94,
    95, 96, 97, 98, 99, 100,
];

/// Table families: ycbcr-444, ycbcr-420, xyb
const FAMILIES: &[(&str, &str)] = &[
    ("ycbcr_444", "ycbcr-444"),
    ("ycbcr_420", "ycbcr-420"),
    ("xyb", "xyb-full"),
];

fn main() -> Result<()> {
    let freq_dir = freq_dir();
    let output_file = output_file();
    let mut out = fs::File::create(&output_file)?;

    writeln!(
        out,
        "//! Corpus-trained Huffman tables for streaming/single-pass encoding."
    )?;
    writeln!(out, "//!")?;
    writeln!(
        out,
        "//! Generated by `generate_corpus_table_source` from 395 training images"
    )?;
    writeln!(
        out,
        "//! across 7 corpora (CID22, CLIC2025, Kodak, gb82, kadid10k, etc.)."
    )?;
    writeln!(out, "//!")?;
    writeln!(
        out,
        "//! Three families: ycbcr_444, ycbcr_420 (also used for 422), xyb."
    )?;
    writeln!(
        out,
        "//! Each family has tables for 30 quality tiers (Q0-Q100)."
    )?;
    writeln!(out, "//!")?;
    writeln!(out, "//! Typical overhead vs per-image optimal: ~2.5%.")?;
    writeln!(
        out,
        "//! Improvement over JPEG Annex K standard tables: 5-12pp."
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "use crate::huffman::optimize::{{HuffmanTableSet, OptimizedTable}};"
    )?;
    writeln!(out)?;

    // Quality tier index
    write!(out, "pub(crate) const QUALITY_TIERS: &[u8] = &[")?;
    for (i, q) in QUALITY_TIERS.iter().enumerate() {
        if i > 0 {
            write!(out, ", ")?;
        }
        write!(out, "{q}")?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    // Nearest quality tier lookup
    writeln!(
        out,
        "/// Returns the index into QUALITY_TIERS for the nearest tier <= quality."
    )?;
    writeln!(
        out,
        "/// If quality < 0, returns index 0. If quality > 100, returns last index."
    )?;
    writeln!(
        out,
        "pub(crate) fn nearest_quality_tier(quality: f32) -> usize {{"
    )?;
    writeln!(out, "    let q = quality.round() as i32;")?;
    writeln!(
        out,
        "    match QUALITY_TIERS.binary_search(&(q.clamp(0, 100) as u8)) {{"
    )?;
    writeln!(out, "        Ok(idx) => idx,")?;
    writeln!(out, "        Err(idx) => idx.saturating_sub(1),")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Generate each family
    for &(rust_name, dir_name) in FAMILIES {
        let freq_path = freq_dir.join(dir_name).join("raw_frequencies.json");
        let data: serde_json::Value = serde_json::from_str(&fs::read_to_string(&freq_path)?)?;

        let is_xyb = rust_name == "xyb";

        // Build tables for each quality tier
        let mut all_tables: Vec<(u8, HuffmanTableSet)> = Vec::new();
        for &q in QUALITY_TIERS {
            let key = format!("q{q}");
            let qdata = &data[&key];
            let freqs = json_to_frequencies(qdata)?;
            let tables = freqs.generate_tables()?;
            all_tables.push((q, tables));
        }

        // Emit the lookup function
        writeln!(
            out,
            "/// Returns corpus-trained tables for {rust_name} at the given quality tier index."
        )?;
        writeln!(out, "///")?;
        writeln!(
            out,
            "/// The tier index comes from [`nearest_quality_tier`]."
        )?;
        writeln!(out, "#[allow(clippy::too_many_lines)]")?;
        writeln!(
            out,
            "pub(crate) fn {rust_name}_tables(tier_idx: usize) -> HuffmanTableSet {{"
        )?;
        writeln!(out, "    match tier_idx {{")?;

        for (i, (_q, tables)) in all_tables.iter().enumerate() {
            writeln!(out, "        {i} => HuffmanTableSet {{")?;
            write_table_field(&mut out, "dc_luma", &tables.dc_luma)?;
            write_table_field(&mut out, "ac_luma", &tables.ac_luma)?;
            if is_xyb {
                // XYB: chroma tables are copies of luma (single shared pair)
                write_table_field(&mut out, "dc_chroma", &tables.dc_luma)?;
                write_table_field(&mut out, "ac_chroma", &tables.ac_luma)?;
            } else {
                write_table_field(&mut out, "dc_chroma", &tables.dc_chroma)?;
                write_table_field(&mut out, "ac_chroma", &tables.ac_chroma)?;
            }
            writeln!(out, "        }},")?;
        }

        writeln!(
            out,
            "        _ => {rust_name}_tables(QUALITY_TIERS.len() - 1),"
        )?;
        writeln!(out, "    }}")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    drop(out);
    println!("Generated: {}", output_file.display());

    // Print size stats
    let contents = fs::read_to_string(&output_file)?;
    let lines = contents.lines().count();
    let bytes = contents.len();
    println!("  {lines} lines, {bytes} bytes");

    // Verify: build every table set and ensure they produce valid tables
    for &(rust_name, dir_name) in FAMILIES {
        let freq_path = freq_dir.join(dir_name).join("raw_frequencies.json");
        let data: serde_json::Value = serde_json::from_str(&fs::read_to_string(&freq_path)?)?;
        for &q in QUALITY_TIERS {
            let key = format!("q{q}");
            let freqs = json_to_frequencies(&data[&key])?;
            let _tables = freqs.generate_tables()?;
        }
        println!(
            "  {rust_name}: all {0} quality tiers verified",
            QUALITY_TIERS.len()
        );
    }

    Ok(())
}

fn write_table_field(out: &mut fs::File, name: &str, table: &OptimizedTable) -> Result<()> {
    write!(
        out,
        "            {name}: OptimizedTable::from_bits_values_static("
    )?;
    // bits array
    write!(out, "[")?;
    for (i, b) in table.bits.iter().enumerate() {
        if i > 0 {
            write!(out, ", ")?;
        }
        write!(out, "{b}")?;
    }
    write!(out, "], &[")?;
    // values slice
    for (i, v) in table.values.iter().enumerate() {
        if i > 0 {
            write!(out, ", ")?;
        }
        write!(out, "{v}")?;
    }
    writeln!(out, "]),")?;
    Ok(())
}

fn json_to_frequencies(qdata: &serde_json::Value) -> Result<HuffmanSymbolFrequencies> {
    fn load_counter(arr: &serde_json::Value) -> Result<FrequencyCounter> {
        let vals: Vec<i64> = serde_json::from_value(arr.clone())?;
        if vals.len() != 256 {
            return Err(format!("expected 256 values, got {}", vals.len()).into());
        }
        let mut counter = FrequencyCounter::new();
        for (i, &v) in vals.iter().enumerate() {
            counter.set_count(i as u8, v);
        }
        Ok(counter)
    }

    Ok(HuffmanSymbolFrequencies {
        dc_luma: load_counter(&qdata["dc_luma"])?,
        ac_luma: load_counter(&qdata["ac_luma"])?,
        dc_chroma: load_counter(&qdata["dc_chroma"])?,
        ac_chroma: load_counter(&qdata["ac_chroma"])?,
    })
}
