//! Forward Discrete Cosine Transform (DCT) implementation.
//!
//! This module provides 8x8 DCT-II transform used for JPEG encoding.
//! Uses the recursive splitting algorithm from jpegli for exact compatibility.
//!
//! SIMD optimization is available via the `simd` feature (enabled by default).

use crate::consts::DCT_BLOCK_SIZE;

#[cfg(feature = "simd")]
use wide::f32x8;

/// WcMultipliers constants for DCT.
/// Generated by: 1.0 / (2 * cos((i + 0.5) * pi / N))
const WC4: [f32; 2] = [0.541196100146197, 1.3065629648763764];

const WC8: [f32; 4] = [
    0.5097955791041592,
    0.6013448869350453,
    0.8999762231364156,
    2.5629154477415055,
];

const SQRT2: f32 = 1.41421356237;

/// Transpose an 8x8 block (scalar version).
#[cfg(any(not(feature = "simd"), test))]
#[inline]
fn transpose_8x8(input: &[f32; 64], output: &mut [f32; 64]) {
    for row in 0..8 {
        for col in 0..8 {
            output[col * 8 + row] = input[row * 8 + col];
        }
    }
}

/// AddReverse: out[i] = in1[i] + in2[N-1-i]
#[inline]
fn add_reverse<const N: usize>(in1: &[f32], in2: &[f32], out: &mut [f32]) {
    for i in 0..N {
        out[i] = in1[i] + in2[N - 1 - i];
    }
}

/// SubReverse: out[i] = in1[i] - in2[N-1-i]
#[inline]
fn sub_reverse<const N: usize>(in1: &[f32], in2: &[f32], out: &mut [f32]) {
    for i in 0..N {
        out[i] = in1[i] - in2[N - 1 - i];
    }
}

/// B transform: coeff[0] = coeff[0] * sqrt2 + coeff[1]; then cumulative sum
#[inline]
fn b_transform<const N: usize>(coeff: &mut [f32]) {
    coeff[0] = coeff[0] * SQRT2 + coeff[1];
    for i in 1..(N - 1) {
        coeff[i] += coeff[i + 1];
    }
}

/// Multiply odd part by Wc multipliers
#[inline]
fn multiply_wc8(coeff: &mut [f32]) {
    for i in 0..4 {
        coeff[4 + i] *= WC8[i];
    }
}

#[inline]
fn multiply_wc4(coeff: &mut [f32]) {
    for i in 0..2 {
        coeff[2 + i] *= WC4[i];
    }
}

/// InverseEvenOdd: Interleave even/odd parts
/// out[2*i] = in[i] for i in 0..N/2
/// out[2*i+1] = in[N/2+i] for i in 0..N/2
#[inline]
fn inverse_even_odd<const N: usize>(input: &[f32], output: &mut [f32]) {
    let half = N / 2;
    for i in 0..half {
        output[2 * i] = input[i];
        output[2 * i + 1] = input[half + i];
    }
}

/// DCT base case for N=2
#[inline]
fn dct1d_2(mem: &mut [f32]) {
    let in1 = mem[0];
    let in2 = mem[1];
    mem[0] = in1 + in2;
    mem[1] = in1 - in2;
}

/// DCT for N=4 (recursive)
#[inline]
fn dct1d_4(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 4];

    // AddReverse<2>: tmp[0:2] = mem[0:2] + reverse(mem[2:4])
    add_reverse::<2>(&mem[0..2], &mem[2..4], &mut tmp[0..2]);

    // DCT1D<2> on first half
    dct1d_2(&mut tmp[0..2]);

    // SubReverse<2>: tmp[2:4] = mem[0:2] - reverse(mem[2:4])
    sub_reverse::<2>(&mem[0..2], &mem[2..4], &mut tmp[2..4]);

    // Multiply<4>: multiply tmp[2:4] by WC4
    multiply_wc4(&mut tmp);

    // DCT1D<2> on second half
    dct1d_2(&mut tmp[2..4]);

    // B<2>: just coeff[0] *= sqrt2 + coeff[1] (no loop since N-1=1)
    tmp[2] = tmp[2] * SQRT2 + tmp[3];

    // InverseEvenOdd<4>
    inverse_even_odd::<4>(&tmp, mem);
}

/// DCT for N=8 (recursive)
#[inline]
fn dct1d_8(mem: &mut [f32]) {
    let mut tmp = [0.0f32; 8];

    // AddReverse<4>: tmp[0:4] = mem[0:4] + reverse(mem[4:8])
    add_reverse::<4>(&mem[0..4], &mem[4..8], &mut tmp[0..4]);

    // DCT1D<4> on first half
    dct1d_4(&mut tmp[0..4]);

    // SubReverse<4>: tmp[4:8] = mem[0:4] - reverse(mem[4:8])
    sub_reverse::<4>(&mem[0..4], &mem[4..8], &mut tmp[4..8]);

    // Multiply<8>: multiply tmp[4:8] by WC8
    multiply_wc8(&mut tmp);

    // DCT1D<4> on second half
    dct1d_4(&mut tmp[4..8]);

    // B<4>: coeff[0] = coeff[0] * sqrt2 + coeff[1]; then cumulative sum
    b_transform::<4>(&mut tmp[4..8]);

    // InverseEvenOdd<8>
    inverse_even_odd::<8>(&tmp, mem);
}

/// 1D DCT on all 8 rows (no per-row scaling, scaling handled in main function)
#[cfg(not(feature = "simd"))]
#[inline]
fn dct_rows(input: &[f32; 64], output: &mut [f32; 64]) {
    for row in 0..8 {
        let mut tmp = [0.0f32; 8];
        for i in 0..8 {
            tmp[i] = input[row * 8 + i];
        }
        dct1d_8(&mut tmp);
        for i in 0..8 {
            output[row * 8 + i] = tmp[i];
        }
    }
}

// SIMD-optimized implementations
#[cfg(feature = "simd")]
mod simd {
    use super::*;

    // SIMD versions of WC constants for parallel DCT
    // Note: The parallel DCT approach has poor cache locality and doesn't
    // improve performance compared to row-by-row processing. Kept for reference.
    #[allow(dead_code)]
    const WC4_0: f32x8 = f32x8::new([0.541196100146197; 8]);
    #[allow(dead_code)]
    const WC4_1: f32x8 = f32x8::new([1.3065629648763764; 8]);

    #[allow(dead_code)]
    const WC8_0: f32x8 = f32x8::new([0.5097955791041592; 8]);
    #[allow(dead_code)]
    const WC8_1: f32x8 = f32x8::new([0.6013448869350453; 8]);
    #[allow(dead_code)]
    const WC8_2: f32x8 = f32x8::new([0.8999762231364156; 8]);
    #[allow(dead_code)]
    const WC8_3: f32x8 = f32x8::new([2.5629154477415055; 8]);

    #[allow(dead_code)]
    const SQRT2_VEC: f32x8 = f32x8::new([1.41421356237; 8]);

    /// DCT base case for N=2 on SIMD vectors
    /// Processes 8 independent 2-point DCTs in parallel
    #[allow(dead_code)]
    #[inline]
    fn dct1d_2_simd(m0: &mut f32x8, m1: &mut f32x8) {
        let in0 = *m0;
        let in1 = *m1;
        *m0 = in0 + in1;
        *m1 = in0 - in1;
    }

    /// DCT for N=4 on SIMD vectors
    /// Processes 8 independent 4-point DCTs in parallel
    #[allow(dead_code)]
    #[inline]
    fn dct1d_4_simd(m: &mut [f32x8; 4]) {
        // AddReverse<2>: tmp[0:2] = m[0:2] + reverse(m[2:4])
        let t0 = m[0] + m[3]; // m[0] + m[4-1-0]
        let t1 = m[1] + m[2]; // m[1] + m[4-1-1]

        // SubReverse<2>: tmp[2:4] = m[0:2] - reverse(m[2:4])
        let t2 = m[0] - m[3];
        let t3 = m[1] - m[2];

        // DCT1D<2> on first half (t0, t1)
        let r0 = t0 + t1;
        let r1 = t0 - t1;

        // Multiply by WC4
        let t2_scaled = t2 * WC4_0;
        let t3_scaled = t3 * WC4_1;

        // DCT1D<2> on second half
        let r2 = t2_scaled + t3_scaled;
        let r3 = t2_scaled - t3_scaled;

        // B<2>: r2 = r2 * sqrt2 + r3
        let r2_final = r2 * SQRT2_VEC + r3;

        // InverseEvenOdd<4>: interleave even/odd
        m[0] = r0; // even[0]
        m[1] = r2_final; // odd[0]
        m[2] = r1; // even[1]
        m[3] = r3; // odd[1]
    }

    /// DCT for N=8 on SIMD vectors
    /// Processes 8 independent 8-point DCTs in parallel
    #[allow(dead_code)]
    #[inline]
    fn dct1d_8_simd(m: &mut [f32x8; 8]) {
        // AddReverse<4>: tmp[0:4] = m[0:4] + reverse(m[4:8])
        let t0 = m[0] + m[7];
        let t1 = m[1] + m[6];
        let t2 = m[2] + m[5];
        let t3 = m[3] + m[4];

        // SubReverse<4>: tmp[4:8] = m[0:4] - reverse(m[4:8])
        let t4 = m[0] - m[7];
        let t5 = m[1] - m[6];
        let t6 = m[2] - m[5];
        let t7 = m[3] - m[4];

        // DCT1D<4> on first half (t0-t3)
        let mut first = [t0, t1, t2, t3];
        dct1d_4_simd(&mut first);

        // Multiply by WC8
        let t4_scaled = t4 * WC8_0;
        let t5_scaled = t5 * WC8_1;
        let t6_scaled = t6 * WC8_2;
        let t7_scaled = t7 * WC8_3;

        // DCT1D<4> on second half
        let mut second = [t4_scaled, t5_scaled, t6_scaled, t7_scaled];
        dct1d_4_simd(&mut second);

        // B<4>: coeff[0] = coeff[0] * sqrt2 + coeff[1]; then cumulative sum
        second[0] = second[0] * SQRT2_VEC + second[1];
        second[1] = second[1] + second[2];
        second[2] = second[2] + second[3];
        // second[3] stays the same

        // InverseEvenOdd<8>: interleave
        m[0] = first[0];
        m[1] = second[0];
        m[2] = first[1];
        m[3] = second[1];
        m[4] = first[2];
        m[5] = second[2];
        m[6] = first[3];
        m[7] = second[3];
    }

    /// Process 8 rows simultaneously using SIMD
    /// Each lane of f32x8 handles one row's element at the same column position
    /// Note: This has poor cache locality due to column-wise gather/scatter.
    /// Row-by-row scalar processing is faster despite less theoretical parallelism.
    #[allow(dead_code)]
    #[inline]
    pub fn dct_8rows_parallel(input: &[f32; 64], output: &mut [f32; 64]) {
        // Load data column-wise: mem[col] holds position col from all 8 rows
        let mut mem = [f32x8::ZERO; 8];
        for col in 0..8 {
            mem[col] = f32x8::from([
                input[0 * 8 + col],
                input[1 * 8 + col],
                input[2 * 8 + col],
                input[3 * 8 + col],
                input[4 * 8 + col],
                input[5 * 8 + col],
                input[6 * 8 + col],
                input[7 * 8 + col],
            ]);
        }

        // Execute 8 DCT-1D operations in parallel (one per row)
        dct1d_8_simd(&mut mem);

        // Store back - now mem[col] holds DCT output col from all 8 rows
        for col in 0..8 {
            let arr = mem[col].to_array();
            output[0 * 8 + col] = arr[0];
            output[1 * 8 + col] = arr[1];
            output[2 * 8 + col] = arr[2];
            output[3 * 8 + col] = arr[3];
            output[4 * 8 + col] = arr[4];
            output[5 * 8 + col] = arr[5];
            output[6 * 8 + col] = arr[6];
            output[7 * 8 + col] = arr[7];
        }
    }

    /// SIMD-optimized 8x8 transpose.
    /// Uses proper 8x8 transpose algorithm.
    #[inline]
    pub fn transpose_8x8_simd(input: &[f32; 64], output: &mut [f32; 64]) {
        // Load all 8 rows as arrays for direct indexing
        let a0 = &input[0..8];
        let a1 = &input[8..16];
        let a2 = &input[16..24];
        let a3 = &input[24..32];
        let a4 = &input[32..40];
        let a5 = &input[40..48];
        let a6 = &input[48..56];
        let a7 = &input[56..64];

        // Transpose: output[col * 8 + row] = input[row * 8 + col]
        // Build each output row by gathering from columns
        for col in 0..8 {
            output[col * 8 + 0] = a0[col];
            output[col * 8 + 1] = a1[col];
            output[col * 8 + 2] = a2[col];
            output[col * 8 + 3] = a3[col];
            output[col * 8 + 4] = a4[col];
            output[col * 8 + 5] = a5[col];
            output[col * 8 + 6] = a6[col];
            output[col * 8 + 7] = a7[col];
        }
    }
}

/// 1D DCT on all 8 rows (no per-row scaling, scaling handled in main function)
/// Uses row-major processing for good cache locality
#[cfg(feature = "simd")]
#[inline]
fn dct_rows(input: &[f32; 64], output: &mut [f32; 64]) {
    // Process rows sequentially (good cache access pattern)
    // The DCT algorithm doesn't parallelize well within a single row
    for row in 0..8 {
        let mut tmp = [0.0f32; 8];
        for i in 0..8 {
            tmp[i] = input[row * 8 + i];
        }
        dct1d_8(&mut tmp);
        for i in 0..8 {
            output[row * 8 + i] = tmp[i];
        }
    }
}

/// Performs an 8x8 forward DCT on the input block.
///
/// The input should be pixel values (typically shifted by -128 for level shift).
/// The output is DCT coefficients ready for quantization.
/// Includes 1/8 scaling for JPEG decoder compatibility.
///
/// Uses SIMD optimization when the `simd` feature is enabled.
///
/// # Arguments
/// * `input` - 8x8 block of input values in row-major order
///
/// # Returns
/// 8x8 block of DCT coefficients
#[inline]
#[must_use]
pub fn forward_dct_8x8(input: &[f32; DCT_BLOCK_SIZE]) -> [f32; DCT_BLOCK_SIZE] {
    let mut scratch = [0.0f32; 64];
    let mut coefficients = [0.0f32; 64];

    // Row transform
    dct_rows(input, &mut scratch);

    // Transpose (use SIMD version when available)
    #[cfg(feature = "simd")]
    simd::transpose_8x8_simd(&scratch, &mut coefficients);
    #[cfg(not(feature = "simd"))]
    transpose_8x8(&scratch, &mut coefficients);

    // Column transform (on transposed data)
    dct_rows(&coefficients, &mut scratch);

    // Transpose back
    #[cfg(feature = "simd")]
    simd::transpose_8x8_simd(&scratch, &mut coefficients);
    #[cfg(not(feature = "simd"))]
    transpose_8x8(&scratch, &mut coefficients);

    // Apply 1/8 scaling for JPEG decoder compatibility (SIMD-optimized)
    // Note: C++ jpegli applies 1/8 per dimension (1/64 total), but standard JPEG
    // decoders like libjpeg/jpeg-decoder expect 1/8 total scaling.
    // Using 1/64 here breaks compatibility (decoded values are 8× too small).
    #[cfg(feature = "simd")]
    {
        let scale = f32x8::splat(1.0 / 8.0);
        for chunk in 0..8 {
            let k = chunk * 8;
            let v = f32x8::from([
                coefficients[k],
                coefficients[k + 1],
                coefficients[k + 2],
                coefficients[k + 3],
                coefficients[k + 4],
                coefficients[k + 5],
                coefficients[k + 6],
                coefficients[k + 7],
            ]);
            let scaled = v * scale;
            let arr: [f32; 8] = scaled.into();
            coefficients[k..k + 8].copy_from_slice(&arr);
        }
    }
    #[cfg(not(feature = "simd"))]
    {
        let scale = 1.0 / 8.0;
        for v in &mut coefficients {
            *v *= scale;
        }
    }

    coefficients
}

/// Performs forward DCT on a block with level shift.
///
/// # Arguments
/// * `input` - 8x8 block of 8-bit pixel values
///
/// # Returns
/// 8x8 block of DCT coefficients
#[must_use]
pub fn forward_dct_8x8_u8(input: &[u8; DCT_BLOCK_SIZE]) -> [f32; DCT_BLOCK_SIZE] {
    // Convert to f32 with level shift (-128)
    #[cfg(feature = "simd")]
    {
        let mut shifted = [0.0f32; DCT_BLOCK_SIZE];
        let level_shift = f32x8::splat(128.0);

        // Process 8 values at a time
        for chunk in 0..8 {
            let k = chunk * 8;
            let v = f32x8::from([
                input[k] as f32,
                input[k + 1] as f32,
                input[k + 2] as f32,
                input[k + 3] as f32,
                input[k + 4] as f32,
                input[k + 5] as f32,
                input[k + 6] as f32,
                input[k + 7] as f32,
            ]);
            let result = v - level_shift;
            let arr: [f32; 8] = result.into();
            shifted[k..k + 8].copy_from_slice(&arr);
        }

        forward_dct_8x8(&shifted)
    }

    #[cfg(not(feature = "simd"))]
    {
        let mut shifted = [0.0f32; DCT_BLOCK_SIZE];
        for (i, &v) in input.iter().enumerate() {
            shifted[i] = v as f32 - 128.0;
        }
        forward_dct_8x8(&shifted)
    }
}

/// Performs forward DCT on multiple blocks.
pub fn forward_dct_blocks(blocks: &[[f32; DCT_BLOCK_SIZE]]) -> Vec<[f32; DCT_BLOCK_SIZE]> {
    blocks.iter().map(forward_dct_8x8).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dct_dc_only() {
        // Constant block should have only DC coefficient
        let input = [128.0f32; DCT_BLOCK_SIZE];
        let output = forward_dct_8x8(&input);

        // DC coefficient should be non-zero
        assert!(output[0].abs() > 1.0);

        // AC coefficients should be near zero
        for i in 1..DCT_BLOCK_SIZE {
            assert!(
                output[i].abs() < 0.001,
                "AC[{}] = {} should be ~0",
                i,
                output[i]
            );
        }
    }

    #[test]
    fn test_dct_zero_block() {
        let input = [0.0f32; DCT_BLOCK_SIZE];
        let output = forward_dct_8x8(&input);

        for (i, &v) in output.iter().enumerate() {
            assert!(v.abs() < 0.001, "coeff[{}] = {} should be 0", i, v);
        }
    }

    #[test]
    fn test_dct_u8_level_shift() {
        // All 128s should produce near-zero output (after -128 shift)
        let input = [128u8; DCT_BLOCK_SIZE];
        let output = forward_dct_8x8_u8(&input);

        for (i, &v) in output.iter().enumerate() {
            assert!(v.abs() < 0.001, "coeff[{}] = {} should be 0", i, v);
        }
    }

    #[test]
    fn test_transpose() {
        let mut input = [0.0f32; 64];
        for i in 0..64 {
            input[i] = i as f32;
        }

        let mut output = [0.0f32; 64];
        transpose_8x8(&input, &mut output);

        // Check a few values
        assert_eq!(output[0], 0.0); // (0,0)
        assert_eq!(output[1], 8.0); // (0,1) <- (1,0) in original
        assert_eq!(output[8], 1.0); // (1,0) <- (0,1) in original
        assert_eq!(output[9], 9.0); // (1,1)
    }

    #[cfg(feature = "simd")]
    #[test]
    fn test_simd_transpose_matches_scalar() {
        let mut input = [0.0f32; 64];
        for i in 0..64 {
            input[i] = (i as f32 * 1.7).sin() * 100.0;
        }

        let mut scalar_output = [0.0f32; 64];
        let mut simd_output = [0.0f32; 64];

        transpose_8x8(&input, &mut scalar_output);
        simd::transpose_8x8_simd(&input, &mut simd_output);

        for i in 0..64 {
            assert!(
                (scalar_output[i] - simd_output[i]).abs() < 1e-6,
                "Mismatch at {}: scalar={} simd={}",
                i,
                scalar_output[i],
                simd_output[i]
            );
        }
    }

    #[cfg(feature = "simd")]
    #[test]
    fn test_simd_dct_rows_matches_scalar() {
        // Test with various input patterns
        let patterns: Vec<[f32; 64]> = vec![
            // Constant block
            [64.0; 64],
            // Gradient
            {
                let mut arr = [0.0f32; 64];
                for i in 0..64 {
                    arr[i] = i as f32;
                }
                arr
            },
            // Sinusoidal pattern
            {
                let mut arr = [0.0f32; 64];
                for i in 0..64 {
                    arr[i] = (i as f32 * 0.3).sin() * 100.0;
                }
                arr
            },
            // Checkerboard
            {
                let mut arr = [0.0f32; 64];
                for row in 0..8 {
                    for col in 0..8 {
                        arr[row * 8 + col] = if (row + col) % 2 == 0 { 100.0 } else { -100.0 };
                    }
                }
                arr
            },
        ];

        for (pattern_idx, input) in patterns.iter().enumerate() {
            // Scalar implementation
            let mut scalar_output = [0.0f32; 64];
            for row in 0..8 {
                let mut tmp = [0.0f32; 8];
                for i in 0..8 {
                    tmp[i] = input[row * 8 + i];
                }
                dct1d_8(&mut tmp);
                for i in 0..8 {
                    scalar_output[row * 8 + i] = tmp[i];
                }
            }

            // SIMD implementation
            let mut simd_output = [0.0f32; 64];
            simd::dct_8rows_parallel(input, &mut simd_output);

            // Compare
            let mut max_error = 0.0f32;
            for i in 0..64 {
                let error = (scalar_output[i] - simd_output[i]).abs();
                max_error = max_error.max(error);
            }

            assert!(
                max_error < 1e-4,
                "Pattern {}: SIMD DCT rows max error {} exceeds threshold",
                pattern_idx,
                max_error
            );
        }
    }
}
