//! Per-encoder, per-strategy achieved-quality + size-ratio tables,
//! measured from forced-strategy recompress-sweeps on REAL encoder
//! output (pinned libjpeg-turbo 3.1.0, mozjpeg 4.1.5, jpegli), with
//! HybridMaxCompression re-encode params.
//!
//! These replace the jpegli-only `data::lookup_420` projection for the
//! turbo/mozjpeg/jpegli encoder classes. They capture two facts the
//! single jpegli table could not:
//!   - **Preserve craters** on aggressive non-jpegli targets (large
//!     source−target gap): coefficient-domain requantization of
//!     turbo/mozjpeg tables over-quantizes (turbo src90→t50 achieves
//!     ~13, not 50).
//!   - **Tuned floors** but never craters: re-encoding decoded pixels
//!     is source-encoder-independent and well-behaved, but cannot
//!     deliver very-low targets from very-high-quality sources (the
//!     decoded pixels are already good).
//!
//! The router uses these to pick the strategy whose projected achieved
//! lands closest to (and at-or-above) the target — routing aggressive
//! non-jpegli recompression to Tuned and avoiding Preserve's cliff.
//!
//! Fit on 50 CID22-512 refs (2026-05-29 recalibration); see
//! `benchmarks/calibration-n50-2026-05-29.pointer.md` for provenance.

use crate::recompress::api::StrategyKind;
use crate::recompress::calibration::EncoderClass;

/// `(achieved_quality, size_ratio)` per-encoder table pair, each a 6×6
/// grid over `PE_SRC_BUCKETS` × `PE_TARGETS`.
type AchievedRatioTables = (&'static [[f32; 6]; 6], &'static [[f32; 6]; 6]);

// === BEGIN GENERATED TABLES ===
// Everything between the BEGIN/END markers is regenerated by
// `scripts/fit_per_encoder.py` (driven by `scripts/recalibrate.sh`).
// Do not edit by hand — edit the fitter / re-run the sweep instead.
// Auto-generated 2026-05-29 from forced-strategy recompress-sweeps
//  on pinned libjpeg-turbo + mozjpeg + jpegli, HybridMaxCompression.
//  Corpus: 50 CID22-512 references × 16 source-q (q20-95 step 5).
//  Each cell is the MEDIAN over all (image, source-q) pairs whose
//  source-estimate / target fall in that bucket.
//  Rows = source-estimate zensim-A bucket [40,50,60,70,80,90];
//  cols = target [30,40,50,60,70,80].
pub const PE_SRC_BUCKETS: &[f32] = &[40.0, 50.0, 60.0, 70.0, 80.0, 90.0];
pub const PE_TARGETS: &[f32] = &[30.0, 40.0, 50.0, 60.0, 70.0, 80.0];
#[rustfmt::skip]
pub const TURBO_PRESERVE_ACHIEVED: &[[f32; 6]; 6] = &[
    [40.3, 43.9, 43.9, 43.9, 43.9, 43.9],
    [35.3, 51.1, 54.5, 54.5, 54.5, 54.5],
    [32.2, 45.1, 56.2, 63.9, 63.9, 63.9],
    [40.9, 48.6, 52.9, 63.8, 67.5, 70.0],
    [59.6, 64.0, 64.1, 73.2, 78.8, 80.3],
    [71.8, 77.6, 79.5, 81.2, 83.7, 85.4],
];
#[rustfmt::skip]
pub const TURBO_PRESERVE_RATIO: &[[f32; 6]; 6] = &[
    [0.9913, 0.9982, 0.9982, 0.9982, 0.9982, 0.9982],
    [0.9210, 0.9948, 0.9985, 0.9985, 0.9985, 0.9985],
    [0.8009, 0.9130, 0.9782, 0.9986, 0.9988, 0.9988],
    [0.5220, 0.5707, 0.8777, 0.9212, 0.9988, 0.9991],
    [0.5193, 0.5570, 0.5999, 0.8848, 0.9667, 0.9994],
    [0.4251, 0.5315, 0.5644, 0.7172, 0.8665, 0.9996],
];
#[rustfmt::skip]
pub const TURBO_TUNED_ACHIEVED: &[[f32; 6]; 6] = &[
    [37.6, 39.0, 39.3, 40.2, 40.7, 41.2],
    [43.3, 46.9, 49.9, 51.5, 51.9, 52.8],
    [47.6, 52.3, 53.9, 57.5, 60.3, 62.7],
    [49.0, 53.4, 56.3, 63.8, 64.1, 65.8],
    [50.8, 55.3, 58.0, 63.9, 66.8, 76.2],
    [51.7, 55.9, 59.3, 64.0, 68.0, 79.0],
];
#[rustfmt::skip]
pub const TURBO_TUNED_RATIO: &[[f32; 6]; 6] = &[
    [0.9308, 0.9857, 1.0200, 1.0760, 1.1337, 1.3305],
    [0.7796, 0.8919, 0.9423, 1.0095, 1.0804, 1.2433],
    [0.6217, 0.7094, 0.7864, 0.9109, 0.9962, 1.1791],
    [0.4685, 0.5391, 0.5973, 0.7150, 0.8490, 1.0750],
    [0.3156, 0.3608, 0.3980, 0.4741, 0.5940, 0.8772],
    [0.1794, 0.2031, 0.2205, 0.2564, 0.3162, 0.5127],
];
#[rustfmt::skip]
pub const MOZJPEG_PRESERVE_ACHIEVED: &[[f32; 6]; 6] = &[
    [f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN],
    [f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN],
    [41.3, 47.1, 55.2, 63.9, 65.7, 65.7],
    [40.6, 51.1, 53.5, 64.0, 67.6, 71.4],
    [45.1, 55.9, 63.8, 64.2, 71.3, 79.2],
    [48.3, 59.5, 64.0, 71.3, 75.8, 85.3],
];
#[rustfmt::skip]
pub const MOZJPEG_PRESERVE_RATIO: &[[f32; 6]; 6] = &[
    [f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN],
    [f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN, f32::NAN],
    [0.5737, 0.6140, 0.9240, 0.9772, 1.0474, 1.0474],
    [0.5587, 0.5889, 0.6227, 0.9317, 1.0092, 1.0419],
    [0.3866, 0.5102, 0.5667, 0.6234, 0.9140, 1.0416],
    [0.2347, 0.2953, 0.3695, 0.4214, 0.5389, 0.9673],
];
#[rustfmt::skip]
pub const MOZJPEG_TUNED_ACHIEVED: &[[f32; 6]; 6] = &[
    [32.4, 33.7, 35.0, 37.1, 38.4, 39.1],
    [45.4, 46.3, 47.7, 50.7, 51.8, 52.6],
    [46.5, 52.0, 54.3, 58.8, 60.5, 63.7],
    [49.7, 53.0, 55.2, 63.7, 64.7, 68.2],
    [48.7, 53.7, 58.5, 64.0, 67.5, 74.0],
    [54.4, 61.1, 64.1, 70.3, 74.6, 83.4],
];
#[rustfmt::skip]
pub const MOZJPEG_TUNED_RATIO: &[[f32; 6]; 6] = &[
    [1.0722, 1.1192, 1.1685, 1.2160, 1.2635, 1.4803],
    [0.9297, 0.9969, 1.0357, 1.0979, 1.1816, 1.3486],
    [0.6863, 0.8100, 0.8868, 0.9761, 1.0549, 1.2264],
    [0.5245, 0.5875, 0.6301, 0.7649, 0.9085, 1.1269],
    [0.4045, 0.4592, 0.4982, 0.5879, 0.6998, 0.9264],
    [0.2140, 0.2450, 0.2710, 0.3261, 0.4021, 0.6155],
];
#[rustfmt::skip]
pub const JPEGLI_PRESERVE_ACHIEVED: &[[f32; 6]; 6] = &[
    [40.0, 42.3, 44.9, 44.9, 44.9, 44.9],
    [44.3, 49.9, 51.4, 54.0, 54.0, 54.0],
    [45.6, 55.0, 57.1, 60.3, 63.9, 63.9],
    [46.7, 57.3, 63.9, 64.1, 65.6, 68.5],
    [40.1, 57.7, 63.4, 69.6, 74.3, 76.1],
    [55.7, 64.1, 64.4, 75.2, 78.5, 85.3],
];
#[rustfmt::skip]
pub const JPEGLI_PRESERVE_RATIO: &[[f32; 6]; 6] = &[
    [1.1425, 1.1867, 1.2001, 1.2012, 1.2012, 1.2012],
    [1.0211, 1.1000, 1.1375, 1.1647, 1.1677, 1.1677],
    [0.9207, 1.0231, 1.0699, 1.1250, 1.1398, 1.1422],
    [0.7755, 0.8929, 0.9693, 1.0441, 1.0960, 1.1189],
    [0.6385, 0.6768, 0.7352, 0.9619, 1.0663, 1.0978],
    [0.3936, 0.4819, 0.6038, 0.6458, 0.9015, 1.0686],
];
#[rustfmt::skip]
pub const JPEGLI_TUNED_ACHIEVED: &[[f32; 6]; 6] = &[
    [40.2, 40.9, 41.7, 42.1, 43.4, 44.0],
    [49.6, 48.6, 48.7, 50.1, 51.7, 53.3],
    [49.4, 55.4, 57.8, 57.0, 59.2, 63.7],
    [50.0, 56.1, 62.3, 64.1, 64.1, 66.1],
    [52.3, 57.7, 63.8, 65.0, 72.0, 74.4],
    [53.8, 60.8, 64.0, 69.6, 73.8, 82.9],
];
#[rustfmt::skip]
pub const JPEGLI_TUNED_RATIO: &[[f32; 6]; 6] = &[
    [1.0088, 1.0619, 1.0892, 1.1349, 1.1903, 1.3756],
    [0.9513, 0.9950, 1.0212, 1.0823, 1.1318, 1.3044],
    [0.8381, 0.9392, 0.9789, 1.0345, 1.0979, 1.2582],
    [0.6743, 0.7733, 0.8495, 0.9709, 1.0307, 1.1942],
    [0.5320, 0.6089, 0.6637, 0.7795, 0.9363, 1.1168],
    [0.3342, 0.3809, 0.4188, 0.4905, 0.5833, 0.9152],
];
// === END GENERATED TABLES ===

// --- Expected generation-loss (vs-source) tables — Lever 4 ----------------
//
// `*_GEXP[src][tgt]` is the MEDIAN zensim-A of the recompressed output
// measured against the SOURCE jpeg (i.e. generation loss, NOT vs the
// original) for a cell at (source-estimate bucket, target/dial). This is
// the quantity the closed loop CAN measure at production time — the
// original reference is unavailable. Rows/cols share the `PE_SRC_BUCKETS`
// / `PE_TARGETS` axes.
//
// Provenance: fit 2026-05-29 from the n=50 CID22-512 end-to-end router
// validation sweeps (the `MaxIterations(1)` measured-vs-source column),
// median over dial-bearing (tuned/preserve) cells. See
// benchmarks/calibration-n50-2026-05-29.pointer.md. NaN = no recompression
// data (source ≤ target ⇒ NoOp). These are hand-fit from the val data
// rather than auto-spliced because the forced-strategy sweep runs OneShot
// and does not record vs-source; regenerating them through
// `scripts/recalibrate.sh` needs the forced sweep switched to
// `MaxIterations(1)` first (tracked follow-up).
//
// Why the closed loop uses these: within a cell, per-image deviation in
// vs-source generation loss tracks per-image deviation in achieved-vs-
// original almost 1:1 (corr 0.80, slope ≈ 1.1, 88% sign concordance on
// the n=50 val data). So `A_hat = anchor + SLOPE·(g_measured − GEXP)`
// recovers the per-image achieved estimate the bucket-median calibration
// cannot.
const NAN: f32 = f32::NAN;
#[rustfmt::skip]
pub const TURBO_GEXP: &[[f32; 6]; 6] = &[
    [76.6,  NAN,  NAN,  NAN,  NAN,  NAN],
    [71.8, 74.5,  NAN,  NAN,  NAN,  NAN],
    [64.1, 64.1, 75.4,  NAN,  NAN,  NAN],
    [56.4, 56.4, 64.1, 81.0,  NAN,  NAN],
    [55.2, 55.2, 59.6, 69.7, 85.8,  NAN],
    [55.0, 55.0, 57.8, 66.7, 78.3, 84.3],
];
#[rustfmt::skip]
pub const MOZJPEG_GEXP: &[[f32; 6]; 6] = &[
    [83.0,  NAN,  NAN,  NAN,  NAN,  NAN],
    [75.3, 84.9,  NAN,  NAN,  NAN,  NAN],
    [65.7, 71.7, 78.3,  NAN,  NAN,  NAN],
    [60.3, 60.3, 64.5, 81.0,  NAN,  NAN],
    [47.1, 47.1, 63.8, 72.8, 85.6,  NAN],
    [56.1, 56.1, 56.1, 64.3, 76.6, 87.0],
];
#[rustfmt::skip]
pub const JPEGLI_GEXP: &[[f32; 6]; 6] = &[
    [ NAN,  NAN,  NAN,  NAN,  NAN,  NAN],
    [67.2,  NAN,  NAN,  NAN,  NAN,  NAN],
    [61.6, 74.4, 81.1,  NAN,  NAN,  NAN],
    [53.8, 68.0, 75.6, 84.0,  NAN,  NAN],
    [41.1, 62.9, 67.9, 77.6,  NAN,  NAN],
    [54.8, 63.3, 62.2, 78.0, 82.2, 88.1],
];

/// Within-cell slope `d(achieved-vs-original) / d(generation-loss-vs-
/// source)`, fit on the n=50 val data (corr 0.80). Used by the closed
/// loop to convert a measured generation-loss deviation into an
/// achieved-quality correction.
pub const GEXP_SLOPE: f32 = 1.1;

/// Expected generation loss (vs source) for a cell, or `None` if the
/// encoder has no GEXP table. Spirals out of NaN cells like [`lookup`].
pub fn gexp_lookup(encoder: EncoderClass, source_est: f32, dial: f32) -> Option<f32> {
    let table = match encoder {
        EncoderClass::IjgFamily => TURBO_GEXP,
        EncoderClass::Mozjpeg | EncoderClass::ImageMagick => MOZJPEG_GEXP,
        EncoderClass::JpegliYcbcr | EncoderClass::JpegliXyb => JPEGLI_GEXP,
        _ => return None,
    };
    let si = nearest_idx(source_est, PE_SRC_BUCKETS);
    let ti = nearest_idx(dial, PE_TARGETS);
    nearest_finite(table, si, ti)
}

/// Look up `(projected_achieved, projected_size_ratio)` for an encoder ×
/// strategy × (source_estimate, target) cell. `None` if this
/// encoder/strategy has no per-encoder table (caller falls back to the
/// jpegli `data::lookup_*`).
pub fn lookup(
    encoder: EncoderClass,
    strategy: StrategyKind,
    source_est: f32,
    target: f32,
) -> Option<(f32, f32)> {
    let (ach, rat) = tables_for(encoder, strategy)?;
    let si = nearest_idx(source_est, PE_SRC_BUCKETS);
    let ti = nearest_idx(target, PE_TARGETS);
    let a = nearest_finite(ach, si, ti)?;
    let r = nearest_finite(rat, si, ti)?;
    Some((a, r))
}

/// Table family by encoder: libjpeg-turbo / IJG / Pillow use standard
/// IJG (Annex K) tables → TURBO_* tables. mozjpeg AND ImageMagick use
/// Robidoux tables → MOZJPEG_* tables (the Robidoux-source proxy;
/// ImageMagick itself is not yet directly swept). This grouping follows
/// the quant-table family, which governs how coefficients requantize.
/// Returns `None` for jpegli — it keeps the richer 15-image
/// `data::lookup_420/444` calibration.
fn tables_for(encoder: EncoderClass, strategy: StrategyKind) -> Option<AchievedRatioTables> {
    let _ = (JPEGLI_PRESERVE_ACHIEVED, JPEGLI_TUNED_ACHIEVED); // keep alive
    Some(match (encoder, strategy) {
        (EncoderClass::IjgFamily, StrategyKind::Preserve) => {
            (TURBO_PRESERVE_ACHIEVED, TURBO_PRESERVE_RATIO)
        }
        (EncoderClass::IjgFamily, _) => (TURBO_TUNED_ACHIEVED, TURBO_TUNED_RATIO),
        (EncoderClass::Mozjpeg | EncoderClass::ImageMagick, StrategyKind::Preserve) => {
            (MOZJPEG_PRESERVE_ACHIEVED, MOZJPEG_PRESERVE_RATIO)
        }
        (EncoderClass::Mozjpeg | EncoderClass::ImageMagick, _) => {
            (MOZJPEG_TUNED_ACHIEVED, MOZJPEG_TUNED_RATIO)
        }
        _ => return None,
    })
}

/// Inverse calibration: find the **target dial** (in zensim-A, on the
/// `PE_TARGETS` axis) that makes this strategy actually *achieve*
/// `user_target` on a source at `source_est`, plus the projected size
/// ratio at that dial. This corrects the strategy's systematic over/
/// under-shoot — feed the returned dial to `target_zensim_a_to_ijg_q`
/// so the strategy lands on `user_target` rather than the achieved
/// value at the naive dial.
///
/// Returns `(dial_zensim_a, projected_size_ratio, projected_achieved)`.
/// When `user_target` is bracketed by the row, `projected_achieved ==
/// user_target` (we dialed to hit it). When the target is below the
/// achievable floor (gentlest dial over-delivers), `projected_achieved`
/// is that floor (> target, safe); when above the ceiling (coarsest dial
/// can't reach it), it's the ceiling (< target).
pub fn invert_dial(
    encoder: EncoderClass,
    strategy: StrategyKind,
    source_est: f32,
    user_target: f32,
) -> Option<(f32, f32, f32)> {
    let (ach, rat) = tables_for(encoder, strategy)?;
    let si = nearest_idx(source_est, PE_SRC_BUCKETS);
    // Achieved as a function of dial along this source row, skipping NaN.
    let row: Vec<(f32, f32, f32)> = (0..PE_TARGETS.len())
        .filter_map(|ti| {
            let a = nearest_finite(ach, si, ti)?;
            let r = nearest_finite(rat, si, ti)?;
            Some((PE_TARGETS[ti], a, r))
        })
        .collect();
    if row.is_empty() {
        return None;
    }
    // achieved is (mostly) monotone increasing in dial. Find the dial
    // bracket where achieved crosses user_target and interpolate.
    for w in row.windows(2) {
        let (d0, a0, r0) = w[0];
        let (d1, a1, r1) = w[1];
        let (lo, hi) = if a0 <= a1 { (a0, a1) } else { (a1, a0) };
        if user_target >= lo && user_target <= hi && (a1 - a0).abs() > 1e-3 {
            let t = (user_target - a0) / (a1 - a0);
            return Some((d0 + t * (d1 - d0), r0 + t * (r1 - r0), user_target));
        }
    }
    let &(d_lo, a_lo, r_lo) = row.first().unwrap();
    let &(d_hi, a_hi, r_hi) = row.last().unwrap();
    if user_target < a_lo.min(a_hi) {
        // over-deliver floor: gentlest available, lowest achieved/file.
        if a_lo <= a_hi {
            Some((d_lo, r_lo, a_lo))
        } else {
            Some((d_hi, r_hi, a_hi))
        }
    } else {
        // can't reach: coarsest available, highest achieved.
        if a_hi >= a_lo {
            Some((d_hi, r_hi, a_hi))
        } else {
            Some((d_lo, r_lo, a_lo))
        }
    }
}

fn nearest_idx(v: f32, axis: &[f32]) -> usize {
    let mut best = 0;
    let mut bd = f32::INFINITY;
    for (i, &a) in axis.iter().enumerate() {
        let d = (v - a).abs();
        if d < bd {
            bd = d;
            best = i;
        }
    }
    best
}

/// Read `t[si][ti]`; if NaN, spiral out to the nearest covered cell.
fn nearest_finite(t: &[[f32; 6]; 6], si: usize, ti: usize) -> Option<f32> {
    if t[si][ti].is_finite() {
        return Some(t[si][ti]);
    }
    for radius in 1..6usize {
        for ds in -(radius as isize)..=(radius as isize) {
            for dt in -(radius as isize)..=(radius as isize) {
                if ds.abs() != radius as isize && dt.abs() != radius as isize {
                    continue;
                }
                let r = si as isize + ds;
                let c = ti as isize + dt;
                if (0..6).contains(&r) && (0..6).contains(&c) {
                    let v = t[r as usize][c as usize];
                    if v.is_finite() {
                        return Some(v);
                    }
                }
            }
        }
    }
    None
}
