//! Locked SHA256 hash tests for frymire.png encoding.
//!
//! These tests verify that encoder output is byte-for-byte reproducible.
//! Any refactoring that changes output will break these tests.
//!
//! Test image: tests/images/frymire.png (1118x1105 RGB)
//!
//! To regenerate hashes after intentional changes:
//!   cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
//!
//! ⚠️ LOCKED TEST: Do NOT modify hash values without understanding the impact.

use enough::Never;
use jpegli::{ChromaSubsampling, DownsamplingMethod, EncoderConfig, PixelLayout};
use sha2::{Digest, Sha256};
use std::fs;

// =============================================================================
// CONFIGURATION
// =============================================================================

/// Quality levels to test (representative sample)
const QUALITY_LEVELS: &[u8] = &[50, 75, 90];

// =============================================================================
// EXPECTED HASHES (generated by print_all_hashes)
// Format: (config_name, quality, sha256_hex)
// =============================================================================

// frymire.png: 1118x1105
// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
// Updated 2026-01-13: After API cleanup (v2 Quality type changes)
const EXPECTED_HASHES: &[(&str, u8, &str)] = &[
    ("baseline_444_opt", 50, "eb3cc572c77faa01b9c29b3bdc8249cb73d499ada88d19d549837f9798166507"), // 329966 bytes
    ("baseline_444_opt", 75, "87336e7079c100ba2c49005a53b3ba4e89b11dccdb5a991d901abd8c6322704b"), // 476900 bytes
    ("baseline_444_opt", 90, "2a4d16a893513486f3e86dd5af016664af9c33148c00ab6a33bd31d06eb05ea6"), // 717812 bytes
    ("baseline_444_fixed", 50, "14ec7ec6244943fb270b0ee2954fff3dbb7cadcf11fd10b2f8dc121e14749a97"), // 344432 bytes
    ("baseline_444_fixed", 75, "c248f3c50bc10e8bddb6d5817e81429f98e50d191a08113e814ca4dc3845c476"), // 496277 bytes
    ("baseline_444_fixed", 90, "c1758b66e897183e540e1bb77d6de883b4601878c27eb81ac74645e8bdfeb5c6"), // 766785 bytes
    ("baseline_420_opt", 50, "8dc8974376a70894a5ce369861dcff60527a369b0189f80e4899e0976e87f923"), // 269852 bytes
    ("baseline_420_opt", 75, "406c924a2bb28e2885ef87f4f048917f903390610604ac7091f3be838378ec02"), // 397281 bytes
    ("baseline_420_opt", 90, "76fd92b1fa95d0e9e141a3c199fe4c7dbdb9236b5fc73f1859bb90b321cb5e3a"), // 584347 bytes
    ("baseline_420_gamma", 50, "971fc61aec8d8ae79876d0ae66e0067994564131d7f7ecc7d5aafd8ba2f900a0"), // 270771 bytes
    ("baseline_420_gamma", 75, "34be3b723c3e72aad9c571fa615ced904a7437b91db3b93cd2ad26520559b224"), // 398916 bytes
    ("baseline_420_gamma", 90, "0885e8f27e55e64c3a6303eaab1a78503cb69788b301194f861b4471d516b77e"), // 586888 bytes
    ("baseline_420_sharpyuv", 50, "a1a202733034213594acef37b9d1d9269066e6ad036cf61c6b4b953968da544e"), // 270349 bytes
    ("baseline_420_sharpyuv", 75, "cf8b0719b0db7e0d1af0109ee7015417f8092f53b9180d3aa2b9cbeeef33f7b3"), // 398174 bytes
    ("baseline_420_sharpyuv", 90, "0e0e8a0e35ea5d0c71e93fe39ddb271ed1c6c7139e27ae53318e8119fe99a516"), // 585699 bytes
    ("baseline_422_opt", 50, "f6509e9d6e1e3765fde4195728348b9bb0494b6ae6d4600850478621f9f4de02"), // 293489 bytes
    ("baseline_422_opt", 75, "804623708de02d685217475f91028793687af53a3da41adf6d34803937e9023a"), // 419254 bytes
    ("baseline_422_opt", 90, "38b35697d09ba05108dffbfffa8dce616dc933972808dc11c364337415939873"), // 613614 bytes
    ("baseline_440_opt", 50, "0a79ee0066277911a666dcae13aecacd15c67fb9c59a58c5dfac81c74431d67e"), // 293693 bytes
    ("baseline_440_opt", 75, "32b8ea3588c5b0a6a9fa801fe0f96c4b3d41036c199f8aa411f2a02bfd350c23"), // 419896 bytes
    ("baseline_440_opt", 90, "b73f8956872b4328607ef85fdfe505afa400c29db21f9406d45d2f95650fc7e3"), // 615445 bytes
    ("progressive_444_opt", 50, "a55c17249bbd972b54147147b1d170edd81338d6777d83f3b1bf365e5e90c679"), // 320773 bytes
    ("progressive_444_opt", 75, "3617dc3ee52aecd238389c9b70e24b00f266ceae2f072e4e02f4b49cf5fa58df"), // 462657 bytes
    ("progressive_444_opt", 90, "449120f11d690a67fd3aa7bc4f3fcb2bc7a69db5704672fe1babde07ae396fd4"), // 696599 bytes
    ("progressive_420_opt", 50, "196a605982f37bc0e4c3d9d73bc6144cd4aeb5897b61f86ac09def8224ba355f"), // 261089 bytes
    ("progressive_420_opt", 75, "07af1d94f45cf3fc1430ef383900ab01d1f591bf1efe08f938d9a9202526ae1b"), // 383821 bytes
    ("progressive_420_opt", 90, "591b020c3e60284880948571230e19ca3a42f9a7d3dd25f16d549c40c8cf13cf"), // 564225 bytes
    ("baseline_xyb_opt", 50, "4acbed2702fbe5c5f715abf3244fb7e15dc24f2cfaba863e1c0ca1903fe6e261"), // 272721 bytes
    ("baseline_xyb_opt", 75, "7164095810fa874bd42a02fe5ca03f7ad5cc79e2cd4f48ef2c94cfd72a91bd64"), // 397271 bytes
    ("baseline_xyb_opt", 90, "d03c14584c4cd0f1a93a97adcb7a1952b9b32957a4d0d564ff4bc7ea3d0f501d"), // 614790 bytes
    ("baseline_xyb_fixed", 50, "2e900de46dfa1551095b29ef96024f718bc995dbd1f1851abf3a2fbc05157b34"), // 294825 bytes
    ("baseline_xyb_fixed", 75, "2f99e2c32f2ab7b865406d8d4d743a50f69c2fc681ecea19b98af4da51c5b3c2"), // 418890 bytes
    ("baseline_xyb_fixed", 90, "8ee8a6274e096413502d5da1ad1645b18e255434ea070c54f814c177a5613a3d"), // 651998 bytes
    ("progressive_xyb_opt", 50, "bd3553c55481487fbe6c8bd1e6d1e973b1c570e457758d08337f1b83d9e24694"), // 270465 bytes
    ("progressive_xyb_opt", 75, "315e2e478077bcb75d85880e5bd95cd5c926f4485b85a9641628d14898a13e23"), // 396193 bytes
    ("progressive_xyb_opt", 90, "ba69c7cd8242e2f24ac55c7c44639e3e81f16d01a8842d830363498a46db5ba5"), // 615329 bytes
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn load_frymire() -> (Vec<u8>, u32, u32) {
    let png_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/images/frymire.png");
    let png_data = fs::read(&png_path).expect("Failed to read frymire.png");
    let decoder = png::Decoder::new(&png_data[..]);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();

    let rgb: Vec<u8> = match info.color_type {
        png::ColorType::Rgb => buf[..info.buffer_size()].to_vec(),
        png::ColorType::Rgba => buf[..info.buffer_size()]
            .chunks(4)
            .flat_map(|c| [c[0], c[1], c[2]])
            .collect(),
        _ => panic!("Unsupported color type"),
    };

    (rgb, info.width, info.height)
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

/// Encoding configuration for testing
#[derive(Clone, Debug)]
struct EncoderTestConfig {
    name: &'static str,
    progressive: bool,
    subsampling: ChromaSubsampling,
    optimize_huffman: bool,
    downsampling_method: DownsamplingMethod,
    use_xyb: bool,
}

impl EncoderTestConfig {
    fn encode(&self, rgb: &[u8], width: u32, height: u32, quality: f32) -> Vec<u8> {
        let mut config = EncoderConfig::new()
            .quality(quality)
            .progressive(self.progressive)
            .ycbcr(self.subsampling)
            .optimize_huffman(self.optimize_huffman)
            .downsampling_method(self.downsampling_method);
        if self.use_xyb {
            config = config.xyb();
        }
        let mut enc = config
            .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
            .expect("encoder setup");
        enc.push_packed(rgb, Never).expect("push data");
        enc.finish().expect("Encoding failed")
    }

    fn mcu_size(&self) -> usize {
        match self.subsampling {
            ChromaSubsampling::Full => 8,
            _ => 16, // All subsampled modes have MCU size of 16
        }
    }
}

/// All configurations to test
fn test_configs() -> Vec<EncoderTestConfig> {
    vec![
        // Baseline modes (YCbCr)
        EncoderTestConfig {
            name: "baseline_444_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Full,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_444_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::Full,
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_gamma",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAware,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_sharpyuv",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAwareIterative,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_422_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfHorizontal,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_440_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfVertical,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // Progressive modes (YCbCr)
        EncoderTestConfig {
            name: "progressive_444_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Full,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "progressive_420_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // XYB modes (subsampling is ignored for XYB)
        EncoderTestConfig {
            name: "baseline_xyb_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "baseline_xyb_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "progressive_xyb_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
    ]
}

// =============================================================================
// TESTS
// =============================================================================

/// Verify all configurations produce expected hashes.
/// This test is skipped until hashes are populated.
#[test]
fn test_frymire_hashes_locked() {
    if EXPECTED_HASHES.is_empty() {
        println!("No hashes configured yet. Run print_all_hashes to generate.");
        return;
    }

    let (rgb, width, height) = load_frymire();

    for (config_name, quality, expected_hash) in EXPECTED_HASHES {
        let config = test_configs()
            .into_iter()
            .find(|c| c.name == *config_name)
            .expect("Unknown config");

        let jpeg = config.encode(&rgb, width, height, *quality as f32);
        let actual_hash = sha256_hex(&jpeg);

        assert_eq!(
            actual_hash,
            *expected_hash,
            "{} Q{}: hash mismatch!\n  expected: {}\n  actual:   {}\n  size: {} bytes",
            config_name,
            quality,
            expected_hash,
            actual_hash,
            jpeg.len()
        );
    }
}

/// Test encoding with various configurations.
/// This verifies strip encoder parity without depending on specific hashes.
///
/// NOTE: Currently skips configs where frymire.png (1118x1105) doesn't align to MCU boundaries.
/// The full-plane encoder has edge padding, but the strip encoder doesn't yet.
/// - 4:4:4: MCU=8, partial cols=6, partial rows=1 -> SKIP
/// - 4:2:0/4:2:2/4:4:0: MCU=16, partial cols=14, partial rows=1 -> SKIP
/// TODO: Remove this skip once strip encoder has edge padding.
#[test]
fn test_frymire_backend_parity() {
    let (rgb, width, height) = load_frymire();

    // Test all configs that support strip encoding (baseline and progressive, including XYB)
    let strip_configs = test_configs();

    for config in &strip_configs {
        // Skip configs where dimensions don't align to MCU (strip encoder lacks edge padding)
        let mcu_size = config.mcu_size();
        if width as usize % mcu_size != 0 || height as usize % mcu_size != 0 {
            // Strip encoder doesn't have edge padding yet - skip non-aligned configs
            continue;
        }

        for &quality in &[50u8, 90] {
            // Use Both backend - will error if outputs differ
            let _jpeg = config.encode(&rgb, width, height, quality as f32);
        }
    }
}

// =============================================================================
// UTILITY: Generate hashes
// =============================================================================

/// Print all hashes for updating EXPECTED_HASHES.
/// Run with: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
#[test]
#[ignore = "utility for generating hash values"]
fn print_all_hashes() {
    let (rgb, width, height) = load_frymire();
    println!("// frymire.png: {}x{}", width, height);
    println!("// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture");
    println!();
    println!("const EXPECTED_HASHES: &[(&str, u8, &str)] = &[");

    for config in test_configs() {
        for &quality in QUALITY_LEVELS {
            let jpeg = config.encode(&rgb, width, height, quality as f32);
            let hash = sha256_hex(&jpeg);
            println!(
                "    (\"{}\", {}, \"{}\"), // {} bytes",
                config.name,
                quality,
                hash,
                jpeg.len()
            );
        }
    }

    println!("];");
}

/// Print hash for a single configuration (for debugging).
#[test]
#[ignore = "utility"]
fn print_single_hash() {
    let (rgb, width, height) = load_frymire();

    let config = EncoderConfig::new()
        .quality(90.0)
        .ycbcr(ChromaSubsampling::Full)
        .optimize_huffman(true);
    let mut enc = config
        .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
        .expect("encoder setup");
    enc.push_packed(&rgb, Never).expect("push data");
    let jpeg = enc.finish().expect("Encoding failed");

    println!("Size: {} bytes", jpeg.len());
    println!("SHA256: {}", sha256_hex(&jpeg));
}
