//! Locked SHA256 hash tests for frymire.png encoding.
//!
//! These tests verify that encoder output is byte-for-byte reproducible.
//! Any refactoring that changes output will break these tests.
//!
//! Test image: tests/images/frymire.png (1118x1105 RGB)
//!
//! To regenerate hashes after intentional changes:
//!   cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
//!
//! ⚠️ LOCKED TEST: Do NOT modify hash values without understanding the impact.

use jpegli::types::{ChromaDownsampling, EncodingBackend, JpegMode, Subsampling};
use jpegli::{Encoder, PixelFormat, Quality};
use sha2::{Digest, Sha256};
use std::fs;

// =============================================================================
// CONFIGURATION
// =============================================================================

/// Quality levels to test (representative sample)
const QUALITY_LEVELS: &[u8] = &[50, 75, 90];

// =============================================================================
// EXPECTED HASHES (generated by print_all_hashes)
// Format: (config_name, quality, sha256_hex)
// =============================================================================

// frymire.png: 1118x1105
// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
// Updated 2026-01-11: FMA optimization changes rounding behavior
const EXPECTED_HASHES: &[(&str, u8, &str)] = &[
    ("baseline_444_opt", 50, "219221a754350fead09b9316ba43d0700cd66bca03e7415389378f6a4e413f50"), // 329838 bytes
    ("baseline_444_opt", 75, "d9c7e1219a025bcf4ab193a7737f99b28ec0c3738926c009da40c76dfe6a71fe"), // 476772 bytes
    ("baseline_444_opt", 90, "2a4d16a893513486f3e86dd5af016664af9c33148c00ab6a33bd31d06eb05ea6"), // 717812 bytes
    ("baseline_444_fixed", 50, "305dcf22142199c84c0c5eaeb9ad3bb18f5e035e0ba587ce66a931e8e4bd9e91"), // 344304 bytes
    ("baseline_444_fixed", 75, "fb00338fd64fd3f6b2709472882dc4169094fb6f1137380f60e1268edf2880ba"), // 496149 bytes
    ("baseline_444_fixed", 90, "c1758b66e897183e540e1bb77d6de883b4601878c27eb81ac74645e8bdfeb5c6"), // 766785 bytes
    ("baseline_420_opt", 50, "75cd91150061cf5121c2405ea84691f2707359183e7c5a185311bad9c6e7413d"), // 269382 bytes
    ("baseline_420_opt", 75, "d5bc235139aef257357d8207391f273610050840b5ee4048c2f75e034822fddd"), // 396823 bytes
    ("baseline_420_opt", 90, "90f645b2c26d0c9c0fbe62249e235b6fd31a9533ccae8f5168616d39f3e5b9ae"), // 583695 bytes
    ("baseline_420_gamma", 50, "d344b3a51aa81f8accd3c1254527144e14d7f58acf7dee7ce36e6f111746441a"), // 270384 bytes
    ("baseline_420_gamma", 75, "f0bd55f28b7f7f2161d89f8045a41214d2231108565ddd5f671b675c7d964b81"), // 398390 bytes
    ("baseline_420_gamma", 90, "db6d5fdac805ce70efb1c0cea578862c25b697ab6dd59aa7be044660818c91fd"), // 586339 bytes
    ("baseline_420_sharpyuv", 50, "0af902879f0d6ecade39e88ac5958ce5680d6addcea948d13cd212378e9c24f0"), // 269878 bytes
    ("baseline_420_sharpyuv", 75, "56cf91f5a2c2750e469f33f72fc49cf7aab6d68fb5038674186575be0a8b37f0"), // 397702 bytes
    ("baseline_420_sharpyuv", 90, "3e2f656b1aa6b566aae4ce8e0bdcbc7aca6df34336d9d52ace61159fbfb4d5de"), // 585243 bytes
    ("baseline_422_opt", 50, "0d1b325e5c3f2d18453a9eed2cfa144dca0bfb62409f4775d392e28c7fc0e274"), // 293361 bytes
    ("baseline_422_opt", 75, "8a318cf5d7f7f1c1ac5505dcb54ae4246c9176aa3012b1a24d16401522c711b2"), // 419126 bytes
    ("baseline_422_opt", 90, "38b35697d09ba05108dffbfffa8dce616dc933972808dc11c364337415939873"), // 613614 bytes
    ("baseline_440_opt", 50, "c7b6b6abbbf6790c26e36998f6279725e22f4b5d1c7be99a9a23423d3830a593"), // 293066 bytes
    ("baseline_440_opt", 75, "f18219f68a0d6aa398e57bb007e09a5d1ff2e12eb17576dded76f653cbeda910"), // 418915 bytes
    ("baseline_440_opt", 90, "750a48c77752d3c76e3520ac00168a376297c80314789e5f51978347582e37e0"), // 613628 bytes
    ("progressive_444_opt", 50, "f5ef6697f43fcdc06b81b1a7809d70af90cfa6b37fc3ca3f2de45aa2bb1de3f2"), // 320645 bytes
    ("progressive_444_opt", 75, "3336b2acc9b7bf6cae5fa65002d27bc60fdd479fd4dd8d10e1f61a0806af8602"), // 462529 bytes
    ("progressive_444_opt", 90, "449120f11d690a67fd3aa7bc4f3fcb2bc7a69db5704672fe1babde07ae396fd4"), // 696599 bytes
    ("progressive_420_opt", 50, "e0620bba711c3d34f9a3d6aa3ac04ec5e02c2f78c66eea118fba3d67fff52eb4"), // 260688 bytes
    ("progressive_420_opt", 75, "27fd1e33226e4f758989515157717069e8e58bf617689ce6cc993a7f98fac097"), // 383367 bytes
    ("progressive_420_opt", 90, "5c81c53d23ab38da27ad848235ba5a9a0ca836bb2588a7169e9618c2610653dd"), // 563852 bytes
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn load_frymire() -> (Vec<u8>, u32, u32) {
    let png_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/images/frymire.png");
    let png_data = fs::read(&png_path).expect("Failed to read frymire.png");
    let decoder = png::Decoder::new(&png_data[..]);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();

    let rgb: Vec<u8> = match info.color_type {
        png::ColorType::Rgb => buf[..info.buffer_size()].to_vec(),
        png::ColorType::Rgba => buf[..info.buffer_size()]
            .chunks(4)
            .flat_map(|c| [c[0], c[1], c[2]])
            .collect(),
        _ => panic!("Unsupported color type"),
    };

    (rgb, info.width, info.height)
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

/// Encoding configuration for testing
#[derive(Clone, Debug)]
struct EncoderTestConfig {
    name: &'static str,
    mode: JpegMode,
    subsampling: Subsampling,
    optimize_huffman: bool,
    chroma_downsampling: ChromaDownsampling,
    use_xyb: bool,
}

impl EncoderTestConfig {
    fn encode(&self, rgb: &[u8], width: u32, height: u32, quality: f32) -> Vec<u8> {
        Encoder::new()
            .width(width)
            .height(height)
            .pixel_format(PixelFormat::Rgb)
            .jpegli_quality(Quality::from_quality(quality))
            .mode(self.mode)
            .subsampling(self.subsampling)
            .optimize_huffman(self.optimize_huffman)
            .chroma_downsampling(self.chroma_downsampling)
            .use_xyb(self.use_xyb)
            .encoding_backend(EncodingBackend::FullPlane) // Lock to one backend for hash stability
            .encode(rgb)
            .expect("Encoding failed")
    }
}

/// All configurations to test
fn test_configs() -> Vec<EncoderTestConfig> {
    vec![
        // Baseline modes (YCbCr)
        EncoderTestConfig {
            name: "baseline_444_opt",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S444,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_444_fixed",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S444,
            optimize_huffman: false,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_opt",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S420,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_gamma",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S420,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::GammaAware,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_sharpyuv",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S420,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::GammaAwareIterative,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_422_opt",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S422,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_440_opt",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S440,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        // Progressive modes (YCbCr)
        EncoderTestConfig {
            name: "progressive_444_opt",
            mode: JpegMode::Progressive,
            subsampling: Subsampling::S444,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "progressive_420_opt",
            mode: JpegMode::Progressive,
            subsampling: Subsampling::S420,
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: false,
        },
        // XYB modes (subsampling is ignored for XYB)
        EncoderTestConfig {
            name: "baseline_xyb_opt",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S420, // Ignored for XYB
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "baseline_xyb_fixed",
            mode: JpegMode::Baseline,
            subsampling: Subsampling::S420, // Ignored for XYB
            optimize_huffman: false,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "progressive_xyb_opt",
            mode: JpegMode::Progressive,
            subsampling: Subsampling::S420, // Ignored for XYB
            optimize_huffman: true,
            chroma_downsampling: ChromaDownsampling::Box,
            use_xyb: true,
        },
    ]
}

// =============================================================================
// TESTS
// =============================================================================

/// Verify all configurations produce expected hashes.
/// This test is skipped until hashes are populated.
#[test]
fn test_frymire_hashes_locked() {
    if EXPECTED_HASHES.is_empty() {
        println!("No hashes configured yet. Run print_all_hashes to generate.");
        return;
    }

    let (rgb, width, height) = load_frymire();

    for (config_name, quality, expected_hash) in EXPECTED_HASHES {
        let config = test_configs()
            .into_iter()
            .find(|c| c.name == *config_name)
            .expect("Unknown config");

        let jpeg = config.encode(&rgb, width, height, *quality as f32);
        let actual_hash = sha256_hex(&jpeg);

        assert_eq!(
            actual_hash,
            *expected_hash,
            "{} Q{}: hash mismatch!\n  expected: {}\n  actual:   {}\n  size: {} bytes",
            config_name,
            quality,
            expected_hash,
            actual_hash,
            jpeg.len()
        );
    }
}

/// Test that both backends produce identical output (enforced by EncodingBackend::Both).
/// This verifies strip encoder parity without depending on specific hashes.
///
/// NOTE: Currently skips configs where frymire.png (1118x1105) doesn't align to MCU boundaries.
/// The full-plane encoder has edge padding, but the strip encoder doesn't yet.
/// - 4:4:4: MCU=8, partial cols=6, partial rows=1 -> SKIP
/// - 4:2:0/4:2:2/4:4:0: MCU=16, partial cols=14, partial rows=1 -> SKIP
/// TODO: Remove this skip once strip encoder has edge padding.
#[test]
fn test_frymire_backend_parity() {
    let (rgb, width, height) = load_frymire();

    // Test all configs that support strip encoding (baseline and progressive, including XYB)
    let strip_configs = test_configs()
        .into_iter()
        .filter(|c| c.mode == JpegMode::Baseline || c.mode == JpegMode::Progressive)
        .collect::<Vec<_>>();

    for config in &strip_configs {
        // Skip configs where dimensions don't align to MCU (strip encoder lacks edge padding)
        let mcu_size = config.subsampling.mcu_size();
        if width as usize % mcu_size != 0 || height as usize % mcu_size != 0 {
            // Strip encoder doesn't have edge padding yet - skip non-aligned configs
            continue;
        }

        for &quality in &[50u8, 90] {
            // Use Both backend - will error if outputs differ
            let _jpeg = Encoder::new()
                .width(width)
                .height(height)
                .pixel_format(PixelFormat::Rgb)
                .jpegli_quality(Quality::from_quality(quality as f32))
                .mode(config.mode)
                .subsampling(config.subsampling)
                .optimize_huffman(config.optimize_huffman)
                .chroma_downsampling(config.chroma_downsampling)
                .use_xyb(config.use_xyb)
                .encoding_backend(EncodingBackend::Both)
                .encode(&rgb)
                .unwrap_or_else(|e| {
                    panic!("{} Q{}: backend mismatch: {}", config.name, quality, e)
                });
        }
    }
}

// =============================================================================
// UTILITY: Generate hashes
// =============================================================================

/// Print all hashes for updating EXPECTED_HASHES.
/// Run with: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
#[test]
#[ignore = "utility for generating hash values"]
fn print_all_hashes() {
    let (rgb, width, height) = load_frymire();
    println!("// frymire.png: {}x{}", width, height);
    println!("// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture");
    println!();
    println!("const EXPECTED_HASHES: &[(&str, u8, &str)] = &[");

    for config in test_configs() {
        for &quality in QUALITY_LEVELS {
            let jpeg = config.encode(&rgb, width, height, quality as f32);
            let hash = sha256_hex(&jpeg);
            println!(
                "    (\"{}\", {}, \"{}\"), // {} bytes",
                config.name,
                quality,
                hash,
                jpeg.len()
            );
        }
    }

    println!("];");
}

/// Print hash for a single configuration (for debugging).
#[test]
#[ignore = "utility"]
fn print_single_hash() {
    let (rgb, width, height) = load_frymire();

    let jpeg = Encoder::new()
        .width(width)
        .height(height)
        .pixel_format(PixelFormat::Rgb)
        .jpegli_quality(Quality::from_quality(90.0))
        .mode(JpegMode::Baseline)
        .subsampling(Subsampling::S444)
        .optimize_huffman(true)
        .encoding_backend(EncodingBackend::FullPlane)
        .encode(&rgb)
        .expect("Encoding failed");

    println!("Size: {} bytes", jpeg.len());
    println!("SHA256: {}", sha256_hex(&jpeg));
}
