//! XMP serialization for Ultra HDR and related multi-image JPEG formats.
//!
//! This module handles the Adobe/Google XMP metadata used by Ultra HDR:
//!
//! - `hdrgm:*` namespace — gain-map numerical parameters (min, max,
//!   gamma, offsets, HDR headroom). Generated by [`generate_xmp`] and
//!   friends; parsed by [`parse_xmp`].
//! - `Container:Directory` — GContainer item manifest used by Google
//!   Camera and Android Dynamic Depth Format. Emitted by
//!   [`generate_xmp_with_items`]; parsed alongside metadata by
//!   [`parse_xmp_full`]. See [`super::types`] for `ContainerItem` and
//!   `ItemSemantic`.
//!
//! The physical APP1 envelope with the `http://ns.adobe.com/xap/1.0/\0`
//! namespace prefix is produced by [`create_xmp_app1_marker`].

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use thiserror::Error;

use super::types::{
    ContainerItem, ItemSemantic, generate_container_directory, parse_container_items,
};

/// XMP namespace for HDR gain-map metadata.
pub const HDRGM_NAMESPACE: &str = "http://ns.adobe.com/hdr-gain-map/1.0/";

/// XMP namespace for GContainer directory.
pub const CONTAINER_NAMESPACE: &str = "http://ns.google.com/photos/1.0/container/";

/// XMP namespace for GContainer item.
pub const ITEM_NAMESPACE: &str = "http://ns.google.com/photos/1.0/container/item/";

/// Upper bound on XMP packet length accepted by [`parse_xmp`]. Guards
/// against CPU exhaustion on crafted inputs.
///
/// Matches `ultrahdr_core::limits::MAX_XMP_LENGTH` (the pre-migration
/// value) so callers moving between the old and new API see no change
/// in accepted input size. Legitimate gain-map XMP is well under
/// 32 KB, but Extended XMP reassembly + base64-encoded depth-map
/// payloads (GDepth / Android Dynamic Depth) can push into MB range,
/// so a generous cap is appropriate.
pub const MAX_XMP_LENGTH: usize = 16 * 1024 * 1024;

/// Errors from [`parse_xmp`].
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum XmpError {
    /// XMP exceeded [`MAX_XMP_LENGTH`].
    #[error("XMP length {got} exceeds maximum {max}")]
    LengthLimit {
        /// Bytes actually passed in.
        got: usize,
        /// Enforced cap.
        max: usize,
    },
    /// XMP does not carry the `hdrgm` namespace — not Ultra HDR.
    #[error("XMP is not an Ultra HDR packet (no hdrgm:Version and no hdrgm:GainMapMax)")]
    NotUltraHdr,
}

/// Generate XMP for a 2-item Primary + GainMap Ultra HDR image.
///
/// This single packet goes in the primary JPEG's APP1 marker. It carries
/// both the numeric metadata (all `hdrgm:*` attrs) AND the
/// `Container:Directory` listing.
///
/// For maximum compatibility with libultrahdr's canonical layout (where
/// the primary XMP carries only the directory and the gain-map XMP
/// carries the numbers), use [`generate_primary_xmp`] +
/// [`generate_gainmap_xmp`] instead.
#[must_use]
pub fn generate_xmp(metadata: &zencodec::GainMapParams, gainmap_length: usize) -> String {
    let items = alloc::vec![
        ContainerItem::primary("image/jpeg"),
        ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", gainmap_length),
    ];
    generate_xmp_with_items(metadata, &items)
}

/// Generate XMP for the primary JPEG: `Container:Directory` only.
///
/// The primary image's XMP contains `hdrgm:Version` and the
/// `Container:Directory` listing every secondary with its semantic and
/// byte length. The numeric gain-map metadata goes in the secondary's
/// XMP via [`generate_gainmap_xmp`]. This matches the layout produced
/// by Google Camera / Android.
#[must_use]
pub fn generate_primary_xmp(gainmap_length: usize) -> String {
    let items = alloc::vec![
        ContainerItem::primary("image/jpeg"),
        ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", gainmap_length),
    ];
    generate_primary_xmp_with_items(&items)
}

/// Generate XMP for the primary JPEG with a custom item list (e.g. for
/// depth-map containers alongside the gain map).
#[must_use]
pub fn generate_primary_xmp_with_items(items: &[ContainerItem]) -> String {
    let container_dir = generate_container_directory(items);
    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        xmlns:Container="{CONTAINER_NAMESPACE}"
        xmlns:Item="{ITEM_NAMESPACE}"
        hdrgm:Version="1.0">
{container_dir}
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

/// Generate XMP for the gain-map (secondary) JPEG: numeric metadata
/// only (no Container:Directory).
///
/// Goes in the gain-map JPEG's APP1 marker. Together with the primary's
/// `Container:Directory` XMP, this matches libultrahdr's canonical
/// output.
#[must_use]
pub fn generate_gainmap_xmp(metadata: &zencodec::GainMapParams) -> String {
    let ch = &metadata.channels;
    let single = metadata.is_single_channel();

    let gain_map_min = format_triple(&[ch[0].min, ch[1].min, ch[2].min], single);
    let gain_map_max = format_triple(&[ch[0].max, ch[1].max, ch[2].max], single);
    let gamma = format_triple(&[ch[0].gamma, ch[1].gamma, ch[2].gamma], single);
    let offset_sdr = format_triple(
        &[ch[0].base_offset, ch[1].base_offset, ch[2].base_offset],
        single,
    );
    let offset_hdr = format_triple(
        &[
            ch[0].alternate_offset,
            ch[1].alternate_offset,
            ch[2].alternate_offset,
        ],
        single,
    );
    let hdr_capacity_min = metadata.base_hdr_headroom;
    let hdr_capacity_max = metadata.alternate_hdr_headroom;

    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        hdrgm:Version="1.0"
        hdrgm:GainMapMin="{gain_map_min}"
        hdrgm:GainMapMax="{gain_map_max}"
        hdrgm:Gamma="{gamma}"
        hdrgm:OffsetSDR="{offset_sdr}"
        hdrgm:OffsetHDR="{offset_hdr}"
        hdrgm:HDRCapacityMin="{hdr_capacity_min:.6}"
        hdrgm:HDRCapacityMax="{hdr_capacity_max:.6}"
        hdrgm:BaseRenditionIsHDR="False"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

/// Generate XMP with both numeric metadata and a custom container
/// directory. Used when carrying depth / confidence maps alongside the
/// gain map.
#[must_use]
pub fn generate_xmp_with_items(
    metadata: &zencodec::GainMapParams,
    items: &[ContainerItem],
) -> String {
    let ch = &metadata.channels;
    let single = metadata.is_single_channel();
    let gain_map_min = format_triple(&[ch[0].min, ch[1].min, ch[2].min], single);
    let gain_map_max = format_triple(&[ch[0].max, ch[1].max, ch[2].max], single);
    let gamma = format_triple(&[ch[0].gamma, ch[1].gamma, ch[2].gamma], single);
    let offset_sdr = format_triple(
        &[ch[0].base_offset, ch[1].base_offset, ch[2].base_offset],
        single,
    );
    let offset_hdr = format_triple(
        &[
            ch[0].alternate_offset,
            ch[1].alternate_offset,
            ch[2].alternate_offset,
        ],
        single,
    );
    let hdr_capacity_min = metadata.base_hdr_headroom;
    let hdr_capacity_max = metadata.alternate_hdr_headroom;
    let container_dir = generate_container_directory(items);
    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        xmlns:Container="{CONTAINER_NAMESPACE}"
        xmlns:Item="{ITEM_NAMESPACE}"
        hdrgm:Version="1.0"
        hdrgm:GainMapMin="{gain_map_min}"
        hdrgm:GainMapMax="{gain_map_max}"
        hdrgm:Gamma="{gamma}"
        hdrgm:OffsetSDR="{offset_sdr}"
        hdrgm:OffsetHDR="{offset_hdr}"
        hdrgm:HDRCapacityMin="{hdr_capacity_min:.6}"
        hdrgm:HDRCapacityMax="{hdr_capacity_max:.6}"
        hdrgm:BaseRenditionIsHDR="False">
{container_dir}
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

fn format_triple(values: &[f64; 3], single_channel: bool) -> String {
    if single_channel {
        format!("{:.6}", values[0])
    } else {
        format!("{:.6}, {:.6}, {:.6}", values[0], values[1], values[2])
    }
}

/// Parse Ultra HDR XMP numeric metadata + optional `Item:Length` for
/// the gain map.
///
/// Returns `(metadata, gainmap_length)`. For access to the full
/// `Container:Directory` (depth maps, confidence maps, vendor items),
/// use [`parse_xmp_full`] instead.
pub fn parse_xmp(xmp: &str) -> Result<(zencodec::GainMapParams, Option<usize>), XmpError> {
    if xmp.len() > MAX_XMP_LENGTH {
        return Err(XmpError::LengthLimit {
            got: xmp.len(),
            max: MAX_XMP_LENGTH,
        });
    }
    if !xmp.contains("hdrgm:Version") && !xmp.contains("hdrgm:GainMapMax") {
        return Err(XmpError::NotUltraHdr);
    }

    let mut metadata = zencodec::GainMapParams::default();
    let mut gainmap_length = None;

    if let Some(val) = extract_attribute(xmp, "hdrgm:GainMapMin") {
        let vals = parse_triple_f64(&val);
        for (i, v) in vals.iter().enumerate() {
            metadata.channels[i].min = *v;
        }
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:GainMapMax") {
        let vals = parse_triple_f64(&val);
        for (i, v) in vals.iter().enumerate() {
            metadata.channels[i].max = *v;
        }
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:Gamma") {
        let vals = parse_triple_f64(&val);
        for (i, v) in vals.iter().enumerate() {
            metadata.channels[i].gamma = *v;
        }
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:OffsetSDR") {
        let vals = parse_triple_f64(&val);
        for (i, v) in vals.iter().enumerate() {
            metadata.channels[i].base_offset = *v;
        }
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:OffsetHDR") {
        let vals = parse_triple_f64(&val);
        for (i, v) in vals.iter().enumerate() {
            metadata.channels[i].alternate_offset = *v;
        }
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:HDRCapacityMin")
        && let Ok(v) = val.parse::<f64>()
    {
        metadata.base_hdr_headroom = v;
    }
    if let Some(val) = extract_attribute(xmp, "hdrgm:HDRCapacityMax")
        && let Ok(v) = val.parse::<f64>()
    {
        metadata.alternate_hdr_headroom = v;
    }
    if let Some(val) = extract_attribute(xmp, "Item:Length")
        && let Ok(len) = val.parse::<usize>()
    {
        gainmap_length = Some(len);
    }
    Ok((metadata, gainmap_length))
}

/// Parse both numeric metadata (if present) and all
/// `Container:Directory` items. Never errors — returns empty results
/// when the input is not an Ultra HDR packet.
#[must_use]
pub fn parse_xmp_full(xmp: &str) -> (Option<zencodec::GainMapParams>, Vec<ContainerItem>) {
    let metadata = if xmp.contains("hdrgm:Version") || xmp.contains("hdrgm:GainMapMax") {
        parse_xmp(xmp).ok().map(|(m, _)| m)
    } else {
        None
    };
    let items = parse_container_items(xmp);
    (metadata, items)
}

fn extract_attribute(xmp: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr}=\"");
    if let Some(start) = xmp.find(&pattern) {
        let value_start = start + pattern.len();
        if let Some(end) = xmp[value_start..].find('"') {
            return Some(xmp[value_start..value_start + end].to_string());
        }
    }
    let open_tag = format!("<{attr}>");
    let close_tag = format!("</{attr}>");
    if let Some(start) = xmp.find(&open_tag) {
        let value_start = start + open_tag.len();
        if let Some(end) = xmp[value_start..].find(&close_tag) {
            return Some(xmp[value_start..value_start + end].trim().to_string());
        }
    }
    None
}

/// Parse a comma-separated triple into exactly 3 f64 values. A single
/// scalar is replicated to all three channels.
fn parse_triple_f64(value: &str) -> [f64; 3] {
    let parsed: Vec<f64> = value
        .split(',')
        .filter_map(|s| s.trim().parse::<f64>().ok())
        .collect();
    match parsed.len() {
        0 => [0.0; 3],
        1 => [parsed[0]; 3],
        2 => [parsed[0], parsed[1], 0.0],
        _ => [parsed[0], parsed[1], parsed[2]],
    }
}

/// Wrap an XMP packet in a JPEG APP1 marker with the standard
/// `http://ns.adobe.com/xap/1.0/\0` namespace prefix.
///
/// Returns bytes ready to splice into a JPEG codestream after SOI.
#[must_use]
pub fn create_xmp_app1_marker(xmp: &str) -> Vec<u8> {
    let xmp_bytes = xmp.as_bytes();
    let namespace = b"http://ns.adobe.com/xap/1.0/\0";
    let total_length = 2 + namespace.len() + xmp_bytes.len();
    let mut marker = Vec::with_capacity(2 + total_length);
    marker.push(0xFF);
    marker.push(0xE1);
    marker.push(((total_length >> 8) & 0xFF) as u8);
    marker.push((total_length & 0xFF) as u8);
    marker.extend_from_slice(namespace);
    marker.extend_from_slice(xmp_bytes);
    marker
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn test_metadata() -> zencodec::GainMapParams {
        let mut m = zencodec::GainMapParams::default();
        for i in 0..3 {
            m.channels[i].min = 0.0;
            m.channels[i].max = 2.0;
            m.channels[i].gamma = 1.0;
            m.channels[i].base_offset = 1.0 / 64.0;
            m.channels[i].alternate_offset = 1.0 / 64.0;
        }
        m.base_hdr_headroom = 0.0;
        m.alternate_hdr_headroom = 2.0;
        m
    }

    fn multi_channel_metadata() -> zencodec::GainMapParams {
        let mut m = test_metadata();
        m.channels[0].min = 1.0;
        m.channels[1].min = 2.0;
        m.channels[2].min = 3.0;
        m.channels[0].max = 4.0;
        m.channels[1].max = 5.0;
        m.channels[2].max = 6.0;
        m
    }

    #[test]
    fn generate_xmp_contains_version_and_length() {
        let xmp = generate_xmp(&test_metadata(), 10_000);
        assert!(xmp.contains("hdrgm:Version=\"1.0\""));
        assert!(xmp.contains("hdrgm:GainMapMax"));
        assert!(xmp.contains("Item:Length=\"10000\""));
        assert!(xmp.contains("Item:Semantic=\"GainMap\""));
    }

    /// XMP serializes f64 via `{:.6}` format, so roundtrip error is
    /// bounded by that — one ULP at the 6th decimal ≈ 5e-7. Anything
    /// looser hides real precision bugs.
    const XMP_FLOAT_TOL: f64 = 1e-5;

    #[test]
    fn parse_xmp_roundtrips_scalar_values() {
        let original = test_metadata();
        let xmp = generate_xmp(&original, 5_000);
        let (parsed, length) = parse_xmp(&xmp).unwrap();
        assert_eq!(length, Some(5_000));
        // Verify every numeric field roundtrips, not just .max.
        for i in 0..3 {
            assert!((parsed.channels[i].min - original.channels[i].min).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].max - original.channels[i].max).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].gamma - original.channels[i].gamma).abs() < XMP_FLOAT_TOL);
            assert!(
                (parsed.channels[i].base_offset - original.channels[i].base_offset).abs()
                    < XMP_FLOAT_TOL
            );
            assert!(
                (parsed.channels[i].alternate_offset - original.channels[i].alternate_offset).abs()
                    < XMP_FLOAT_TOL
            );
        }
        assert!(
            (parsed.base_hdr_headroom - original.base_hdr_headroom).abs() < XMP_FLOAT_TOL
        );
        assert!(
            (parsed.alternate_hdr_headroom - original.alternate_hdr_headroom).abs()
                < XMP_FLOAT_TOL
        );
    }

    #[test]
    fn parse_xmp_roundtrips_multi_channel_values() {
        let original = multi_channel_metadata();
        let xmp = generate_xmp(&original, 5_000);
        let (parsed, _) = parse_xmp(&xmp).unwrap();
        // All three channels must differ — a regression that replicated
        // channel-0 to 1/2 would have channels[0].min == channels[1].min.
        for i in 0..3 {
            assert!((parsed.channels[i].min - original.channels[i].min).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].max - original.channels[i].max).abs() < XMP_FLOAT_TOL);
        }
        assert!(
            (parsed.channels[0].min - parsed.channels[1].min).abs() > 0.5,
            "channels must remain distinct across the roundtrip"
        );
    }

    #[test]
    fn parse_xmp_rejects_non_ultrahdr_packet() {
        let xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        dc:creator="SomeCamera"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#;
        assert!(matches!(parse_xmp(xmp), Err(XmpError::NotUltraHdr)));
    }

    /// Pins the accepted-input ceiling. If someone shrinks
    /// `MAX_XMP_LENGTH` (as was mistakenly done during the initial
    /// container-module extraction — 16 MiB became 1 MiB), this test
    /// fails by value-equality, not just behavior.
    #[test]
    fn max_xmp_length_is_16_mib() {
        assert_eq!(MAX_XMP_LENGTH, 16 * 1024 * 1024);
    }

    #[test]
    fn parse_xmp_rejects_oversized_input() {
        let mut big = String::with_capacity(MAX_XMP_LENGTH + 100);
        big.push_str("hdrgm:Version=\"1.0\" ");
        while big.len() <= MAX_XMP_LENGTH {
            big.push_str("                                   ");
        }
        assert!(matches!(parse_xmp(&big), Err(XmpError::LengthLimit { .. })));
    }

    /// 1 MiB of valid XMP must be accepted — confirms the 16 MiB cap
    /// isn't silently re-tightened.
    #[test]
    fn parse_xmp_accepts_1_mib_input() {
        let mut big = String::with_capacity(1024 * 1024 + 100);
        big.push_str("hdrgm:Version=\"1.0\" hdrgm:GainMapMax=\"2.0\" ");
        while big.len() <= 1024 * 1024 {
            big.push_str("                                   ");
        }
        assert!(parse_xmp(&big).is_ok(), "1 MiB XMP must not trip the cap");
    }

    #[test]
    fn extract_attribute_finds_attribute_form() {
        let xmp = r#"<rdf:Description hdrgm:Version="1.0" hdrgm:GainMapMax="2.0"/>"#;
        assert_eq!(extract_attribute(xmp, "hdrgm:Version"), Some("1.0".into()));
        assert_eq!(extract_attribute(xmp, "hdrgm:GainMapMax"), Some("2.0".into()));
        assert_eq!(extract_attribute(xmp, "hdrgm:Missing"), None);
    }

    #[test]
    fn extract_attribute_finds_element_form() {
        let xmp = "<hdrgm:Gamma>1.5</hdrgm:Gamma>";
        assert_eq!(extract_attribute(xmp, "hdrgm:Gamma"), Some("1.5".into()));
    }

    #[test]
    fn parse_triple_f64_single_scalar_replicates() {
        assert_eq!(parse_triple_f64("1.5"), [1.5, 1.5, 1.5]);
    }

    #[test]
    fn parse_triple_f64_three_values() {
        assert_eq!(parse_triple_f64("1.0, 2.0, 3.0"), [1.0, 2.0, 3.0]);
    }

    #[test]
    fn parse_triple_f64_empty_is_zeros() {
        assert_eq!(parse_triple_f64(""), [0.0, 0.0, 0.0]);
        assert_eq!(parse_triple_f64("not-a-number"), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn parse_xmp_full_returns_items_even_without_numeric_metadata() {
        let items = alloc::vec![
            ContainerItem::primary("image/jpeg"),
            ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", 123),
        ];
        let xmp = generate_primary_xmp_with_items(&items);
        let (meta, parsed) = parse_xmp_full(&xmp);
        assert!(meta.is_some()); // primary_xmp has hdrgm:Version
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[1].length, Some(123));
    }

    #[test]
    fn generate_gainmap_xmp_has_only_numeric_attrs() {
        let xmp = generate_gainmap_xmp(&test_metadata());
        assert!(xmp.contains("hdrgm:Version=\"1.0\""));
        assert!(xmp.contains("hdrgm:GainMapMax"));
        // Gain-map XMP should NOT carry Container:Directory.
        assert!(!xmp.contains("Container:Directory"));
    }

    #[test]
    fn create_xmp_app1_marker_shape() {
        let xmp = "<x:xmpmeta/>";
        let marker = create_xmp_app1_marker(xmp);
        assert_eq!(marker[0], 0xFF);
        assert_eq!(marker[1], 0xE1);
        // Length word includes itself + namespace + xmp bytes.
        let declared = u16::from_be_bytes([marker[2], marker[3]]) as usize;
        assert_eq!(declared, marker.len() - 2);
        assert!(marker.ends_with(xmp.as_bytes()));
    }

    #[test]
    fn parse_xmp_no_panic_on_garbage() {
        let _ = parse_xmp("");
        let _ = parse_xmp("hdrgm:GainMapMax=\"not_a_number\"");
        let garbage: String = (0..4096).map(|i| (i % 128) as u8 as char).collect();
        let _ = parse_xmp(&garbage);
    }
}
