//! XMP serialization for Ultra HDR and related multi-image JPEG formats.
//!
//! This module handles the Adobe/Google XMP metadata used by Ultra HDR:
//!
//! - `hdrgm:*` namespace — gain-map numerical parameters (min, max,
//!   gamma, offsets, HDR headroom). Generated by [`generate_xmp`] and
//!   friends; parsed by [`parse_xmp`].
//! - `Container:Directory` — GContainer item manifest used by Google
//!   Camera and Android Dynamic Depth Format. Emitted by
//!   [`generate_xmp_with_items`]; parsed alongside metadata by
//!   [`parse_xmp_full`]. See [`super::types`] for `ContainerItem` and
//!   `ItemSemantic`.
//!
//! The physical APP1 envelope with the `http://ns.adobe.com/xap/1.0/\0`
//! namespace prefix is produced by [`create_xmp_app1_marker`].

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use thiserror::Error;

use super::types::{ContainerItem, ItemSemantic, generate_container_directory};

/// XMP namespace for HDR gain-map metadata.
pub const HDRGM_NAMESPACE: &str = "http://ns.adobe.com/hdr-gain-map/1.0/";

/// XMP namespace for GContainer directory.
pub const CONTAINER_NAMESPACE: &str = "http://ns.google.com/photos/1.0/container/";

/// XMP namespace for GContainer item.
pub const ITEM_NAMESPACE: &str = "http://ns.google.com/photos/1.0/container/item/";

/// Upper bound on XMP packet length accepted by [`parse_xmp`]. Guards
/// against CPU exhaustion on crafted inputs.
///
/// Matches `ultrahdr_core::limits::MAX_XMP_LENGTH` (the pre-migration
/// value) so callers moving between the old and new API see no change
/// in accepted input size. Legitimate gain-map XMP is well under
/// 32 KB, but Extended XMP reassembly + base64-encoded depth-map
/// payloads (GDepth / Android Dynamic Depth) can push into MB range,
/// so a generous cap is appropriate.
pub const MAX_XMP_LENGTH: usize = 16 * 1024 * 1024;

/// Errors from [`parse_xmp`].
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum XmpError {
    /// XMP exceeded [`MAX_XMP_LENGTH`].
    #[error("XMP length {got} exceeds maximum {max}")]
    LengthLimit {
        /// Bytes actually passed in.
        got: usize,
        /// Enforced cap.
        max: usize,
    },
    /// XMP does not carry the `hdrgm` namespace — not Ultra HDR.
    #[error("XMP is not an Ultra HDR packet (no hdrgm:Version and no hdrgm:GainMapMax)")]
    NotUltraHdr,
    /// Malformed, ambiguous or unsupported XML/RDF.
    #[error("invalid gain-map XMP: {0}")]
    Invalid(String),
}

/// Generate XMP for a 2-item Primary + GainMap Ultra HDR image.
///
/// This single packet goes in the primary JPEG's APP1 marker. It carries
/// both the numeric metadata (all `hdrgm:*` attrs) AND the
/// `Container:Directory` listing.
///
/// For maximum compatibility with libultrahdr's canonical layout (where
/// the primary XMP carries only the directory and the gain-map XMP
/// carries the numbers), use [`generate_primary_xmp`] +
/// [`generate_gainmap_xmp`] instead.
///
/// # Examples
///
/// Roundtrip a default set of gain-map parameters:
///
/// ```
/// use zenjpeg::container::xmp::{generate_xmp, parse_xmp};
///
/// let mut params = zencodec::GainMapParams::default();
/// for c in &mut params.channels {
///     c.max = 2.0;
///     c.gamma = 1.0;
/// }
/// let xmp = generate_xmp(&params, 5_000);
/// let (parsed, length) = parse_xmp(&xmp).expect("parse");
/// assert_eq!(length, Some(5_000));
/// assert!((parsed.channels[0].max - 2.0).abs() < 1e-5);
/// ```
#[must_use]
pub fn generate_xmp(metadata: &zencodec::GainMapParams, gainmap_length: usize) -> String {
    let items = alloc::vec![
        ContainerItem::primary("image/jpeg"),
        ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", gainmap_length),
    ];
    generate_xmp_with_items(metadata, &items)
}

/// Generate XMP for the primary JPEG: `Container:Directory` only.
///
/// The primary image's XMP contains `hdrgm:Version` and the
/// `Container:Directory` listing every secondary with its semantic and
/// byte length. The numeric gain-map metadata goes in the secondary's
/// XMP via [`generate_gainmap_xmp`]. This matches the layout produced
/// by Google Camera / Android.
#[must_use]
pub fn generate_primary_xmp(gainmap_length: usize) -> String {
    let items = alloc::vec![
        ContainerItem::primary("image/jpeg"),
        ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", gainmap_length),
    ];
    generate_primary_xmp_with_items(&items)
}

/// Generate XMP for the primary JPEG with a custom item list (e.g. for
/// depth-map containers alongside the gain map).
#[must_use]
pub fn generate_primary_xmp_with_items(items: &[ContainerItem]) -> String {
    let container_dir = generate_container_directory(items);
    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        xmlns:Container="{CONTAINER_NAMESPACE}"
        xmlns:Item="{ITEM_NAMESPACE}"
        hdrgm:Version="1.0">
{container_dir}
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

/// Generate XMP for the gain-map (secondary) JPEG: numeric metadata
/// only (no Container:Directory).
///
/// Goes in the gain-map JPEG's APP1 marker. Together with the primary's
/// `Container:Directory` XMP, this matches libultrahdr's canonical
/// output.
#[must_use]
pub fn generate_gainmap_xmp(metadata: &zencodec::GainMapParams) -> String {
    let ch = &metadata.channels;
    let single = metadata.is_single_channel();

    let gain_map_min = format_triple(&[ch[0].min, ch[1].min, ch[2].min], single);
    let gain_map_max = format_triple(&[ch[0].max, ch[1].max, ch[2].max], single);
    let gamma = format_triple(&[ch[0].gamma, ch[1].gamma, ch[2].gamma], single);
    let offset_sdr = format_triple(
        &[ch[0].base_offset, ch[1].base_offset, ch[2].base_offset],
        single,
    );
    let offset_hdr = format_triple(
        &[
            ch[0].alternate_offset,
            ch[1].alternate_offset,
            ch[2].alternate_offset,
        ],
        single,
    );
    let hdr_capacity_min = metadata.base_hdr_headroom;
    let hdr_capacity_max = metadata.alternate_hdr_headroom;

    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        hdrgm:Version="1.0"
        hdrgm:GainMapMin="{gain_map_min}"
        hdrgm:GainMapMax="{gain_map_max}"
        hdrgm:Gamma="{gamma}"
        hdrgm:OffsetSDR="{offset_sdr}"
        hdrgm:OffsetHDR="{offset_hdr}"
        hdrgm:HDRCapacityMin="{hdr_capacity_min:.6}"
        hdrgm:HDRCapacityMax="{hdr_capacity_max:.6}"
        hdrgm:BaseRenditionIsHDR="False"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

/// Generate XMP with both numeric metadata and a custom container
/// directory. Used when carrying depth / confidence maps alongside the
/// gain map.
#[must_use]
pub fn generate_xmp_with_items(
    metadata: &zencodec::GainMapParams,
    items: &[ContainerItem],
) -> String {
    let ch = &metadata.channels;
    let single = metadata.is_single_channel();
    let gain_map_min = format_triple(&[ch[0].min, ch[1].min, ch[2].min], single);
    let gain_map_max = format_triple(&[ch[0].max, ch[1].max, ch[2].max], single);
    let gamma = format_triple(&[ch[0].gamma, ch[1].gamma, ch[2].gamma], single);
    let offset_sdr = format_triple(
        &[ch[0].base_offset, ch[1].base_offset, ch[2].base_offset],
        single,
    );
    let offset_hdr = format_triple(
        &[
            ch[0].alternate_offset,
            ch[1].alternate_offset,
            ch[2].alternate_offset,
        ],
        single,
    );
    let hdr_capacity_min = metadata.base_hdr_headroom;
    let hdr_capacity_max = metadata.alternate_hdr_headroom;
    let container_dir = generate_container_directory(items);
    format!(
        r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:hdrgm="{HDRGM_NAMESPACE}"
        xmlns:Container="{CONTAINER_NAMESPACE}"
        xmlns:Item="{ITEM_NAMESPACE}"
        hdrgm:Version="1.0"
        hdrgm:GainMapMin="{gain_map_min}"
        hdrgm:GainMapMax="{gain_map_max}"
        hdrgm:Gamma="{gamma}"
        hdrgm:OffsetSDR="{offset_sdr}"
        hdrgm:OffsetHDR="{offset_hdr}"
        hdrgm:HDRCapacityMin="{hdr_capacity_min:.6}"
        hdrgm:HDRCapacityMax="{hdr_capacity_max:.6}"
        hdrgm:BaseRenditionIsHDR="False">
{container_dir}
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#
    )
}

fn format_triple(values: &[f64; 3], single_channel: bool) -> String {
    if single_channel {
        format!("{:.6}", values[0])
    } else {
        format!("{:.6}, {:.6}, {:.6}", values[0], values[1], values[2])
    }
}

/// Parse Ultra HDR XMP numeric metadata + optional `Item:Length` for
/// the gain map.
///
/// Returns `(metadata, gainmap_length)`. For access to the full
/// `Container:Directory` (depth maps, confidence maps, vendor items),
/// use [`parse_xmp_full`] instead.
pub fn parse_xmp(xmp: &str) -> Result<(zencodec::GainMapParams, Option<usize>), XmpError> {
    if xmp.len() > MAX_XMP_LENGTH {
        return Err(XmpError::LengthLimit {
            got: xmp.len(),
            max: MAX_XMP_LENGTH,
        });
    }
    let packet = zencodec::xmp::Packet::parse(xmp).map_err(|e| XmpError::Invalid(e.to_string()))?;
    let property = |name| {
        packet
            .property(HDRGM_NAMESPACE, name)
            .map_err(|e| XmpError::Invalid(e.to_string()))
    };
    let version = property("Version")?;
    if version.is_none() && property("GainMapMax")?.is_none() {
        return Err(XmpError::NotUltraHdr);
    }
    if version.is_some_and(|v| v != ["1.0"]) {
        return Err(XmpError::Invalid("unsupported hdrgm version".into()));
    }
    if property("BaseRenditionIsHDR")?.is_some_and(|v| v != ["False"]) {
        return Err(XmpError::Invalid(
            "HDR-base XMP requires a supported inverse reconstruction path".into(),
        ));
    }
    let mut metadata = zencodec::GainMapParams::default();
    for (name, field) in [
        ("GainMapMin", 0),
        ("GainMapMax", 1),
        ("Gamma", 2),
        ("OffsetSDR", 3),
        ("OffsetHDR", 4),
    ] {
        if let Some(values) = property(name)? {
            let values = numeric_values(values, name)?;
            let triple = match values.as_slice() {
                [v] => [*v; 3],
                [r, g, b] => [*r, *g, *b],
                _ => {
                    return Err(XmpError::Invalid(format!(
                        "{name}: expected one or three values"
                    )));
                }
            };
            for (ch, value) in metadata.channels.iter_mut().zip(triple) {
                match field {
                    0 => ch.min = value,
                    1 => ch.max = value,
                    2 => ch.gamma = value,
                    3 => ch.base_offset = value,
                    _ => ch.alternate_offset = value,
                }
            }
        }
    }
    for (name, slot) in [
        ("HDRCapacityMin", &mut metadata.base_hdr_headroom),
        ("HDRCapacityMax", &mut metadata.alternate_hdr_headroom),
    ] {
        if let Some(values) = property(name)? {
            let values = numeric_values(values, name)?;
            if values.len() != 1 {
                return Err(XmpError::Invalid(format!("{name}: expected scalar")));
            }
            *slot = values[0];
        }
    }
    metadata
        .validate()
        .map_err(|e| XmpError::Invalid(e.to_string()))?;
    let items = checked_container_items(&packet)?;
    let mut gainmaps = items.iter().filter(|i| i.semantic == ItemSemantic::GainMap);
    let length = gainmaps.next().and_then(|i| i.length);
    if gainmaps.next().is_some() {
        return Err(XmpError::Invalid("multiple gain-map items".into()));
    }
    Ok((metadata, length))
}
fn numeric_values(values: Vec<String>, name: &str) -> Result<Vec<f64>, XmpError> {
    values
        .iter()
        .flat_map(|v| v.split(','))
        .map(|v| {
            v.trim()
                .parse::<f64>()
                .ok()
                .filter(|v| v.is_finite())
                .ok_or_else(|| XmpError::Invalid(format!("{name}: invalid number")))
        })
        .collect()
}

/// Parse numeric parameters and container items. Invalid packets yield no
/// metadata; use [`parse_xmp`] when a diagnostic error is required.
#[must_use]
pub fn parse_xmp_full(xmp: &str) -> (Option<zencodec::GainMapParams>, Vec<ContainerItem>) {
    let Ok(packet) = zencodec::xmp::Packet::parse(xmp) else {
        return (None, Vec::new());
    };
    (
        parse_xmp(xmp).ok().map(|(m, _)| m),
        checked_container_items(&packet).unwrap_or_default(),
    )
}

pub(super) fn checked_container_items(
    packet: &zencodec::xmp::Packet<'_>,
) -> Result<Vec<ContainerItem>, XmpError> {
    packet
        .resource_sequence(
            CONTAINER_NAMESPACE,
            "Directory",
            CONTAINER_NAMESPACE,
            "Item",
        )
        .map_err(|e| XmpError::Invalid(e.to_string()))?
        .into_iter()
        .map(|fields| {
            let value = |name: &str| {
                fields
                    .iter()
                    .find(|f| f.namespace() == ITEM_NAMESPACE && f.name() == name)
                    .map(|f| f.value())
            };
            let semantic = value("Semantic")
                .ok_or_else(|| XmpError::Invalid("missing item semantic".into()))?;
            let mime =
                value("Mime").ok_or_else(|| XmpError::Invalid("missing item MIME".into()))?;
            let number = |name| {
                value(name)
                    .map(|s| {
                        s.parse::<usize>()
                            .map_err(|_| XmpError::Invalid(format!("invalid item {name}")))
                    })
                    .transpose()
            };
            Ok(ContainerItem {
                semantic: ItemSemantic::from_xmp(semantic),
                mime: mime.into(),
                length: number("Length")?,
                padding: number("Padding")?,
            })
        })
        .collect()
}

/// Wrap an XMP packet in a JPEG APP1 marker with the standard
/// `http://ns.adobe.com/xap/1.0/\0` namespace prefix.
///
/// Returns bytes ready to splice into a JPEG codestream after SOI.
#[must_use]
pub fn create_xmp_app1_marker(xmp: &str) -> Vec<u8> {
    super::marker::create_app_segment(1, b"http://ns.adobe.com/xap/1.0/\0", xmp.as_bytes())
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn test_metadata() -> zencodec::GainMapParams {
        let mut m = zencodec::GainMapParams::default();
        for i in 0..3 {
            m.channels[i].min = 0.0;
            m.channels[i].max = 2.0;
            m.channels[i].gamma = 1.0;
            m.channels[i].base_offset = 1.0 / 64.0;
            m.channels[i].alternate_offset = 1.0 / 64.0;
        }
        m.base_hdr_headroom = 0.0;
        m.alternate_hdr_headroom = 2.0;
        m
    }

    fn multi_channel_metadata() -> zencodec::GainMapParams {
        let mut m = test_metadata();
        m.channels[0].min = 1.0;
        m.channels[1].min = 2.0;
        m.channels[2].min = 3.0;
        m.channels[0].max = 4.0;
        m.channels[1].max = 5.0;
        m.channels[2].max = 6.0;
        m
    }

    #[test]
    fn generate_xmp_contains_version_and_length() {
        let xmp = generate_xmp(&test_metadata(), 10_000);
        assert!(xmp.contains("hdrgm:Version=\"1.0\""));
        assert!(xmp.contains("hdrgm:GainMapMax"));
        assert!(xmp.contains("Item:Length=\"10000\""));
        assert!(xmp.contains("Item:Semantic=\"GainMap\""));
    }

    /// XMP serializes f64 via `{:.6}` format, so roundtrip error is
    /// bounded by that — one ULP at the 6th decimal ≈ 5e-7. Anything
    /// looser hides real precision bugs.
    const XMP_FLOAT_TOL: f64 = 1e-5;

    #[test]
    fn parse_xmp_roundtrips_scalar_values() {
        let original = test_metadata();
        let xmp = generate_xmp(&original, 5_000);
        let (parsed, length) = parse_xmp(&xmp).unwrap();
        assert_eq!(length, Some(5_000));
        // Verify every numeric field roundtrips, not just .max.
        for i in 0..3 {
            assert!((parsed.channels[i].min - original.channels[i].min).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].max - original.channels[i].max).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].gamma - original.channels[i].gamma).abs() < XMP_FLOAT_TOL);
            assert!(
                (parsed.channels[i].base_offset - original.channels[i].base_offset).abs()
                    < XMP_FLOAT_TOL
            );
            assert!(
                (parsed.channels[i].alternate_offset - original.channels[i].alternate_offset).abs()
                    < XMP_FLOAT_TOL
            );
        }
        assert!((parsed.base_hdr_headroom - original.base_hdr_headroom).abs() < XMP_FLOAT_TOL);
        assert!(
            (parsed.alternate_hdr_headroom - original.alternate_hdr_headroom).abs() < XMP_FLOAT_TOL
        );
    }

    #[test]
    fn parse_xmp_roundtrips_multi_channel_values() {
        let original = multi_channel_metadata();
        let xmp = generate_xmp(&original, 5_000);
        let (parsed, _) = parse_xmp(&xmp).unwrap();
        // All three channels must differ — a regression that replicated
        // channel-0 to 1/2 would have channels[0].min == channels[1].min.
        for i in 0..3 {
            assert!((parsed.channels[i].min - original.channels[i].min).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].max - original.channels[i].max).abs() < XMP_FLOAT_TOL);
        }
        assert!(
            (parsed.channels[0].min - parsed.channels[1].min).abs() > 0.5,
            "channels must remain distinct across the roundtrip"
        );
    }

    #[test]
    fn parse_xmp_rejects_non_ultrahdr_packet() {
        let xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        dc:creator="SomeCamera"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#;
        assert!(matches!(parse_xmp(xmp), Err(XmpError::NotUltraHdr)));
    }

    /// Pins the accepted-input ceiling. If someone shrinks
    /// `MAX_XMP_LENGTH` (as was mistakenly done during the initial
    /// container-module extraction — 16 MiB became 1 MiB), this test
    /// fails by value-equality, not just behavior.
    #[test]
    fn max_xmp_length_is_16_mib() {
        assert_eq!(MAX_XMP_LENGTH, 16 * 1024 * 1024);
    }

    #[test]
    fn parse_xmp_rejects_oversized_input() {
        let mut big = String::with_capacity(MAX_XMP_LENGTH + 100);
        big.push_str("hdrgm:Version=\"1.0\" ");
        while big.len() <= MAX_XMP_LENGTH {
            big.push_str("                                   ");
        }
        assert!(matches!(parse_xmp(&big), Err(XmpError::LengthLimit { .. })));
    }

    /// 1 MiB of valid XMP must be accepted — confirms the 16 MiB cap
    /// isn't silently re-tightened.
    #[test]
    fn parse_xmp_accepts_1_mib_input() {
        let mut big = String::with_capacity(1024 * 1024 + 100);
        big.push_str(&generate_gainmap_xmp(&test_metadata()));
        while big.len() <= 1024 * 1024 {
            big.push_str("                                   ");
        }
        assert!(parse_xmp(&big).is_ok(), "1 MiB XMP must not trip the cap");
    }

    /// Regression test for issue #144: the gain-map XMP packet from
    /// `seine_sdr_gainmap_srgb.jpg` (Adobe Camera Raw output), verbatim.
    /// Scalars are attributes; GainMapMin/Max/Gamma are rdf:Seq
    /// elements. The old parser zeroed all three element-form fields.
    #[test]
    fn parse_xmp_rdf_seq_element_form_seine_fixture() {
        let xmp = r#"<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.0-c000 1.000000, 0000/00/00-00:00:00        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:hdrgm="http://ns.adobe.com/hdr-gain-map/1.0/"
   hdrgm:Version="1.0"
   hdrgm:BaseRenditionIsHDR="False"
   hdrgm:OffsetSDR="0.015625"
   hdrgm:OffsetHDR="0.015625"
   hdrgm:HDRCapacityMin="0"
   hdrgm:HDRCapacityMax="1.3">
   <hdrgm:GainMapMin>
    <rdf:Seq>
     <rdf:li>-0.256907</rdf:li>
     <rdf:li>-0.261365</rdf:li>
     <rdf:li>-0.280284</rdf:li>
    </rdf:Seq>
   </hdrgm:GainMapMin>
   <hdrgm:GainMapMax>
    <rdf:Seq>
     <rdf:li>1.277177</rdf:li>
     <rdf:li>1.277203</rdf:li>
     <rdf:li>1.277969</rdf:li>
    </rdf:Seq>
   </hdrgm:GainMapMax>
   <hdrgm:Gamma>
    <rdf:Seq>
     <rdf:li>0.953784</rdf:li>
     <rdf:li>0.941095</rdf:li>
     <rdf:li>0.919422</rdf:li>
    </rdf:Seq>
   </hdrgm:Gamma>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"#;
        let (parsed, length) = parse_xmp(xmp).expect("seine gain-map XMP must parse");
        assert_eq!(length, None);

        let expect_min = [-0.256907, -0.261365, -0.280284];
        let expect_max = [1.277177, 1.277203, 1.277969];
        let expect_gamma = [0.953784, 0.941095, 0.919422];
        for i in 0..3 {
            assert!(
                (parsed.channels[i].min - expect_min[i]).abs() < XMP_FLOAT_TOL,
                "ch[{i}].min: {}",
                parsed.channels[i].min
            );
            assert!(
                (parsed.channels[i].max - expect_max[i]).abs() < XMP_FLOAT_TOL,
                "ch[{i}].max: {}",
                parsed.channels[i].max
            );
            assert!(
                (parsed.channels[i].gamma - expect_gamma[i]).abs() < XMP_FLOAT_TOL,
                "ch[{i}].gamma: {}",
                parsed.channels[i].gamma
            );
            assert!((parsed.channels[i].base_offset - 0.015625).abs() < XMP_FLOAT_TOL);
            assert!((parsed.channels[i].alternate_offset - 0.015625).abs() < XMP_FLOAT_TOL);
        }
        assert!((parsed.base_hdr_headroom - 0.0).abs() < XMP_FLOAT_TOL);
        assert!((parsed.alternate_hdr_headroom - 1.3).abs() < XMP_FLOAT_TOL);
        // The downstream gate that exposed #144: gamma=0 fails validate().
        parsed.validate().expect("parsed params must validate");
    }

    #[test]
    fn malformed_numbers_refuse_instead_of_changing_rendering() {
        let xml = generate_gainmap_xmp(&test_metadata())
            .replace("hdrgm:Gamma=\"1.000000\"", "hdrgm:Gamma=\"oops\"");
        assert!(matches!(parse_xmp(&xml), Err(XmpError::Invalid(_))));
    }

    #[test]
    fn namespace_alias_and_gainmap_item_identity() {
        let items = alloc::vec![
            ContainerItem::primary("image/jpeg"),
            ContainerItem::secondary(ItemSemantic::DepthMap, "image/jpeg", 9),
            ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", 123)
        ];
        let xml = generate_xmp_with_items(&test_metadata(), &items)
            .replace("hdrgm:", "gain:")
            .replace("xmlns:hdrgm=", "xmlns:gain=");
        assert_eq!(parse_xmp(&xml).unwrap().1, Some(123));
        let fake = xml.replace(HDRGM_NAMESPACE, "urn:spoof");
        assert!(matches!(parse_xmp(&fake), Err(XmpError::NotUltraHdr)));
        let duplicate = xml.replace(
            "gain:Version=\"1.0\"",
            "gain:Version=\"1.0\" gain:Version=\"1.0\"",
        );
        assert!(parse_xmp(&duplicate).is_err());
    }

    #[test]
    fn parse_xmp_full_returns_items_even_without_numeric_metadata() {
        let items = alloc::vec![
            ContainerItem::primary("image/jpeg"),
            ContainerItem::secondary(ItemSemantic::GainMap, "image/jpeg", 123),
        ];
        let xmp = generate_primary_xmp_with_items(&items);
        let (meta, parsed) = parse_xmp_full(&xmp);
        assert!(meta.is_some()); // primary_xmp has hdrgm:Version
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[1].length, Some(123));
    }

    #[test]
    fn generate_gainmap_xmp_has_only_numeric_attrs() {
        let xmp = generate_gainmap_xmp(&test_metadata());
        assert!(xmp.contains("hdrgm:Version=\"1.0\""));
        assert!(xmp.contains("hdrgm:GainMapMax"));
        // Gain-map XMP should NOT carry Container:Directory.
        assert!(!xmp.contains("Container:Directory"));
    }

    #[test]
    fn create_xmp_app1_marker_shape() {
        let xmp = "<x:xmpmeta/>";
        let marker = create_xmp_app1_marker(xmp);
        assert_eq!(marker[0], 0xFF);
        assert_eq!(marker[1], 0xE1);
        // Length word includes itself + namespace + xmp bytes.
        let declared = u16::from_be_bytes([marker[2], marker[3]]) as usize;
        assert_eq!(declared, marker.len() - 2);
        assert!(marker.ends_with(xmp.as_bytes()));
    }

    #[test]
    fn parse_xmp_no_panic_on_garbage() {
        let _ = parse_xmp("");
        let _ = parse_xmp("hdrgm:GainMapMax=\"not_a_number\"");
        let garbage: String = (0..4096).map(|i| (i % 128) as u8 as char).collect();
        let _ = parse_xmp(&garbage);
    }

    // -----------------------------------------------------------------------
    // Property tests: parse(generate(x)) ≈ x (within f64 serialization tol)
    // -----------------------------------------------------------------------

    use proptest::prelude::*;

    // `GainMapChannel` and `GainMapParams` are both `#[non_exhaustive]`
    // in zencodec, so we can't construct them with struct-literal syntax
    // from this crate. Default + field assignment is the only option;
    // silence the clippy lint that wants struct literals.
    #[allow(clippy::field_reassign_with_default)]
    fn arb_gainmap_params() -> impl Strategy<Value = zencodec::GainMapParams> {
        // Bounded ranges keep `{:.6}` formatting well inside the f64 ULP
        // envelope. XMP gain-map values in the wild are bounded to
        // roughly [-1024, 1024] — we restrict well within that.
        let ch_arb = (
            -100.0f64..100.0, // min
            -100.0f64..100.0, // max
            0.01f64..10.0,    // gamma (must be > 0 per spec)
            0.0f64..1.0,      // base_offset
            0.0f64..1.0,      // alternate_offset
        )
            .prop_map(|(min, max, gamma, bo, ao)| {
                let mut c = zencodec::GainMapChannel::default();
                c.min = min.min(max);
                c.max = min.max(max);
                c.gamma = gamma;
                c.base_offset = bo;
                c.alternate_offset = ao;
                c
            });

        (
            [ch_arb.clone(), ch_arb.clone(), ch_arb],
            -10.0f64..10.0, // base_hdr_headroom
            0.0f64..10.0,   // alternate_hdr_headroom
            any::<bool>(),  // use_base_color_space
        )
            .prop_map(|(channels, base_hr, alt_hr, use_base)| {
                let mut m = zencodec::GainMapParams::default();
                m.channels = channels;
                m.base_hdr_headroom = base_hr;
                m.alternate_hdr_headroom = alt_hr;
                m.use_base_color_space = use_base;
                m
            })
    }

    proptest! {
        /// Any GainMapParams in the supported numeric range roundtrips
        /// through `generate_xmp` → `parse_xmp` with all per-channel
        /// fields (min, max, gamma, base_offset, alternate_offset) and
        /// both headroom fields preserved within f64 `{:.6}` tolerance.
        #[test]
        fn gainmap_xmp_roundtrip(params in arb_gainmap_params(), length in 1usize..10_000_000) {
            let xmp = generate_xmp(&params, length);
            let (parsed, parsed_length) = parse_xmp(&xmp)
                .expect("parse should succeed on self-generated XMP");
            prop_assert_eq!(parsed_length, Some(length));

            for i in 0..3 {
                prop_assert!(
                    (parsed.channels[i].min - params.channels[i].min).abs() < XMP_FLOAT_TOL,
                    "ch[{i}].min: orig {} parsed {}", params.channels[i].min, parsed.channels[i].min
                );
                prop_assert!(
                    (parsed.channels[i].max - params.channels[i].max).abs() < XMP_FLOAT_TOL,
                    "ch[{i}].max",
                );
                prop_assert!(
                    (parsed.channels[i].gamma - params.channels[i].gamma).abs() < XMP_FLOAT_TOL,
                    "ch[{i}].gamma",
                );
                prop_assert!(
                    (parsed.channels[i].base_offset - params.channels[i].base_offset).abs()
                        < XMP_FLOAT_TOL,
                    "ch[{i}].base_offset",
                );
                prop_assert!(
                    (parsed.channels[i].alternate_offset - params.channels[i].alternate_offset).abs()
                        < XMP_FLOAT_TOL,
                    "ch[{i}].alternate_offset",
                );
            }
            prop_assert!(
                (parsed.base_hdr_headroom - params.base_hdr_headroom).abs() < XMP_FLOAT_TOL,
            );
            prop_assert!(
                (parsed.alternate_hdr_headroom - params.alternate_hdr_headroom).abs()
                    < XMP_FLOAT_TOL,
            );
        }
    }
}
