//! Byte-identity regression: default build (feature `boundary-rd` OFF)
//! must produce bit-for-bit identical output to pre-boundary-RD
//! `origin/main`.
//!
//! This test is the **only reason** the boundary-RD feature exists as
//! an opt-in Cargo flag: users who don't opt in MUST NOT see any
//! behavioral drift from the refinement plumbing.
//!
//! Hashes were generated by extracting `origin/main` (commit
//! `aae28ce8118fafbd6eb38ac1150cb6d5fe6edbee`) into a clean build tree,
//! dropping the lineart corpus into the same relative path, and running
//! the same encode config against each PNG. The hashes in this file
//! match both origin/main and the current worktree's default build.
//!
//! # When a hash here drifts
//!
//! - **Expected failure:** you intentionally changed encoder behavior
//!   and bumped the `values_archmage.csv` hash in `locked_values.rs`.
//!   Regenerate these hashes alongside those.
//!
//! - **Unexpected failure:** the boundary-RD gating leaked into the
//!   default path. Stop, diff against origin/main, find the leak.
//!
//! This test intentionally runs **regardless of feature flags** so that
//! a user who accidentally enables `boundary-rd` via a dep still gets
//! byte-identity protection for the `BoundaryRd::Off` default.

use enough::Unstoppable;
use sha2::{Digest, Sha256};
use std::io::Cursor;
use zenjpeg::encoder::{ChromaSubsampling, EncoderConfig, PixelLayout};

/// Relative path from the crate Cargo.toml → repo root → corpus dir.
const LINEART_DIR: &str = "../benchmarks/boundary_rd/sweep_corpus/lineart";

/// Pinned hashes generated against `origin/main` @ aae28ce8 (2026-04-20).
/// Order: (stem, width, quality, sha256, expected_len).
#[allow(clippy::type_complexity)]
const PINNED: &[(&str, u32, u32, &str, usize)] = &[
    (
        "flat_blocks",
        512,
        25,
        "b656af42210f2b072a6f02f04ec479cc7acc7954c2bfe322cdba1949e55b5140",
        3381,
    ),
    (
        "flat_blocks",
        512,
        50,
        "3a1d6ab6cf16031f461bce2082ae083c32b973d0c9f195bb8c6ee7e665d59503",
        3927,
    ),
    (
        "flat_blocks",
        512,
        75,
        "b0d1affad0a62968bd27a4c59603604c86311513d693e7255c81f8544147e742",
        4772,
    ),
    (
        "flat_blocks",
        512,
        90,
        "0e782a749da7950b30f36b366103911436875a26f393999e13e84d7b1a171472",
        6364,
    ),
    (
        "text_label",
        512,
        25,
        "5f057152558823058647f4f971da4fbeab8ef9e8b9ac91a3dcc6ecdcb3a37a84",
        8400,
    ),
    (
        "text_label",
        512,
        50,
        "1d74036c4a6af6b814fdb62d5e7b53073c627bf4191f918b43b6a1d747f0cb0d",
        10258,
    ),
    (
        "text_label",
        512,
        75,
        "ba953fd06fd8d8b4286bdcd05e67324f0cad709e046058ca4855202dd16d4ffe",
        13243,
    ),
    (
        "text_label",
        512,
        90,
        "ba53ffbbfdd7ba6133d50c39bba01ea9de8fe93ae924108dd21a24e43d984d12",
        17982,
    ),
    (
        "ui_mockup",
        512,
        25,
        "e910104293e401a461fcf424e732f4f5709d4c6fbf9faad3943f8c1a71570cdf",
        5417,
    ),
    (
        "ui_mockup",
        512,
        50,
        "30a2c04fcf013c877f568032aefb9d36a30f7333a7ece69434ad39d3ce42f6ca",
        6481,
    ),
    (
        "ui_mockup",
        512,
        75,
        "1bd39751d2b2eed61ad5555c204a607428c4f66dcf3c32778e819aabc8baeb6c",
        7942,
    ),
    (
        "ui_mockup",
        512,
        90,
        "476cdd3a7d3be79ea56405f809cee6386ee2a19cd30e46a237ee5938eb01cfa5",
        9831,
    ),
    (
        "vector_art",
        512,
        25,
        "6fae79f4f4f6151a668a30566e03c4771d28d5687a04d540a20f345faf7fc9db",
        8720,
    ),
    (
        "vector_art",
        512,
        50,
        "035223f2b2f6ebd2317224580db3f564b8df3be4a0f8d5d19d35d6a01596c53b",
        11050,
    ),
    (
        "vector_art",
        512,
        75,
        "b8f94c2e9d63ad0c31a8d804b8f2d383e62a4bdab6333998790ccdd9f82fd1f9",
        15868,
    ),
    (
        "vector_art",
        512,
        90,
        "8068293d9bacd1f241ee8e39e28c107287130560201d51653e01b7cf57f46e08",
        25396,
    ),
];

fn decode_png(path: &str) -> (u32, u32, Vec<u8>) {
    let data = std::fs::read(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let decoder = png::Decoder::new(Cursor::new(data));
    let mut reader = decoder.read_info().expect("read png info");
    let mut buf = vec![0u8; reader.output_buffer_size().expect("png size")];
    let info = reader.next_frame(&mut buf).expect("png next frame");
    buf.truncate(info.buffer_size());
    let rgb = match info.color_type {
        png::ColorType::Rgb => buf,
        png::ColorType::Rgba => {
            let mut out = Vec::with_capacity((buf.len() / 4) * 3);
            for chunk in buf.chunks_exact(4) {
                out.extend_from_slice(&chunk[0..3]);
            }
            out
        }
        other => panic!("unexpected png color type: {other:?}"),
    };
    (info.width, info.height, rgb)
}

fn encode_default(rgb: &[u8], w: u32, h: u32, q: u32) -> Vec<u8> {
    let cfg = EncoderConfig::ycbcr(q as f32, ChromaSubsampling::Quarter);
    let mut enc = cfg
        .encode_from_bytes(w, h, PixelLayout::Rgb8Srgb)
        .expect("encoder");
    enc.push_packed(rgb, Unstoppable).expect("push");
    enc.finish().expect("finish")
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

#[test]
fn default_build_matches_origin_main_lineart_corpus() {
    let base = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dir = std::path::Path::new(&base).join(LINEART_DIR);
    if !dir.exists() {
        // Corpus is part of the repo under benchmarks/; if a downstream
        // consumer built the crate from a .crate tarball (which strips
        // `benchmarks/`), skip silently. The locked_values test covers
        // encoder determinism via a different path in that environment.
        eprintln!(
            "lineart corpus missing at {:?}; skipping byte-identity test \
             (this is expected when building from a packaged .crate file)",
            dir
        );
        return;
    }

    let mut last_stem: Option<&str> = None;
    let mut cached_img: Option<(u32, u32, Vec<u8>)> = None;

    for &(stem, expected_w, q, expected_hash, expected_len) in PINNED {
        let path = dir.join(format!("{stem}.png"));

        // Cache the decoded PNG across quality levels for the same stem.
        if last_stem != Some(stem) {
            cached_img = Some(decode_png(path.to_str().unwrap()));
            last_stem = Some(stem);
        }
        let (w, h, ref rgb) = *cached_img.as_ref().unwrap();
        assert_eq!(w, expected_w, "{stem} width drift");
        assert_eq!(h, expected_w, "{stem} height drift (corpus is square)");

        let jpeg = encode_default(rgb, w, h, q);
        let hash = sha256_hex(&jpeg);

        assert_eq!(
            jpeg.len(),
            expected_len,
            "{stem}@q{q}: length drift — default build diverged from \
             origin/main. Either encoder behavior changed (and this \
             test needs regenerated hashes alongside locked_values.rs), \
             or the boundary-RD gating leaked into the default path.",
        );
        assert_eq!(
            hash, expected_hash,
            "{stem}@q{q}: SHA-256 drift — default build diverged from \
             origin/main. Either encoder behavior changed (and this \
             test needs regenerated hashes alongside locked_values.rs), \
             or the boundary-RD gating leaked into the default path.",
        );
    }
}
