//! Locked SHA256 hash tests for frymire.png encoding.
//!
//! These tests verify that encoder output is byte-for-byte reproducible.
//! Any refactoring that changes output will break these tests.
//!
//! Test image: tests/images/frymire.png (1118x1105 RGB)
//!
//! To regenerate hashes after intentional changes:
//!   cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
//!
//! ⚠️ LOCKED TEST: Do NOT modify hash values without understanding the impact.

use sha2::{Digest, Sha256};
use zenjpeg::encoder::{
    ChromaSubsampling, DownsamplingMethod, EncoderConfig, PixelLayout, XybSubsampling,
};

// =============================================================================
// CONFIGURATION
// =============================================================================

/// Quality levels to test (representative sample)
const QUALITY_LEVELS: &[u8] = &[50, 75, 90];

// =============================================================================
// EXPECTED HASHES (generated by print_all_hashes)
// Format: (config_name, quality, sha256_hex, size_bytes)
// =============================================================================

// frymire.png: 1118x1105
// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
//
// The archmage SIMD uses explicit SIMD intrinsics for DCT which produces
// slightly different float rounding than the wide-crate autovectorized path.
// This affects ~14 of 36 entries (mostly Q75/Q90 YCbCr configs; XYB is identical).
// Both sets are valid — they represent the same algorithm with different FP precision.

// Updated 2026-03-31: linear-srgb 0.6.5→0.6.6 changed GammaAware/GammaAwareIterative
// downsampling output; baseline_420_gamma and baseline_420_sharpyuv hashes updated.
#[cfg(target_arch = "x86_64")]
const EXPECTED_HASHES: &[(&str, u8, &str, usize)] = &[
    (
        "baseline_444_opt",
        50,
        "73004e7c85551b63db097fb8a1c1116581ee8786aac92b6dd8c38fff77906ee8",
        327016,
    ),
    (
        "baseline_444_opt",
        75,
        "c1dc9628b8ff41f8b8fd9800e94f5925237aaab6297106c01e0befbdbc6e856e",
        473427,
    ),
    (
        "baseline_444_opt",
        90,
        "d83236f51895c568e49fe1529933ea9f11439b3b801dbfa4e171432211b40e3a",
        713175,
    ),
    (
        "baseline_444_fixed",
        50,
        "f4b4ea91f5d3b0128f41144a4729c5eac345826b69f14670af0f22f8b1eaa484",
        340427,
    ),
    (
        "baseline_444_fixed",
        75,
        "560f3ecb8d44286f8ab0c1d768bc62d504e4d4211d178572650abb225559cfb0",
        488382,
    ),
    (
        "baseline_444_fixed",
        90,
        "5fd36d673156678d527c7d9c1ba2677239bca83d6a78119ea83f5a3f7dfa2b84",
        749302,
    ),
    (
        "baseline_420_opt",
        50,
        "83c64bd847abd6eb45ccff8f7a876525192219a1b955a4787952249bba116068",
        267414,
    ),
    (
        "baseline_420_opt",
        75,
        "134016a4a2ba49fe7cc830661724f17ee559ca16e5d0d67bc489da605c70993a",
        394950,
    ),
    (
        "baseline_420_opt",
        90,
        "948cda97d855cec2127ce885926222bbf45fb55cb3c5defd4e44788db9012570",
        582322,
    ),
    (
        "baseline_420_gamma",
        50,
        "e29258f39aa77d276d448e5678c44eaab86b6aea1cd165b5d3b428ad6f37fc52",
        268313,
    ),
    (
        "baseline_420_gamma",
        75,
        "1cd5c1cd44af122f0363dd588fdad17356f02e75d532e4d9c447f6ee40d80a5b",
        396612,
    ),
    (
        "baseline_420_gamma",
        90,
        "bf542b185aadb87080f466dc8c7f23f03f43d0175954eacc3aa20cb8048ecb6a",
        584723,
    ),
    (
        "baseline_420_sharpyuv",
        50,
        "8a86afdab65154482f3a287d13908c1d3a9e961608ff628ad6e387c35cde5da0",
        267866,
    ),
    (
        "baseline_420_sharpyuv",
        75,
        "91dfd18a2ff2f025f976b2a4da14db9c0fe9a4c541f65838661a660546617f88",
        395931,
    ),
    (
        "baseline_420_sharpyuv",
        90,
        "cd68d01d32d5eb9fb265debe2f7009b98479d8e88275f55c24611110985f9f98",
        583660,
    ),
    (
        "baseline_422_opt",
        50,
        "845bbd2f36b8142c80da01150fb12c1cfdeb8a96f34e50ec563a9df26954129f",
        290890,
    ),
    (
        "baseline_422_opt",
        75,
        "e9a7c8c790fa9a4fe64c2ebf5b748a244668f390b67787f1472f5bdd43eb2828",
        416790,
    ),
    (
        "baseline_422_opt",
        90,
        "263510614dc7d491cf66b5d5ff3ae8b7d23a18b9f2ec5cb33962dbf213173ac5",
        610396,
    ),
    (
        "baseline_440_opt",
        50,
        "68a144aee157f283bfd614e2d744970b46cffd1b0d6c4ccc632632a06a492160",
        291142,
    ),
    (
        "baseline_440_opt",
        75,
        "17f0acaccedc085d71791c71ce826fde1bf9a219c9a956ffba75cabf7bfa7e1a",
        417514,
    ),
    (
        "baseline_440_opt",
        90,
        "88133f150c15f0495b428b0c36aa8ce05a40c755c22fd2b6ed0e8fbba119ba18",
        612493,
    ),
    (
        "progressive_444_opt",
        50,
        "eb8730bba5393960eac3f9c92b6a627afa458128b21c4eb13cfb3b84720f9979",
        317203,
    ),
    (
        "progressive_444_opt",
        75,
        "c4b5516a2aa8b4d6e57fd7e2174259a7b9717183d1d044561e0f46116df525b1",
        458015,
    ),
    (
        "progressive_444_opt",
        90,
        "8a9e75e21d814a03af84d3df29c325b6b7344371ed262979dd11b689a2a0e4bc",
        690703,
    ),
    (
        "progressive_420_opt",
        50,
        "44f27c1f82a9872b51a8ee5e5fa784b0f2bae7d4b05775c722c39636df500cce",
        258247,
    ),
    (
        "progressive_420_opt",
        75,
        "4bd45287bc44b5154aa5fd5b70055622c3d46017352d0d24e9201dda3b828b0b",
        380487,
    ),
    (
        "progressive_420_opt",
        90,
        "4ed8581ffe58ae95be1a40b30e1f2a31b0dc694eeb0e754b1c6ce41fe656d090",
        560337,
    ),
    // XYB: identical between SIMD and non-SIMD
    // Updated 2026-03-09: XYB now defaults allow_16bit_quant_tables=false (8-bit DQT)
    // with force_sof1=true (SOF1 for DC categories). All sequential XYB hashes changed
    // because SOF marker is now always 0xC1 (SOF1) regardless of quant value range.
    // Progressive XYB uses SOF2 (unchanged by force_sof1).
    (
        "baseline_xyb_opt",
        50,
        "aad76243f8ce84b8772653767acc6ad2f8472f4ee7aeb763c02b516f77c01266",
        288338,
    ),
    (
        "baseline_xyb_opt",
        75,
        "8f72f8225c32c7fb83feb09bb76bf520ae537e886785daea4310435756c2a0e8",
        404047,
    ),
    (
        "baseline_xyb_opt",
        90,
        "02f0a8bb4f70a4d827ee8ac10072c9965cff2497f6f1a40880bac707daf4ba99",
        604469,
    ),
    (
        "baseline_xyb_fixed",
        50,
        "707bd2dc6465a555674998ad8fa9dc9ecf11a3e47f0a16d8e5d3c6fb1ef9327f",
        294978,
    ),
    (
        "baseline_xyb_fixed",
        75,
        "f28ba97f5dc42b9cffc3794940a313e599febb28ae9aca0c0a3739581f30daa2",
        419319,
    ),
    (
        "baseline_xyb_fixed",
        90,
        "e19bcdd933e1228ffb57386eba8dff41f2f970aaf2c8ce3e68260683008fc3df",
        616582,
    ),
    (
        "progressive_xyb_opt",
        50,
        "32bd816ccfbb418ac4b5cb11130269a136d49eb8391faae002c6678bff80f15e",
        272849,
    ),
    (
        "progressive_xyb_opt",
        75,
        "77c13a82e8c6db826161b107e67238371b01313c4972290887820fdd68fe4e42",
        384155,
    ),
    (
        "progressive_xyb_opt",
        90,
        "adabe9292d70fd48f4a3ef85c79ddd31ea3b0e8d8e8f838be1b4727a31f62d9c",
        571912,
    ),
];

// Updated 2026-03-31: archmage/magetypes 0.9.15 changed NEON output on aarch64;
// linear-srgb 0.6.6 changed GammaAware/GammaAwareIterative downsampling output.
// All non-x86_64 hashes regenerated from ubuntu-24.04-arm CI run.
#[cfg(not(target_arch = "x86_64"))]
const EXPECTED_HASHES: &[(&str, u8, &str, usize)] = &[
    (
        "baseline_444_opt",
        50,
        "2deaece64217edfd4bdef771fbc33349e9564c985604191da5721f155d41521e",
        327060,
    ),
    (
        "baseline_444_opt",
        75,
        "c0172dcae9c4de8384512ab3baf3a907b414cfd6d6ac544f6face2afed2b3537",
        473510,
    ),
    (
        "baseline_444_opt",
        90,
        "0456d1eccd5315e6afd3616018de2c2024928b312627febccf735ec22f4d058c",
        713220,
    ),
    (
        "baseline_444_fixed",
        50,
        "e0591f25f3830e4c6109f92452778d8854849866c553c627031f7e537428bb81",
        340486,
    ),
    (
        "baseline_444_fixed",
        75,
        "26da607f14850495b3e4001545342978426fdda78b9c32c05e270a7f830bc84b",
        488449,
    ),
    (
        "baseline_444_fixed",
        90,
        "3221afa7f3dcdd0cdc41cc56a423b98e5de1c2b0f7ab673ed96ec0db98c44a27",
        749357,
    ),
    (
        "baseline_420_opt",
        50,
        "7fd45dd3e5305a66bb1259c8130f7ad0df6f891f4407993b149b95c4edddfebe",
        267272,
    ),
    (
        "baseline_420_opt",
        75,
        "2ace4be37fca3e6bd95b6a32f124d665b6bc94614987dfca167fe33d5f58613e",
        394930,
    ),
    (
        "baseline_420_opt",
        90,
        "18c9d4cdb53020e56b687e79ce056d892402548bca1c73ded93ff5ec41f3c1e4",
        582256,
    ),
    (
        "baseline_420_gamma",
        50,
        "d876eedbb9648fb95c97e1462435edeb1b36f93d9168200a9a8a0d3dd012297e",
        268261,
    ),
    (
        "baseline_420_gamma",
        75,
        "834770c8b1d2100f42e0f3224d182bc0cde534133934b7d3695be0e729e8e741",
        396612,
    ),
    (
        "baseline_420_gamma",
        90,
        "487f768e0e8aae7301b22757dec70dd509e1586bca5c83e85868e2f66bf22421",
        584673,
    ),
    (
        "baseline_420_sharpyuv",
        50,
        "1482e0b08a9a1fbeb1e129f449b4b1fd734dae9019848cfdd3500ab6e34be778",
        267859,
    ),
    (
        "baseline_420_sharpyuv",
        75,
        "a18d220ab234c2971b6b2d1f693b1746a6022e3f2c8c18ff9d636cba6444e0de",
        395931,
    ),
    (
        "baseline_420_sharpyuv",
        90,
        "407cf3479d151b45cabe9ecc6e43a084c0818d75dc6c0aa7387a95839352bf23",
        583671,
    ),
    (
        "baseline_422_opt",
        50,
        "5ec528ba4cc16bb46962f752185e90e857b04e2ca725b55b6d5f25a7d55f2fdc",
        290916,
    ),
    (
        "baseline_422_opt",
        75,
        "51d9218af5421dc45ad62fc042508fac6fa678a55e4cf8eea8b136684b7fc4b7",
        416808,
    ),
    (
        "baseline_422_opt",
        90,
        "af990597cd60690830b35c4b169eab5da02391d89d81643c445dd78ea400b40b",
        610376,
    ),
    (
        "baseline_440_opt",
        50,
        "6ba2f2bd1b198e1771761ddae080d472a3db604fad3c2045f2d8af4eb9ffbbd8",
        291092,
    ),
    (
        "baseline_440_opt",
        75,
        "e935fd0e84badf916c84fd0e68e6974bc7424b0fb2c11d23b03798cae9bc42d6",
        417498,
    ),
    (
        "baseline_440_opt",
        90,
        "50f9237c6c24d3938c748082f92ab84b6726f203478deff861ac8700233b7257",
        612436,
    ),
    (
        "progressive_444_opt",
        50,
        "0220e3e0c52e2584d853fb6444b752858abd78b3e7f40e203fcde947ffb321a2",
        317204,
    ),
    (
        "progressive_444_opt",
        75,
        "c8e303325d9b396680ff1e2116ad8ba6bde203ca6954f53577f9e1f9799cdf56",
        458021,
    ),
    (
        "progressive_444_opt",
        90,
        "f64b0a185c59d21b8861742fb52bd01a1f4e43ddb3292f7bdd09a2fbd4e21869",
        690722,
    ),
    (
        "progressive_420_opt",
        50,
        "5b5819804812f24a1ea12b60e71784386b663a760d6eb6a3428876a889fe9eea",
        258214,
    ),
    (
        "progressive_420_opt",
        75,
        "721a37c37a2d02d83112f6b2d377567f7e8493897dc232cef59fd13ce0071f38",
        380482,
    ),
    (
        "progressive_420_opt",
        90,
        "ba08017e5de3a668b3ea9e7229c6669fdc34214c8d089bb5007bf7565931a9fd",
        560354,
    ),
    // XYB: xyb_opt Q90 changed; others identical to x86_64
    (
        "baseline_xyb_opt",
        50,
        "aad76243f8ce84b8772653767acc6ad2f8472f4ee7aeb763c02b516f77c01266",
        288338,
    ),
    (
        "baseline_xyb_opt",
        75,
        "8f72f8225c32c7fb83feb09bb76bf520ae537e886785daea4310435756c2a0e8",
        404047,
    ),
    (
        "baseline_xyb_opt",
        90,
        "f6fe3e0b4d1e6ced217b216efea6ffd358268f986713d3a04d45e4c451b66600",
        604483,
    ),
    (
        "baseline_xyb_fixed",
        50,
        "707bd2dc6465a555674998ad8fa9dc9ecf11a3e47f0a16d8e5d3c6fb1ef9327f",
        294978,
    ),
    (
        "baseline_xyb_fixed",
        75,
        "f28ba97f5dc42b9cffc3794940a313e599febb28ae9aca0c0a3739581f30daa2",
        419319,
    ),
    (
        "baseline_xyb_fixed",
        90,
        "7eebb1c763dae6fcd6d436a5b23ab87a77194223b1c1fa91fb4f13dbf8afbaab",
        616638,
    ),
    (
        "progressive_xyb_opt",
        50,
        "32bd816ccfbb418ac4b5cb11130269a136d49eb8391faae002c6678bff80f15e",
        272849,
    ),
    (
        "progressive_xyb_opt",
        75,
        "77c13a82e8c6db826161b107e67238371b01313c4972290887820fdd68fe4e42",
        384155,
    ),
    (
        "progressive_xyb_opt",
        90,
        "56464b47d996693d1b7333e02d4f1049e4a5f59d230d718c98a67abc2df56237",
        571921,
    ),
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn load_frymire() -> (Vec<u8>, u32, u32) {
    let png_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/images/frymire.png");
    let img = zenjpeg_bench_utils::load_png(&png_path).expect("Failed to load frymire.png");
    let width = img.width() as u32;
    let height = img.height() as u32;
    let rgb: Vec<u8> = img.buf().iter().flat_map(|p| [p.r, p.g, p.b]).collect();
    (rgb, width, height)
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

/// Encoding configuration for testing
#[derive(Clone, Debug)]
struct EncoderTestConfig {
    name: &'static str,
    progressive: bool,
    subsampling: ChromaSubsampling,
    optimize_huffman: bool,
    downsampling_method: DownsamplingMethod,
    use_xyb: bool,
}

impl EncoderTestConfig {
    fn encode(&self, rgb: &[u8], width: u32, height: u32, quality: f32) -> Vec<u8> {
        let config = if self.use_xyb {
            EncoderConfig::xyb(quality, XybSubsampling::BQuarter)
        } else {
            EncoderConfig::ycbcr(quality, self.subsampling)
        }
        .progressive(self.progressive)
        .optimize_huffman(self.optimize_huffman)
        .downsampling_method(self.downsampling_method)
        .deringing(false) // Disable deringing to match locked hashes
        .restart_mcu_rows(0); // Disable restart markers to match locked hashes
        let mut enc = config
            .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
            .expect("encoder setup");
        enc.push_packed(rgb, enough::Unstoppable)
            .expect("push data");
        enc.finish().expect("Encoding failed")
    }

    fn mcu_size(&self) -> usize {
        match self.subsampling {
            ChromaSubsampling::None => 8,
            _ => 16, // All subsampled modes have MCU size of 16
        }
    }
}

/// All configurations to test
fn test_configs() -> Vec<EncoderTestConfig> {
    vec![
        // Baseline modes (YCbCr)
        EncoderTestConfig {
            name: "baseline_444_opt",
            progressive: false,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_444_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_gamma",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAware,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_sharpyuv",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAwareIterative,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_422_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfHorizontal,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_440_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfVertical,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // Progressive modes (YCbCr)
        EncoderTestConfig {
            name: "progressive_444_opt",
            progressive: true,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "progressive_420_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // XYB modes (subsampling is ignored for XYB)
        EncoderTestConfig {
            name: "baseline_xyb_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "baseline_xyb_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "progressive_xyb_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
    ]
}

// =============================================================================
// TESTS
// =============================================================================

/// Verify all configurations produce expected hashes.
///
/// Only runs in release mode without the parallel feature:
/// - Debug mode: floating-point rounding differences cause hash mismatches
/// - Parallel feature: thread ordering causes non-deterministic output
/// - Without yuv feature: YCbCr conversion path produces different output
#[cfg(feature = "yuv")]
#[test]
#[cfg_attr(
    any(debug_assertions, feature = "parallel"),
    ignore = "debug FP rounding or parallel non-determinism causes hash mismatch"
)]
fn test_frymire_hashes_locked() {
    if EXPECTED_HASHES.is_empty() {
        println!("No hashes configured yet. Run print_all_hashes to generate.");
        return;
    }

    let (rgb, width, height) = load_frymire();

    for (config_name, quality, expected_hash, expected_size) in EXPECTED_HASHES {
        let config = test_configs()
            .into_iter()
            .find(|c| c.name == *config_name)
            .expect("Unknown config");

        let jpeg = config.encode(&rgb, width, height, *quality as f32);
        let actual_hash = sha256_hex(&jpeg);

        if jpeg.len() != *expected_size || actual_hash != *expected_hash {
            // Print replacement entry for easy copy-paste into EXPECTED_HASHES
            eprintln!(
                "    (\"{}\", {}, \"{}\", {}),",
                config_name,
                quality,
                actual_hash,
                jpeg.len()
            );
        }

        assert_eq!(
            jpeg.len(),
            *expected_size,
            "{} Q{}: size mismatch!\n  expected: {} bytes\n  actual:   {} bytes\n\
             Replacement: (\"{}\", {}, \"{}\", {}),",
            config_name,
            quality,
            expected_size,
            jpeg.len(),
            config_name,
            quality,
            actual_hash,
            jpeg.len()
        );

        assert_eq!(
            actual_hash,
            *expected_hash,
            "{} Q{}: hash mismatch!\n  expected: {}\n  actual:   {}\n  size: {} bytes",
            config_name,
            quality,
            expected_hash,
            actual_hash,
            jpeg.len()
        );
    }
}

/// Test encoding with various configurations.
/// This verifies strip encoder parity without depending on specific hashes.
///
/// NOTE: Currently skips configs where frymire.png (1118x1105) doesn't align to MCU boundaries.
/// The full-plane encoder has edge padding, but the strip encoder doesn't yet.
/// - 4:4:4: MCU=8, partial cols=6, partial rows=1 -> SKIP
/// - 4:2:0/4:2:2/4:4:0: MCU=16, partial cols=14, partial rows=1 -> SKIP
///
/// TODO: Remove this skip once strip encoder has edge padding.
#[test]
fn test_frymire_backend_parity() {
    let (rgb, width, height) = load_frymire();

    // Test all configs that support strip encoding (baseline and progressive, including XYB)
    let strip_configs = test_configs();

    for config in &strip_configs {
        // Skip configs where dimensions don't align to MCU (strip encoder lacks edge padding)
        let mcu_size = config.mcu_size();
        if width as usize % mcu_size != 0 || height as usize % mcu_size != 0 {
            // Strip encoder doesn't have edge padding yet - skip non-aligned configs
            continue;
        }

        for &quality in &[50u8, 90] {
            // Use Both backend - will error if outputs differ
            let _jpeg = config.encode(&rgb, width, height, quality as f32);
        }
    }
}

// =============================================================================
// UTILITY: Generate hashes
// =============================================================================

/// Print all hashes for updating EXPECTED_HASHES.
/// Run with: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
#[test]
#[ignore = "utility for generating hash values"]
fn print_all_hashes() {
    let (rgb, width, height) = load_frymire();
    println!("// frymire.png: {}x{}", width, height);
    println!(
        "// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture"
    );
    println!("// Format: (config_name, quality, sha256_hex, size_bytes)");
    println!();
    println!("const EXPECTED_HASHES: &[(&str, u8, &str, usize)] = &[");

    for config in test_configs() {
        for &quality in QUALITY_LEVELS {
            let jpeg = config.encode(&rgb, width, height, quality as f32);
            let hash = sha256_hex(&jpeg);
            println!(
                "    (\"{}\", {}, \"{}\", {}),",
                config.name,
                quality,
                hash,
                jpeg.len()
            );
        }
    }

    println!("];");
}

/// Print hash for a single configuration (for debugging).
#[test]
#[ignore = "utility"]
fn print_single_hash() {
    let (rgb, width, height) = load_frymire();

    let config = EncoderConfig::ycbcr(90.0, ChromaSubsampling::None).optimize_huffman(true);
    let mut enc = config
        .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
        .expect("encoder setup");
    enc.push_packed(&rgb, enough::Unstoppable)
        .expect("push data");
    let jpeg = enc.finish().expect("Encoding failed");

    println!("Size: {} bytes", jpeg.len());
    println!("SHA256: {}", sha256_hex(&jpeg));
}
