//! Locked SHA256 hash tests for frymire.png encoding.
//!
//! These tests verify that encoder output is byte-for-byte reproducible.
//! Any refactoring that changes output will break these tests.
//!
//! Test image: tests/images/frymire.png (1118x1105 RGB)
//!
//! To regenerate hashes after intentional changes:
//!   cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
//!
//! ⚠️ LOCKED TEST: Do NOT modify hash values without understanding the impact.

use sha2::{Digest, Sha256};
use std::fs;
use zenjpeg::encoder::{
    ChromaSubsampling, DownsamplingMethod, EncoderConfig, PixelLayout, XybSubsampling,
};

// =============================================================================
// CONFIGURATION
// =============================================================================

/// Quality levels to test (representative sample)
const QUALITY_LEVELS: &[u8] = &[50, 75, 90];

// =============================================================================
// EXPECTED HASHES (generated by print_all_hashes)
// Format: (config_name, quality, sha256_hex, size_bytes)
// =============================================================================

// frymire.png: 1118x1105
// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
// Updated 2026-01-31: Fixed archmage-simd DCT scaling (was 1/8, now 1/64 matching C++)
const EXPECTED_HASHES: &[(&str, u8, &str, usize)] = &[
    (
        "baseline_444_opt",
        50,
        "0d0bf3d05091191403cf2d9917d1bd070f905f51df90b3c66475672bf6dedf24",
        327144,
    ),
    (
        "baseline_444_opt",
        75,
        "438968e95ead7d560af51fe1db64ec902b62b2c59c848e6bb6b8cbc7c09192db",
        473555,
    ),
    (
        "baseline_444_opt",
        90,
        "d83236f51895c568e49fe1529933ea9f11439b3b801dbfa4e171432211b40e3a",
        713175,
    ),
    (
        "baseline_444_fixed",
        50,
        "85ec796b4196e394f3af3f2e0361c3d45fe8901605ece953803da75eb5ebca76",
        342367,
    ),
    (
        "baseline_444_fixed",
        75,
        "800c41379f797783f65f5bb599db8294c593fd28ccceff90f51cf20c4ccbf7a5",
        494040,
    ),
    (
        "baseline_444_fixed",
        90,
        "13558c622ef453dfe1419e2a3c8cd19fa40e7fe430a67755b93750b646a297c5",
        764368,
    ),
    (
        "baseline_420_opt",
        50,
        "9c0c22d786194e62f20fe05d054a479f298f3b763c09b183b21096cd6731fecb",
        267542,
    ),
    (
        "baseline_420_opt",
        75,
        "134016a4a2ba49fe7cc830661724f17ee559ca16e5d0d67bc489da605c70993a",
        394950,
    ),
    (
        "baseline_420_opt",
        90,
        "948cda97d855cec2127ce885926222bbf45fb55cb3c5defd4e44788db9012570",
        582322,
    ),
    (
        "baseline_420_gamma",
        50,
        "3f5975cd7d5a24de46427aafd3b17ed907db1dda8f5dc8a4421686e16069e0e3",
        268387,
    ),
    (
        "baseline_420_gamma",
        75,
        "48ab269a235993af5ae0e256d267af39532c3eb64cb0c93ba89b6059d058441c",
        396612,
    ),
    (
        "baseline_420_gamma",
        90,
        "425b7290854cd8f4ee5d63b5266941ee7b3b83757d69126678de213dd89d154a",
        584723,
    ),
    (
        "baseline_420_sharpyuv",
        50,
        "ccc9d70fb60b3309ff4f11ce8075f21aa36be772e7063e2369d8f650cf0938ca",
        267969,
    ),
    (
        "baseline_420_sharpyuv",
        75,
        "60ba57795f19a406bf3a9b3ca81d18e5ec0817e05f90709aff232b7512fc810b",
        395931,
    ),
    (
        "baseline_420_sharpyuv",
        90,
        "542f31fdaa9e24ba856a213df80699a4b9b5509fcccb9b5b87d60d6a155e7e17",
        583660,
    ),
    (
        "baseline_422_opt",
        50,
        "564a31ebaed17379f03058ee443e45e6ea8b16761d0de307b4501762413994d8",
        291018,
    ),
    (
        "baseline_422_opt",
        75,
        "3d8024bb23d97091528d2646547daf59fe0cd840aecc021526aa8fc17858ad6b",
        416918,
    ),
    (
        "baseline_422_opt",
        90,
        "263510614dc7d491cf66b5d5ff3ae8b7d23a18b9f2ec5cb33962dbf213173ac5",
        610396,
    ),
    (
        "baseline_440_opt",
        50,
        "3fbf4fd95a4fc8102e6279adaffcc03dcba75135556385990b98681044dbd9da",
        291270,
    ),
    (
        "baseline_440_opt",
        75,
        "c1e15693120358d34ff930bdf753c3ec306ad52e953cd89004c5eae5290f09c6",
        417660,
    ),
    (
        "baseline_440_opt",
        90,
        "88133f150c15f0495b428b0c36aa8ce05a40c755c22fd2b6ed0e8fbba119ba18",
        612493,
    ),
    (
        "progressive_444_opt",
        50,
        "d6ed693241472404172a6bba7c923e2b80cce1a1fd09a48b91b6f62140c0efef",
        318153,
    ),
    (
        "progressive_444_opt",
        75,
        "e93d2ffb5a1c334f56b0185bbbf8139656ab194e88a1537c320d6f69f65f4822",
        459805,
    ),
    (
        "progressive_444_opt",
        90,
        "cb6f424232478d7caeb4cb6996a3b7e4ae391f674f41efd7dc2fb31806244ae5",
        693353,
    ),
    (
        "progressive_420_opt",
        50,
        "4e195ce24ba1ef64a2439f8d2fcd26d8f435b9ead57b77f3f8bf5f0017711b7a",
        259182,
    ),
    (
        "progressive_420_opt",
        75,
        "86df9e7c1d11bcebcc879b4c2e38ec7ebe9d20191fc0b8a51617fe7c713428b3",
        381997,
    ),
    (
        "progressive_420_opt",
        90,
        "70701e1f1145946c03b9b6f0207964d578bb6290bfc4d8f6159c033c01c8ab7a",
        562626,
    ),
    (
        "baseline_xyb_opt",
        50,
        "3ad417269eb39f17897ffe5d1df12c3fb69f835800ba31560bf6c01dad09df53",
        304190,
    ),
    (
        "baseline_xyb_opt",
        75,
        "612642691a8cd9c25fb0a13c3af1d835367e1dd02fa8fa70de27d224a8a8e3db",
        425292,
    ),
    (
        "baseline_xyb_opt",
        90,
        "fb65c7ad548ae24f03e390e7d63d736c6b02debc1857639cb82df32c89a984d9",
        637888,
    ),
    (
        "baseline_xyb_fixed",
        50,
        "cc132220ad1dcf4d42214a1ee40f754acc73b4120a81b778d2e3dbf2a8c25ce0",
        313152,
    ),
    (
        "baseline_xyb_fixed",
        75,
        "1c1578f31dceb61344d2aa3d3bab5b0a1a19e31fb6d80accd10e4c14f495c6f0",
        435476,
    ),
    (
        "baseline_xyb_fixed",
        90,
        "cee7d5e2f2e07d897a46ee4a5c333f5c16b94a8425114bd8cbb7f156e9b878a5",
        665456,
    ),
    (
        "progressive_xyb_opt",
        50,
        "4bded684de8e5e2c93d34a02b40079bc9dabdebd1b0937ea6392348cb0eef09f",
        295741,
    ),
    (
        "progressive_xyb_opt",
        75,
        "7f3e8b26d6038bc74bf76c37034744d251dfda60148b47ea0a5bd968e314c61e",
        419333,
    ),
    (
        "progressive_xyb_opt",
        90,
        "c748fda95a83398ecc4f2115709d87e62f3b43cc37fef042882471ae479fe436",
        632609,
    ),
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn load_frymire() -> (Vec<u8>, u32, u32) {
    let png_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/images/frymire.png");
    let png_data = fs::read(&png_path).expect("Failed to read frymire.png");
    let decoder = png::Decoder::new(&png_data[..]);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();

    let rgb: Vec<u8> = match info.color_type {
        png::ColorType::Rgb => buf[..info.buffer_size()].to_vec(),
        png::ColorType::Rgba => buf[..info.buffer_size()]
            .chunks(4)
            .flat_map(|c| [c[0], c[1], c[2]])
            .collect(),
        _ => panic!("Unsupported color type"),
    };

    (rgb, info.width, info.height)
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

/// Encoding configuration for testing
#[derive(Clone, Debug)]
struct EncoderTestConfig {
    name: &'static str,
    progressive: bool,
    subsampling: ChromaSubsampling,
    optimize_huffman: bool,
    downsampling_method: DownsamplingMethod,
    use_xyb: bool,
}

impl EncoderTestConfig {
    fn encode(&self, rgb: &[u8], width: u32, height: u32, quality: f32) -> Vec<u8> {
        let config = if self.use_xyb {
            EncoderConfig::xyb(quality, XybSubsampling::BQuarter)
        } else {
            EncoderConfig::ycbcr(quality, self.subsampling)
        }
        .progressive(self.progressive)
        .optimize_huffman(self.optimize_huffman)
        .downsampling_method(self.downsampling_method)
        .deringing(false); // Disable deringing to match locked hashes
        let mut enc = config
            .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
            .expect("encoder setup");
        enc.push_packed(rgb, enough::Unstoppable)
            .expect("push data");
        enc.finish().expect("Encoding failed")
    }

    fn mcu_size(&self) -> usize {
        match self.subsampling {
            ChromaSubsampling::None => 8,
            _ => 16, // All subsampled modes have MCU size of 16
        }
    }
}

/// All configurations to test
fn test_configs() -> Vec<EncoderTestConfig> {
    vec![
        // Baseline modes (YCbCr)
        EncoderTestConfig {
            name: "baseline_444_opt",
            progressive: false,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_444_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_gamma",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAware,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_420_sharpyuv",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::GammaAwareIterative,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_422_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfHorizontal,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "baseline_440_opt",
            progressive: false,
            subsampling: ChromaSubsampling::HalfVertical,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // Progressive modes (YCbCr)
        EncoderTestConfig {
            name: "progressive_444_opt",
            progressive: true,
            subsampling: ChromaSubsampling::None,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        EncoderTestConfig {
            name: "progressive_420_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter,
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: false,
        },
        // XYB modes (subsampling is ignored for XYB)
        EncoderTestConfig {
            name: "baseline_xyb_opt",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "baseline_xyb_fixed",
            progressive: false,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: false,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
        EncoderTestConfig {
            name: "progressive_xyb_opt",
            progressive: true,
            subsampling: ChromaSubsampling::Quarter, // Ignored for XYB
            optimize_huffman: true,
            downsampling_method: DownsamplingMethod::Box,
            use_xyb: true,
        },
    ]
}

// =============================================================================
// TESTS
// =============================================================================

/// Verify all configurations produce expected hashes.
/// This test is skipped until hashes are populated.
#[test]
fn test_frymire_hashes_locked() {
    if EXPECTED_HASHES.is_empty() {
        println!("No hashes configured yet. Run print_all_hashes to generate.");
        return;
    }

    let (rgb, width, height) = load_frymire();

    for (config_name, quality, expected_hash, expected_size) in EXPECTED_HASHES {
        let config = test_configs()
            .into_iter()
            .find(|c| c.name == *config_name)
            .expect("Unknown config");

        let jpeg = config.encode(&rgb, width, height, *quality as f32);
        let actual_hash = sha256_hex(&jpeg);

        assert_eq!(
            jpeg.len(),
            *expected_size,
            "{} Q{}: size mismatch!\n  expected: {} bytes\n  actual:   {} bytes",
            config_name,
            quality,
            expected_size,
            jpeg.len()
        );

        assert_eq!(
            actual_hash,
            *expected_hash,
            "{} Q{}: hash mismatch!\n  expected: {}\n  actual:   {}\n  size: {} bytes",
            config_name,
            quality,
            expected_hash,
            actual_hash,
            jpeg.len()
        );
    }
}

/// Test encoding with various configurations.
/// This verifies strip encoder parity without depending on specific hashes.
///
/// NOTE: Currently skips configs where frymire.png (1118x1105) doesn't align to MCU boundaries.
/// The full-plane encoder has edge padding, but the strip encoder doesn't yet.
/// - 4:4:4: MCU=8, partial cols=6, partial rows=1 -> SKIP
/// - 4:2:0/4:2:2/4:4:0: MCU=16, partial cols=14, partial rows=1 -> SKIP
///
/// TODO: Remove this skip once strip encoder has edge padding.
#[test]
fn test_frymire_backend_parity() {
    let (rgb, width, height) = load_frymire();

    // Test all configs that support strip encoding (baseline and progressive, including XYB)
    let strip_configs = test_configs();

    for config in &strip_configs {
        // Skip configs where dimensions don't align to MCU (strip encoder lacks edge padding)
        let mcu_size = config.mcu_size();
        if width as usize % mcu_size != 0 || height as usize % mcu_size != 0 {
            // Strip encoder doesn't have edge padding yet - skip non-aligned configs
            continue;
        }

        for &quality in &[50u8, 90] {
            // Use Both backend - will error if outputs differ
            let _jpeg = config.encode(&rgb, width, height, quality as f32);
        }
    }
}

// =============================================================================
// UTILITY: Generate hashes
// =============================================================================

/// Print all hashes for updating EXPECTED_HASHES.
/// Run with: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture
#[test]
#[ignore = "utility for generating hash values"]
fn print_all_hashes() {
    let (rgb, width, height) = load_frymire();
    println!("// frymire.png: {}x{}", width, height);
    println!("// Generated by: cargo test --release --test frymire_hash_locked print_all_hashes -- --ignored --nocapture");
    println!("// Format: (config_name, quality, sha256_hex, size_bytes)");
    println!();
    println!("const EXPECTED_HASHES: &[(&str, u8, &str, usize)] = &[");

    for config in test_configs() {
        for &quality in QUALITY_LEVELS {
            let jpeg = config.encode(&rgb, width, height, quality as f32);
            let hash = sha256_hex(&jpeg);
            println!(
                "    (\"{}\", {}, \"{}\", {}),",
                config.name,
                quality,
                hash,
                jpeg.len()
            );
        }
    }

    println!("];");
}

/// Print hash for a single configuration (for debugging).
#[test]
#[ignore = "utility"]
fn print_single_hash() {
    let (rgb, width, height) = load_frymire();

    let config = EncoderConfig::ycbcr(90.0, ChromaSubsampling::None).optimize_huffman(true);
    let mut enc = config
        .encode_from_bytes(width, height, PixelLayout::Rgb8Srgb)
        .expect("encoder setup");
    enc.push_packed(&rgb, enough::Unstoppable)
        .expect("push data");
    let jpeg = enc.finish().expect("Encoding failed");

    println!("Size: {} bytes", jpeg.len());
    println!("SHA256: {}", sha256_hex(&jpeg));
}
