//! SA-optimized piecewise quantization tables (v4).
//!
//! 20 quality-anchored quant table sets with linear interpolation between
//! anchors. Replaces the parametric `BASE_QUANT × distance_to_scale ×
//! GLOBAL_SCALE` formula with empirical per-coefficient data.
//!
//! # When to use
//!
//! - **Q1-Q99** when optimizing against butteraugli or ssimulacra2 on
//!   typical photographic content. Beats jpegli's algorithm-computed
//!   tables on 99/100 quality levels with mean pareto +6.602.
//! - **As `EncoderConfig::adaptive`'s default** for any cell where the
//!   metric matches the corpus the tables were tuned against.
//!
//! # When NOT to use
//!
//! - **Q100**: jpegli wins by 0.000 — flat tie. Use jpegli defaults.
//! - **Anything not photographic**: tables were tuned on CID22 photo
//!   content. Screenshots / illustrations may regress; rerun the
//!   piecewise optimizer on a matching corpus to generate a new table set.
//!
//! # Source
//!
//! Generated by coefficient's piecewise SA optimizer on **CID22-512
//! training (209 images)** with **GPU butteraugli** as the fitness
//! metric, jpegli encoder, 4:2:0 chroma. Mean pareto distance vs jpegli
//! defaults: **+6.602** training, **+6.09** holdout (41 unseen images).
//!
//! See `coefficient/docs/OPTIMIZATION_SPEC.md` §14 for the full validation
//! numbers and `coefficient/docs/PIECEWISE_TABLES_INTEGRATION.md` for the
//! integration plan that landed these constants here.
//!
//! Provenance: `/mnt/v/output/coefficient/piecewise/best_tables_v4.rs`
//! (also `combined_hybrid_v4.json` with per-anchor pareto/BPP/butter traces).
//!
//! Zero-bias is intentionally neutral here (`mul = 0`, `offset = 0`) — the
//! v4 SA run optimized only the quant tables. Joint zero-bias-per-anchor
//! optimization is M4 of the integration plan; until then, callers that
//! want jpegli's tuned zero-bias should fall back to non-piecewise tables.

use crate::encode::tuning::{EncodingTables, PerComponent, ScalingParams};

include!("sa_piecewise_v4_data.rs");

/// Find the bracketing anchor pair and interpolation weight `t`.
///
/// - Below the lowest anchor: `(0, 1, 0.0)` — clamps to anchor 0.
/// - Above the highest anchor: `(N-2, N-1, 1.0)` — clamps to anchor N-1.
/// - Between anchors `lo` and `hi`: `(lo, hi, t)` with `t ∈ (0.0, 1.0)`.
fn find_bracket(quality: u8) -> (usize, usize, f32) {
    let q = quality;
    let last = ANCHOR_COUNT - 1;

    if q <= ANCHOR_QUALITIES[0] {
        return (0, 1.min(last), 0.0);
    }
    if q >= ANCHOR_QUALITIES[last] {
        return (last.saturating_sub(1), last, 1.0);
    }

    let upper = ANCHOR_QUALITIES.partition_point(|&aq| aq < q).min(last);
    let lower = upper.saturating_sub(1);

    let lo_q = ANCHOR_QUALITIES[lower];
    let hi_q = ANCHOR_QUALITIES[upper];
    if lo_q == hi_q {
        return (lower, upper, 0.0);
    }
    let t = (q - lo_q) as f32 / (hi_q - lo_q) as f32;
    (lower, upper, t)
}

fn lerp_table(a: &[u16; 64], b: &[u16; 64], t: f32) -> [f32; 64] {
    let mut out = [0.0f32; 64];
    for i in 0..64 {
        out[i] = a[i] as f32 * (1.0 - t) + b[i] as f32 * t;
    }
    out
}

/// Build [`EncodingTables`] for the given quality level (1-100).
///
/// Uses linear interpolation between bracketing anchor tables. Values
/// outside Q5-Q100 are clamped to the nearest anchor.
///
/// Returns tables with [`ScalingParams::Exact`] (jpegli's distance-to-scale
/// formula is bypassed) and neutral zero-bias (the v4 SA run held zero-bias
/// fixed; M4 of the integration plan adds zero-bias-per-anchor SA).
#[must_use]
pub fn tables_for_quality(quality: u8) -> EncodingTables {
    let (lo, hi, t) = find_bracket(quality);
    let luma = lerp_table(&ANCHOR_LUMA[lo], &ANCHOR_LUMA[hi], t);
    let cb = lerp_table(&ANCHOR_CB[lo], &ANCHOR_CB[hi], t);
    let cr = lerp_table(&ANCHOR_CR[lo], &ANCHOR_CR[hi], t);

    let zero_mul = [0.0f32; 64];
    EncodingTables {
        quant: PerComponent {
            c0: luma,
            c1: cb,
            c2: cr,
        },
        zero_bias_mul: PerComponent {
            c0: zero_mul,
            c1: zero_mul,
            c2: zero_mul,
        },
        zero_bias_offset_dc: [0.0; 3],
        zero_bias_offset_ac: [0.0; 3],
        scaling: ScalingParams::Exact,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn anchor_array_sizes_match() {
        assert_eq!(ANCHOR_QUALITIES.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_LUMA.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_CB.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_CR.len(), ANCHOR_COUNT);
    }

    #[test]
    fn anchor_qualities_sorted_strictly_ascending() {
        for w in ANCHOR_QUALITIES.windows(2) {
            assert!(
                w[0] < w[1],
                "anchors not strictly ascending: {} >= {}",
                w[0],
                w[1]
            );
        }
    }

    #[test]
    fn anchor_values_are_valid_u16_quant() {
        // Quant entries should fit in u16 and be at least 1 (enforced by
        // jpegli encoder; lerp_u16 in coefficient also clamps to [1, 255]).
        for tab in ANCHOR_LUMA
            .iter()
            .chain(ANCHOR_CB.iter())
            .chain(ANCHOR_CR.iter())
        {
            for &v in tab.iter() {
                assert!(v >= 1, "quant value < 1: {}", v);
                assert!(v <= 255, "quant value > 255: {}", v);
            }
        }
    }

    #[test]
    fn find_bracket_at_anchors() {
        // First anchor: lo=0, hi=1, t=0
        let (lo, hi, t) = find_bracket(ANCHOR_QUALITIES[0]);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        assert!(t.abs() < 1e-6);

        // Last anchor: lo=N-2, hi=N-1, t=1
        let (lo, hi, t) = find_bracket(ANCHOR_QUALITIES[ANCHOR_COUNT - 1]);
        assert_eq!(lo, ANCHOR_COUNT - 2);
        assert_eq!(hi, ANCHOR_COUNT - 1);
        assert!((t - 1.0).abs() < 1e-6);
    }

    #[test]
    fn find_bracket_midpoint() {
        // Anchors are at q5, q10, q15, ... so q7 is between q5 (idx 0) and q10 (idx 1).
        let (lo, hi, t) = find_bracket(7);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        // (7 - 5) / (10 - 5) = 0.4
        assert!((t - 0.4).abs() < 1e-3);
    }

    #[test]
    fn find_bracket_below_first_clamps() {
        let (lo, hi, t) = find_bracket(1);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        assert!(t.abs() < 1e-6);
    }

    #[test]
    fn find_bracket_above_last_clamps() {
        // ANCHOR_QUALITIES[last] is 100; >100 isn't valid u8 quality but defends the boundary.
        let (lo, hi, t) = find_bracket(100);
        assert_eq!(lo, ANCHOR_COUNT - 2);
        assert_eq!(hi, ANCHOR_COUNT - 1);
        assert!((t - 1.0).abs() < 1e-6);
    }

    #[test]
    fn tables_for_quality_uses_exact_scaling() {
        let tables = tables_for_quality(50);
        assert!(matches!(tables.scaling, ScalingParams::Exact));
    }

    #[test]
    fn tables_for_quality_neutral_zero_bias() {
        let tables = tables_for_quality(50);
        for c in [
            &tables.zero_bias_mul.c0,
            &tables.zero_bias_mul.c1,
            &tables.zero_bias_mul.c2,
        ] {
            for &v in c.iter() {
                assert_eq!(v, 0.0);
            }
        }
        for &v in tables
            .zero_bias_offset_dc
            .iter()
            .chain(tables.zero_bias_offset_ac.iter())
        {
            assert_eq!(v, 0.0);
        }
    }

    #[test]
    fn tables_for_quality_at_anchor_returns_anchor_data() {
        // Q5 is anchor 0 → c0 should equal ANCHOR_LUMA[0] (cast to f32).
        let tables = tables_for_quality(5);
        for i in 0..64 {
            assert!((tables.quant.c0[i] - ANCHOR_LUMA[0][i] as f32).abs() < 1e-3);
            assert!((tables.quant.c1[i] - ANCHOR_CB[0][i] as f32).abs() < 1e-3);
            assert!((tables.quant.c2[i] - ANCHOR_CR[0][i] as f32).abs() < 1e-3);
        }
    }

    #[test]
    fn tables_for_quality_interpolates_between_anchors() {
        let lo_q = ANCHOR_QUALITIES[0];
        let hi_q = ANCHOR_QUALITIES[1];
        let mid_q = lo_q + (hi_q - lo_q) / 2;
        let mid = tables_for_quality(mid_q);

        // Each f32 should be between the two anchors at the same index.
        for i in 0..64 {
            let lo_v = ANCHOR_LUMA[0][i] as f32;
            let hi_v = ANCHOR_LUMA[1][i] as f32;
            let (min_v, max_v) = if lo_v < hi_v {
                (lo_v, hi_v)
            } else {
                (hi_v, lo_v)
            };
            assert!(mid.quant.c0[i] >= min_v - 0.01);
            assert!(mid.quant.c0[i] <= max_v + 0.01);
        }
    }
}
