//! SA-optimized piecewise quantization tables (v4), monotonized.
//!
//! 20 quality-anchored quant table sets with linear interpolation between
//! anchors. Replaces the parametric `BASE_QUANT × distance_to_scale ×
//! GLOBAL_SCALE` formula with empirical per-coefficient data.
//!
//! # Monotonicity (issue #12)
//!
//! The raw v4 anchors were SA-optimized **independently per quality**, so
//! each landed in its own local optimum and the per-cell sequence across
//! anchors was not monotone — e.g. raw luma DC q90=5, q95=37, q100=6, and
//! raw Cb DC q100=81, coarser than q5's 66. Lerping between such anchors
//! made file size wobble with quality (34 size-monotonicity violations
//! q1–q99 on a 512² noise+patches image vs 0 for the jpegli tables).
//!
//! The public `ANCHOR_*` tables are therefore the raw anchors passed
//! through [`monotonize`]: an L2 isotonic regression (pool-adjacent-
//! violators) per coefficient position across the 20 anchors, enforcing
//! **non-increasing quant values as quality rises**. It runs at compile
//! time, so `tables_for_quality` stays a pure lerp. The raw data is kept
//! in `sa_piecewise_v4_data.rs` as `RAW_ANCHOR_*` (provenance + the
//! mutation baseline for the monotonicity gates).
//!
//! **The pareto figures below were measured on the RAW anchors and have
//! NOT been re-measured after smoothing.** Treat them as the provenance of
//! the data, not as a claim about the tables this module ships.
//!
//! # When to use
//!
//! - **Q1-Q99** when optimizing against butteraugli or ssimulacra2 on
//!   typical photographic content, and only after re-validating on your
//!   corpus — the raw anchors beat jpegli's algorithm-computed tables on
//!   99/100 quality levels (mean pareto +6.602) but the shipped,
//!   monotonized tables carry no measured claim yet.
//!
//! # When NOT to use
//!
//! - **As a default**: `QuantTableConfig::default()` is Jpegli, and this
//!   family should stay opt-in until the smoothed tables are re-validated.
//! - **Q100**: jpegli wins by 0.000 — flat tie. Use jpegli defaults.
//! - **Anything not photographic**: tables were tuned on CID22 photo
//!   content. Screenshots / illustrations may regress; rerun the
//!   piecewise optimizer on a matching corpus to generate a new table set.
//!
//! # Source
//!
//! Raw anchors generated by coefficient's piecewise SA optimizer on
//! **CID22-512 training (209 images)** with **GPU butteraugli** as the
//! fitness metric, jpegli encoder, 4:2:0 chroma. Mean pareto distance vs
//! jpegli defaults (RAW anchors): **+6.602** training, **+6.09** holdout
//! (41 unseen images).
//!
//! See `coefficient/docs/OPTIMIZATION_SPEC.md` §14 for the full validation
//! numbers and `coefficient/docs/PIECEWISE_TABLES_INTEGRATION.md` for the
//! integration plan that landed these constants here.
//!
//! Provenance: `/mnt/v/output/coefficient/piecewise/best_tables_v4.rs`
//! (also `combined_hybrid_v4.json` with per-anchor pareto/BPP/butter traces).
//!
//! Zero-bias is intentionally neutral here (`mul = 0`, `offset = 0`) — the
//! v4 SA run optimized only the quant tables. Joint zero-bias-per-anchor
//! optimization is M4 of the integration plan; until then, callers that
//! want jpegli's tuned zero-bias should fall back to non-piecewise tables.

use crate::encode::tuning::{EncodingTables, PerComponent, ScalingParams};

include!("sa_piecewise_v4_data.rs");

/// LUMA anchors, monotonized (see module docs / [`monotonize`]).
pub const ANCHOR_LUMA: [[u16; 64]; ANCHOR_COUNT] = monotonize(&RAW_ANCHOR_LUMA);
/// CB anchors, monotonized.
pub const ANCHOR_CB: [[u16; 64]; ANCHOR_COUNT] = monotonize(&RAW_ANCHOR_CB);
/// CR anchors, monotonized.
pub const ANCHOR_CR: [[u16; 64]; ANCHOR_COUNT] = monotonize(&RAW_ANCHOR_CR);

/// L2 isotonic regression (pool-adjacent-violators) of one anchor sequence
/// under the constraint "non-increasing in anchor index" — i.e. a quant
/// value may not get coarser as quality rises. Each pooled block takes the
/// (rounded-to-nearest) mean of its members, which is the least-squares
/// monotone fit; rounding a monotone real sequence keeps it monotone.
///
/// `const fn` so the smoothing costs nothing at runtime.
const fn pav_non_increasing(v: [u16; ANCHOR_COUNT]) -> [u16; ANCHOR_COUNT] {
    // Blocks of pooled anchors: sum + length. At most ANCHOR_COUNT blocks.
    let mut sum = [0u32; ANCHOR_COUNT];
    let mut len = [0u32; ANCHOR_COUNT];
    let mut nb = 0usize;
    let mut i = 0usize;
    while i < ANCHOR_COUNT {
        sum[nb] = v[i] as u32;
        len[nb] = 1;
        nb += 1;
        // Non-increasing means mean(prev) >= mean(cur). While the previous
        // block's mean is SMALLER than the current one's, pool them.
        // mean(prev) < mean(cur)  <=>  sum_prev * len_cur < sum_cur * len_prev.
        while nb > 1 && sum[nb - 2] * len[nb - 1] < sum[nb - 1] * len[nb - 2] {
            sum[nb - 2] += sum[nb - 1];
            len[nb - 2] += len[nb - 1];
            nb -= 1;
        }
        i += 1;
    }
    // Expand blocks back to per-anchor values (round half up).
    let mut out = [0u16; ANCHOR_COUNT];
    let mut b = 0usize;
    let mut k = 0usize;
    while b < nb {
        let mean = (2 * sum[b] + len[b]) / (2 * len[b]);
        let mut j = 0u32;
        while j < len[b] {
            out[k] = mean as u16;
            k += 1;
            j += 1;
        }
        b += 1;
    }
    out
}

/// Apply [`pav_non_increasing`] to every coefficient position of an anchor
/// table set. Output has the same shape; every column (fixed zigzag/raster
/// index, anchor index rising) is non-increasing.
const fn monotonize(raw: &[[u16; 64]; ANCHOR_COUNT]) -> [[u16; 64]; ANCHOR_COUNT] {
    let mut out = [[0u16; 64]; ANCHOR_COUNT];
    let mut pos = 0usize;
    while pos < 64 {
        let mut col = [0u16; ANCHOR_COUNT];
        let mut a = 0usize;
        while a < ANCHOR_COUNT {
            col[a] = raw[a][pos];
            a += 1;
        }
        let fit = pav_non_increasing(col);
        let mut a = 0usize;
        while a < ANCHOR_COUNT {
            out[a][pos] = fit[a];
            a += 1;
        }
        pos += 1;
    }
    out
}

/// Find the bracketing anchor pair and interpolation weight `t`.
///
/// - Below the lowest anchor: `(0, 1, 0.0)` — clamps to anchor 0.
/// - Above the highest anchor: `(N-2, N-1, 1.0)` — clamps to anchor N-1.
/// - Between anchors `lo` and `hi`: `(lo, hi, t)` with `t ∈ (0.0, 1.0)`.
fn find_bracket(quality: u8) -> (usize, usize, f32) {
    let q = quality;
    let last = ANCHOR_COUNT - 1;

    if q <= ANCHOR_QUALITIES[0] {
        return (0, 1.min(last), 0.0);
    }
    if q >= ANCHOR_QUALITIES[last] {
        return (last.saturating_sub(1), last, 1.0);
    }

    let upper = ANCHOR_QUALITIES.partition_point(|&aq| aq < q).min(last);
    let lower = upper.saturating_sub(1);

    let lo_q = ANCHOR_QUALITIES[lower];
    let hi_q = ANCHOR_QUALITIES[upper];
    if lo_q == hi_q {
        return (lower, upper, 0.0);
    }
    let t = (q - lo_q) as f32 / (hi_q - lo_q) as f32;
    (lower, upper, t)
}

fn lerp_table(a: &[u16; 64], b: &[u16; 64], t: f32) -> [f32; 64] {
    let mut out = [0.0f32; 64];
    for i in 0..64 {
        out[i] = a[i] as f32 * (1.0 - t) + b[i] as f32 * t;
    }
    out
}

/// Build [`EncodingTables`] for the given quality level (1-100).
///
/// Uses linear interpolation between bracketing anchor tables. Values
/// outside Q5-Q100 are clamped to the nearest anchor.
///
/// Returns tables with [`ScalingParams::Exact`] (jpegli's distance-to-scale
/// formula is bypassed) and neutral zero-bias (the v4 SA run held zero-bias
/// fixed; M4 of the integration plan adds zero-bias-per-anchor SA).
#[must_use]
pub fn tables_for_quality(quality: u8) -> EncodingTables {
    let (lo, hi, t) = find_bracket(quality);
    let luma = lerp_table(&ANCHOR_LUMA[lo], &ANCHOR_LUMA[hi], t);
    let cb = lerp_table(&ANCHOR_CB[lo], &ANCHOR_CB[hi], t);
    let cr = lerp_table(&ANCHOR_CR[lo], &ANCHOR_CR[hi], t);

    let zero_mul = [0.0f32; 64];
    EncodingTables {
        quant: PerComponent {
            c0: luma,
            c1: cb,
            c2: cr,
        },
        zero_bias_mul: PerComponent {
            c0: zero_mul,
            c1: zero_mul,
            c2: zero_mul,
        },
        zero_bias_offset_dc: [0.0; 3],
        zero_bias_offset_ac: [0.0; 3],
        scaling: ScalingParams::Exact,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Count `(position, anchor k)` cells where anchor k+1 quantizes
    /// COARSER than anchor k — the defect #12 is about.
    fn monotonicity_violations(tables: &[[u16; 64]; ANCHOR_COUNT]) -> usize {
        let mut n = 0;
        for pos in 0..64 {
            for k in 0..ANCHOR_COUNT - 1 {
                if tables[k + 1][pos] > tables[k][pos] {
                    n += 1;
                }
            }
        }
        n
    }

    #[test]
    fn raw_anchors_are_non_monotone_so_the_smoothing_is_load_bearing() {
        // The mutation baseline: if this ever passes with zero violations,
        // the raw data was regenerated monotone and `monotonize` is a no-op.
        let raw = monotonicity_violations(&RAW_ANCHOR_LUMA)
            + monotonicity_violations(&RAW_ANCHOR_CB)
            + monotonicity_violations(&RAW_ANCHOR_CR);
        assert!(raw > 0, "raw v4 anchors are already monotone");
        // The headline offenders from #12, read from the raw data.
        assert_eq!(RAW_ANCHOR_LUMA[17][0], 5, "raw luma DC q90");
        assert_eq!(RAW_ANCHOR_LUMA[18][0], 37, "raw luma DC q95");
        assert_eq!(RAW_ANCHOR_LUMA[19][0], 6, "raw luma DC q100");
    }

    #[test]
    fn shipped_anchors_are_non_increasing_per_cell() {
        for (name, tables) in [
            ("luma", &ANCHOR_LUMA),
            ("cb", &ANCHOR_CB),
            ("cr", &ANCHOR_CR),
        ] {
            assert_eq!(
                monotonicity_violations(tables),
                0,
                "{name}: a quant value gets coarser as quality rises"
            );
        }
        // And the #12 headline cells specifically: q95 no longer coarser
        // than q90 / q100 on luma DC, q100 Cb DC no longer coarser than q5.
        assert!(ANCHOR_LUMA[18][0] <= ANCHOR_LUMA[17][0]);
        assert!(ANCHOR_LUMA[19][0] <= ANCHOR_LUMA[18][0]);
        assert!(ANCHOR_CB[19][0] <= ANCHOR_CB[0][0]);
    }

    #[test]
    fn pav_matches_hand_computed_isotonic_fits() {
        // Pad to ANCHOR_COUNT with a trailing run of 1s (already monotone).
        fn seq(prefix: &[u16]) -> [u16; ANCHOR_COUNT] {
            let mut v = [1u16; ANCHOR_COUNT];
            v[..prefix.len()].copy_from_slice(prefix);
            v
        }
        // Already non-increasing: identity.
        assert_eq!(
            pav_non_increasing(seq(&[9, 7, 7, 3, 1])),
            seq(&[9, 7, 7, 3, 1])
        );
        // The #12 luma DC tail (5, 37, 6): 5<37 pools to mean 21; 21>=6 ok.
        assert_eq!(pav_non_increasing(seq(&[5, 37, 6])), seq(&[21, 21, 6]));
        // Cascading pool: 10, 20, 30 all violate -> one block, mean 20.
        assert_eq!(pav_non_increasing(seq(&[10, 20, 30])), seq(&[20, 20, 20]));
        // Rounding half up: (3 + 4) / 2 = 3.5 -> 4.
        let out = pav_non_increasing(seq(&[3, 4]));
        assert_eq!(out[0], 4);
        assert_eq!(out[1], 4);
        // Output never leaves [min, max] of the input and is monotone.
        let out = pav_non_increasing(seq(&[15, 15, 28, 20, 24, 12, 14, 18, 23, 26, 30, 12]));
        for w in out.windows(2) {
            assert!(w[0] >= w[1], "{out:?} not non-increasing");
        }
        assert!(out.iter().all(|&x| (1..=30).contains(&x)));
    }

    #[test]
    fn monotonize_is_idempotent_and_preserves_u8_range() {
        let again = monotonize(&ANCHOR_LUMA);
        assert_eq!(
            again, ANCHOR_LUMA,
            "monotonize must be a no-op on its own output"
        );
        for tab in ANCHOR_LUMA
            .iter()
            .chain(ANCHOR_CB.iter())
            .chain(ANCHOR_CR.iter())
        {
            for &v in tab {
                assert!((1..=255).contains(&v));
            }
        }
    }

    #[test]
    fn tables_for_quality_is_non_increasing_over_the_whole_q_range() {
        let mut prev = tables_for_quality(1);
        for q in 2..=100u8 {
            let cur = tables_for_quality(q);
            for (name, a, b) in [
                ("luma", &prev.quant.c0, &cur.quant.c0),
                ("cb", &prev.quant.c1, &cur.quant.c1),
                ("cr", &prev.quant.c2, &cur.quant.c2),
            ] {
                for i in 0..64 {
                    assert!(
                        b[i] <= a[i] + 1e-4,
                        "{name} pos {i}: q{q} ({}) coarser than q{} ({})",
                        b[i],
                        q - 1,
                        a[i]
                    );
                }
            }
            prev = cur;
        }
    }

    #[test]
    fn anchor_array_sizes_match() {
        assert_eq!(ANCHOR_QUALITIES.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_LUMA.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_CB.len(), ANCHOR_COUNT);
        assert_eq!(ANCHOR_CR.len(), ANCHOR_COUNT);
    }

    #[test]
    fn anchor_qualities_sorted_strictly_ascending() {
        for w in ANCHOR_QUALITIES.windows(2) {
            assert!(
                w[0] < w[1],
                "anchors not strictly ascending: {} >= {}",
                w[0],
                w[1]
            );
        }
    }

    #[test]
    fn anchor_values_are_valid_u16_quant() {
        // Quant entries should fit in u16 and be at least 1 (enforced by
        // jpegli encoder; lerp_u16 in coefficient also clamps to [1, 255]).
        for tab in ANCHOR_LUMA
            .iter()
            .chain(ANCHOR_CB.iter())
            .chain(ANCHOR_CR.iter())
        {
            for &v in tab.iter() {
                assert!(v >= 1, "quant value < 1: {}", v);
                assert!(v <= 255, "quant value > 255: {}", v);
            }
        }
    }

    #[test]
    fn find_bracket_at_anchors() {
        // First anchor: lo=0, hi=1, t=0
        let (lo, hi, t) = find_bracket(ANCHOR_QUALITIES[0]);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        assert!(t.abs() < 1e-6);

        // Last anchor: lo=N-2, hi=N-1, t=1
        let (lo, hi, t) = find_bracket(ANCHOR_QUALITIES[ANCHOR_COUNT - 1]);
        assert_eq!(lo, ANCHOR_COUNT - 2);
        assert_eq!(hi, ANCHOR_COUNT - 1);
        assert!((t - 1.0).abs() < 1e-6);
    }

    #[test]
    fn find_bracket_midpoint() {
        // Anchors are at q5, q10, q15, ... so q7 is between q5 (idx 0) and q10 (idx 1).
        let (lo, hi, t) = find_bracket(7);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        // (7 - 5) / (10 - 5) = 0.4
        assert!((t - 0.4).abs() < 1e-3);
    }

    #[test]
    fn find_bracket_below_first_clamps() {
        let (lo, hi, t) = find_bracket(1);
        assert_eq!(lo, 0);
        assert_eq!(hi, 1);
        assert!(t.abs() < 1e-6);
    }

    #[test]
    fn find_bracket_above_last_clamps() {
        // ANCHOR_QUALITIES[last] is 100; >100 isn't valid u8 quality but defends the boundary.
        let (lo, hi, t) = find_bracket(100);
        assert_eq!(lo, ANCHOR_COUNT - 2);
        assert_eq!(hi, ANCHOR_COUNT - 1);
        assert!((t - 1.0).abs() < 1e-6);
    }

    #[test]
    fn tables_for_quality_uses_exact_scaling() {
        let tables = tables_for_quality(50);
        assert!(matches!(tables.scaling, ScalingParams::Exact));
    }

    #[test]
    fn tables_for_quality_neutral_zero_bias() {
        let tables = tables_for_quality(50);
        for c in [
            &tables.zero_bias_mul.c0,
            &tables.zero_bias_mul.c1,
            &tables.zero_bias_mul.c2,
        ] {
            for &v in c.iter() {
                assert_eq!(v, 0.0);
            }
        }
        for &v in tables
            .zero_bias_offset_dc
            .iter()
            .chain(tables.zero_bias_offset_ac.iter())
        {
            assert_eq!(v, 0.0);
        }
    }

    #[test]
    fn tables_for_quality_at_anchor_returns_anchor_data() {
        // Q5 is anchor 0 → c0 should equal ANCHOR_LUMA[0] (cast to f32).
        let tables = tables_for_quality(5);
        for i in 0..64 {
            assert!((tables.quant.c0[i] - ANCHOR_LUMA[0][i] as f32).abs() < 1e-3);
            assert!((tables.quant.c1[i] - ANCHOR_CB[0][i] as f32).abs() < 1e-3);
            assert!((tables.quant.c2[i] - ANCHOR_CR[0][i] as f32).abs() < 1e-3);
        }
    }

    #[test]
    fn tables_for_quality_interpolates_between_anchors() {
        let lo_q = ANCHOR_QUALITIES[0];
        let hi_q = ANCHOR_QUALITIES[1];
        let mid_q = lo_q + (hi_q - lo_q) / 2;
        let mid = tables_for_quality(mid_q);

        // Each f32 should be between the two anchors at the same index.
        for i in 0..64 {
            let lo_v = ANCHOR_LUMA[0][i] as f32;
            let hi_v = ANCHOR_LUMA[1][i] as f32;
            let (min_v, max_v) = if lo_v < hi_v {
                (lo_v, hi_v)
            } else {
                (hi_v, lo_v)
            };
            assert!(mid.quant.c0[i] >= min_v - 0.01);
            assert!(mid.quant.c0[i] <= max_v + 0.01);
        }
    }
}
