#!/usr/bin/env python3
"""Fit per-encoder × per-strategy achieved-quality + size-ratio tables.

Reads forced-strategy recompress-sweep TSVs and emits the Rust constant
block that lives between the `=== BEGIN/END GENERATED TABLES ===` markers
in `zenjpeg-recompress/src/calibration/per_encoder.rs`.

Input: a directory containing, for each encoder in {turbo, mozjpeg,
jpegli} and each strategy in {preserve, tuned}, a file named
`<strategy>_<encoder>.tsv` (the output of
`zjr-calibrate recompress-sweep --force-strategy <strategy>`).

Usage:
    fit_per_encoder.py <sweep_dir> <date> > generated_tables.rs

Then `recalibrate.sh` splices the output between the markers.
"""

import csv
import statistics
import sys
from collections import defaultdict

SRC = [40, 50, 60, 70, 80, 90]      # source-estimate zensim-A buckets
TGT = [30, 40, 50, 60, 70, 80]      # target zensim-A grid
ENCODERS = ["turbo", "mozjpeg", "jpegli"]
STRATEGIES = ["preserve", "tuned"]


def nearest(v, arr):
    return min(arr, key=lambda a: abs(a - v))


def fit(path):
    """Return (achieved, ratio) dicts keyed (src_bucket, target)."""
    ach, rat = defaultdict(list), defaultdict(list)
    try:
        rows = list(csv.DictReader(open(path), delimiter="\t"))
    except FileNotFoundError:
        return ach, rat
    for r in rows:
        if r.get("zensim_a_vs_reference", "-") in ("-", ""):
            continue
        s = nearest(float(r["source_estimated_zensim_a"]), SRC)
        t = nearest(float(r["target_zensim_a"]), TGT)
        ach[(s, t)].append(float(r["zensim_a_vs_reference"]))
        rat[(s, t)].append(float(r["size_ratio"]))
    return ach, rat


def emit_table(name, data, fmt):
    print("#[rustfmt::skip]")
    print(f"pub const {name}: &[[f32; 6]; 6] = &[")
    for s in SRC:
        cells = []
        for t in TGT:
            v = data.get((s, t))
            cells.append(fmt.format(statistics.median(v)) if v else "f32::NAN")
        print("    [" + ", ".join(cells) + "],")
    print("];")


def corpus_size(sweep_dir):
    """Distinct reference images in the sweep (proxy for corpus size)."""
    refs = set()
    for enc in ENCODERS:
        for strat in STRATEGIES:
            try:
                for r in csv.DictReader(
                    open(f"{sweep_dir}/{strat}_{enc}.tsv"), delimiter="\t"
                ):
                    refs.add(r.get("reference_id", ""))
            except FileNotFoundError:
                pass
    refs.discard("")
    return len(refs)


def main(sweep_dir, date):
    n = corpus_size(sweep_dir)
    print("// === BEGIN GENERATED TABLES ===")
    print("// Everything between the BEGIN/END markers is regenerated by")
    print("// `scripts/fit_per_encoder.py` (driven by `scripts/recalibrate.sh`).")
    print("// Do not edit by hand — edit the fitter / re-run the sweep instead.")
    print(f"// Auto-generated {date} from forced-strategy recompress-sweeps")
    print("//  on pinned libjpeg-turbo + mozjpeg + jpegli, HybridMaxCompression.")
    print(f"//  Corpus: {n} CID22-512 references × 16 source-q (q20-95 step 5).")
    print("//  Each cell is the MEDIAN over all (image, source-q) pairs whose")
    print("//  source-estimate / target fall in that bucket.")
    print("//  Rows = source-estimate zensim-A bucket [40,50,60,70,80,90];")
    print("//  cols = target [30,40,50,60,70,80].")
    print(f"pub const PE_SRC_BUCKETS: &[f32] = &{[float(s) for s in SRC]!r};")
    print(f"pub const PE_TARGETS: &[f32] = &{[float(t) for t in TGT]!r};")
    for enc in ENCODERS:
        for strat in STRATEGIES:
            ach, rat = fit(f"{sweep_dir}/{strat}_{enc}.tsv")
            base = f"{enc.upper()}_{strat.upper()}"
            emit_table(f"{base}_ACHIEVED", ach, "{:.1f}")
            emit_table(f"{base}_RATIO", rat, "{:.4f}")
    print("// === END GENERATED TABLES ===")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
