//! FFI bindings to jpegli C++ for comparison testing.
//!
//! This crate provides raw FFI bindings to the C++ jpegli library
//! for testing the Rust port against the original implementation.
//!
//! jpegli exposes a libjpeg-62 compatible API.
//!
//! NOTE: These bindings were generated with bindgen from the actual jpegli headers
//! to ensure struct layout compatibility.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::upper_case_acronyms)]

use libc::{c_char, c_int, c_long, c_uchar, c_uint, c_ulong, c_void, size_t};

// ============================================================================
// libjpeg-62 compatible types (generated by bindgen)
// ============================================================================

pub const JPEG_LIB_VERSION: u32 = 62;
pub const DCTSIZE: u32 = 8;
pub const DCTSIZE2: u32 = 64;
pub const JCS_EXTENSIONS: u32 = 1;
pub const JCS_ALPHA_EXTENSIONS: u32 = 1;
pub const NUM_QUANT_TBLS: usize = 4;
pub const NUM_HUFF_TBLS: usize = 4;
pub const NUM_ARITH_TBLS: usize = 16;
pub const MAX_COMPS_IN_SCAN: usize = 4;
pub const C_MAX_BLOCKS_IN_MCU: usize = 10;
pub const D_MAX_BLOCKS_IN_MCU: usize = 10;

// Color space constants
pub const JCS_UNKNOWN: c_int = 0;
pub const JCS_GRAYSCALE: c_int = 1;
pub const JCS_RGB: c_int = 2;
pub const JCS_YCbCr: c_int = 3;
pub const JCS_CMYK: c_int = 4;
pub const JCS_YCCK: c_int = 5;
pub const JCS_EXT_RGB: c_int = 6;
pub const JCS_EXT_RGBX: c_int = 7;
pub const JCS_EXT_BGR: c_int = 8;
pub const JCS_EXT_BGRX: c_int = 9;
pub const JCS_EXT_XBGR: c_int = 10;
pub const JCS_EXT_XRGB: c_int = 11;
pub const JCS_EXT_RGBA: c_int = 12;
pub const JCS_EXT_BGRA: c_int = 13;
pub const JCS_EXT_ABGR: c_int = 14;
pub const JCS_EXT_ARGB: c_int = 15;
pub const JCS_RGB565: c_int = 16;

// DCT method constants
pub const JDCT_ISLOW: c_int = 0;
pub const JDCT_IFAST: c_int = 1;
pub const JDCT_FLOAT: c_int = 2;

// Basic types
pub type JSAMPLE = c_uchar;
pub type JCOEF = c_short;
pub type JOCTET = c_uchar;
pub type UINT8 = c_uchar;
pub type UINT16 = c_ushort;
pub type JDIMENSION = c_uint;
pub type boolean = c_int;
pub type c_short = i16;
pub type c_ushort = u16;

// Pointer types
pub type JSAMPROW = *mut JSAMPLE;
pub type JSAMPARRAY = *mut JSAMPROW;
pub type JSAMPIMAGE = *mut JSAMPARRAY;
pub type JBLOCK = [JCOEF; 64usize];
pub type JBLOCKROW = *mut JBLOCK;
pub type JBLOCKARRAY = *mut JBLOCKROW;

pub type J_COLOR_SPACE = c_uint;
pub type J_DCT_METHOD = c_uint;
pub type J_DITHER_MODE = c_uint;

// ============================================================================
// Structs (correct layout for JPEG_LIB_VERSION 62)
// ============================================================================

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JQUANT_TBL {
    pub quantval: [UINT16; 64usize],
    pub sent_table: boolean,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JHUFF_TBL {
    pub bits: [UINT8; 17usize],
    pub huffval: [UINT8; 256usize],
    pub sent_table: boolean,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_component_info {
    pub component_id: c_int,
    pub component_index: c_int,
    pub h_samp_factor: c_int,
    pub v_samp_factor: c_int,
    pub quant_tbl_no: c_int,
    pub dc_tbl_no: c_int,
    pub ac_tbl_no: c_int,
    pub width_in_blocks: JDIMENSION,
    pub height_in_blocks: JDIMENSION,
    pub DCT_scaled_size: c_int, // NOTE: v62 has this, not DCT_h/v_scaled_size
    pub downsampled_width: JDIMENSION,
    pub downsampled_height: JDIMENSION,
    pub component_needed: boolean,
    pub MCU_width: c_int,
    pub MCU_height: c_int,
    pub MCU_blocks: c_int,
    pub MCU_sample_width: c_int,
    pub last_col_width: c_int,
    pub last_row_height: c_int,
    pub quant_table: *mut JQUANT_TBL,
    pub dct_table: *mut c_void,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_scan_info {
    pub comps_in_scan: c_int,
    pub component_index: [c_int; 4usize],
    pub Ss: c_int,
    pub Se: c_int,
    pub Ah: c_int,
    pub Al: c_int,
}

pub type jpeg_saved_marker_ptr = *mut jpeg_marker_struct;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_marker_struct {
    pub next: jpeg_saved_marker_ptr,
    pub marker: UINT8,
    pub original_length: c_uint,
    pub data_length: c_uint,
    pub data: *mut JOCTET,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_common_struct {
    pub err: *mut jpeg_error_mgr,
    pub mem: *mut jpeg_memory_mgr,
    pub progress: *mut jpeg_progress_mgr,
    pub client_data: *mut c_void,
    pub is_decompressor: boolean,
    pub global_state: c_int,
}

pub type j_common_ptr = *mut jpeg_common_struct;
pub type j_compress_ptr = *mut jpeg_compress_struct;
pub type j_decompress_ptr = *mut jpeg_decompress_struct;

/// Compression struct - matches jpegli's JPEG_LIB_VERSION 62 layout exactly
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_compress_struct {
    // Common fields (24 bytes on 64-bit)
    pub err: *mut jpeg_error_mgr,
    pub mem: *mut jpeg_memory_mgr,
    pub progress: *mut jpeg_progress_mgr,
    pub client_data: *mut c_void,
    pub is_decompressor: boolean,
    pub global_state: c_int,
    // Destination
    pub dest: *mut jpeg_destination_mgr,
    // Image info
    pub image_width: JDIMENSION,
    pub image_height: JDIMENSION,
    pub input_components: c_int,
    pub in_color_space: J_COLOR_SPACE,
    pub input_gamma: f64,
    // Compression parameters
    pub data_precision: c_int,
    pub num_components: c_int,
    pub jpeg_color_space: J_COLOR_SPACE,
    pub comp_info: *mut jpeg_component_info,
    pub quant_tbl_ptrs: [*mut JQUANT_TBL; 4usize],
    pub dc_huff_tbl_ptrs: [*mut JHUFF_TBL; 4usize],
    pub ac_huff_tbl_ptrs: [*mut JHUFF_TBL; 4usize],
    pub arith_dc_L: [UINT8; 16usize],
    pub arith_dc_U: [UINT8; 16usize],
    pub arith_ac_K: [UINT8; 16usize],
    pub num_scans: c_int,
    pub scan_info: *const jpeg_scan_info,
    pub raw_data_in: boolean,
    pub arith_code: boolean,
    pub optimize_coding: boolean,
    pub CCIR601_sampling: boolean,
    pub smoothing_factor: c_int,
    pub dct_method: J_DCT_METHOD,
    pub restart_interval: c_uint,
    pub restart_in_rows: c_int,
    // JFIF/Adobe markers
    pub write_JFIF_header: boolean,
    pub JFIF_major_version: UINT8,
    pub JFIF_minor_version: UINT8,
    pub density_unit: UINT8,
    pub X_density: UINT16,
    pub Y_density: UINT16,
    pub write_Adobe_marker: boolean,
    // State variables
    pub next_scanline: JDIMENSION,
    pub progressive_mode: boolean,
    pub max_h_samp_factor: c_int,
    pub max_v_samp_factor: c_int,
    pub total_iMCU_rows: JDIMENSION,
    pub comps_in_scan: c_int,
    pub cur_comp_info: [*mut jpeg_component_info; 4usize],
    pub MCUs_per_row: JDIMENSION,
    pub MCU_rows_in_scan: JDIMENSION,
    pub blocks_in_MCU: c_int,
    pub MCU_membership: [c_int; 10usize],
    pub Ss: c_int,
    pub Se: c_int,
    pub Ah: c_int,
    pub Al: c_int,
    // Module pointers
    pub master: *mut jpeg_comp_master,
    pub main: *mut jpeg_c_main_controller,
    pub prep: *mut jpeg_c_prep_controller,
    pub coef: *mut jpeg_c_coef_controller,
    pub marker: *mut jpeg_marker_writer,
    pub cconvert: *mut jpeg_color_converter,
    pub downsample: *mut jpeg_downsampler,
    pub fdct: *mut jpeg_forward_dct,
    pub entropy: *mut jpeg_entropy_encoder,
    pub script_space: *mut jpeg_scan_info,
    pub script_space_size: c_int,
}

/// Decompression struct - matches jpegli's JPEG_LIB_VERSION 62 layout exactly
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_decompress_struct {
    // Common fields
    pub err: *mut jpeg_error_mgr,
    pub mem: *mut jpeg_memory_mgr,
    pub progress: *mut jpeg_progress_mgr,
    pub client_data: *mut c_void,
    pub is_decompressor: boolean,
    pub global_state: c_int,
    // Source
    pub src: *mut jpeg_source_mgr,
    // Basic image info
    pub image_width: JDIMENSION,
    pub image_height: JDIMENSION,
    pub num_components: c_int,
    pub jpeg_color_space: J_COLOR_SPACE,
    // Decompression parameters
    pub out_color_space: J_COLOR_SPACE,
    pub scale_num: c_uint,
    pub scale_denom: c_uint,
    pub output_gamma: f64,
    pub buffered_image: boolean,
    pub raw_data_out: boolean,
    pub dct_method: J_DCT_METHOD,
    pub do_fancy_upsampling: boolean,
    pub do_block_smoothing: boolean,
    pub quantize_colors: boolean,
    pub dither_mode: J_DITHER_MODE,
    pub two_pass_quantize: boolean,
    pub desired_number_of_colors: c_int,
    pub enable_1pass_quant: boolean,
    pub enable_external_quant: boolean,
    pub enable_2pass_quant: boolean,
    // Output info
    pub output_width: JDIMENSION,
    pub output_height: JDIMENSION,
    pub out_color_components: c_int,
    pub output_components: c_int,
    pub rec_outbuf_height: c_int,
    // Color quantization
    pub actual_number_of_colors: c_int,
    pub colormap: JSAMPARRAY,
    // State variables
    pub output_scanline: JDIMENSION,
    pub input_scan_number: c_int,
    pub input_iMCU_row: JDIMENSION,
    pub output_scan_number: c_int,
    pub output_iMCU_row: JDIMENSION,
    pub coef_bits: *mut [c_int; 64usize],
    // Tables
    pub quant_tbl_ptrs: [*mut JQUANT_TBL; 4usize],
    pub dc_huff_tbl_ptrs: [*mut JHUFF_TBL; 4usize],
    pub ac_huff_tbl_ptrs: [*mut JHUFF_TBL; 4usize],
    // Data precision
    pub data_precision: c_int,
    pub comp_info: *mut jpeg_component_info,
    // More state
    pub progressive_mode: boolean,
    pub arith_code: boolean,
    pub arith_dc_L: [UINT8; 16usize],
    pub arith_dc_U: [UINT8; 16usize],
    pub arith_ac_K: [UINT8; 16usize],
    pub restart_interval: c_uint,
    // JFIF/Adobe info
    pub saw_JFIF_marker: boolean,
    pub JFIF_major_version: UINT8,
    pub JFIF_minor_version: UINT8,
    pub density_unit: UINT8,
    pub X_density: UINT16,
    pub Y_density: UINT16,
    pub saw_Adobe_marker: boolean,
    pub Adobe_transform: UINT8,
    pub CCIR601_sampling: boolean,
    pub marker_list: jpeg_saved_marker_ptr,
    // Internal state
    pub max_h_samp_factor: c_int,
    pub max_v_samp_factor: c_int,
    pub min_DCT_scaled_size: c_int, // NOTE: v62 has this, not min_DCT_h/v_scaled_size
    pub total_iMCU_rows: JDIMENSION,
    pub sample_range_limit: *mut JSAMPLE,
    pub comps_in_scan: c_int,
    pub cur_comp_info: [*mut jpeg_component_info; 4usize],
    pub MCUs_per_row: JDIMENSION,
    pub MCU_rows_in_scan: JDIMENSION,
    pub blocks_in_MCU: c_int,
    pub MCU_membership: [c_int; 10usize],
    pub Ss: c_int,
    pub Se: c_int,
    pub Ah: c_int,
    pub Al: c_int,
    pub unread_marker: c_int,
    // Module pointers
    pub master: *mut jpeg_decomp_master,
    pub main: *mut jpeg_d_main_controller,
    pub coef: *mut jpeg_d_coef_controller,
    pub post: *mut jpeg_d_post_controller,
    pub inputctl: *mut jpeg_input_controller,
    pub marker: *mut jpeg_marker_reader,
    pub entropy: *mut jpeg_entropy_decoder,
    pub idct: *mut jpeg_inverse_dct,
    pub upsample: *mut jpeg_upsampler,
    pub cconvert: *mut jpeg_color_deconverter,
    pub cquantize: *mut jpeg_color_quantizer,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct jpeg_error_mgr {
    pub error_exit: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub emit_message: Option<unsafe extern "C" fn(cinfo: j_common_ptr, msg_level: c_int)>,
    pub output_message: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub format_message: Option<unsafe extern "C" fn(cinfo: j_common_ptr, buffer: *mut c_char)>,
    pub reset_error_mgr: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub msg_code: c_int,
    pub msg_parm: jpeg_error_mgr_msg_parm,
    pub trace_level: c_int,
    pub num_warnings: c_long,
    pub jpeg_message_table: *const *const c_char,
    pub last_jpeg_message: c_int,
    pub addon_message_table: *const *const c_char,
    pub first_addon_message: c_int,
    pub last_addon_message: c_int,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union jpeg_error_mgr_msg_parm {
    pub i: [c_int; 8usize],
    pub s: [c_char; 80usize],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_progress_mgr {
    pub progress_monitor: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub pass_counter: c_long,
    pub pass_limit: c_long,
    pub completed_passes: c_int,
    pub total_passes: c_int,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_destination_mgr {
    pub next_output_byte: *mut JOCTET,
    pub free_in_buffer: size_t,
    pub init_destination: Option<unsafe extern "C" fn(cinfo: j_compress_ptr)>,
    pub empty_output_buffer: Option<unsafe extern "C" fn(cinfo: j_compress_ptr) -> boolean>,
    pub term_destination: Option<unsafe extern "C" fn(cinfo: j_compress_ptr)>,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_source_mgr {
    pub next_input_byte: *const JOCTET,
    pub bytes_in_buffer: size_t,
    pub init_source: Option<unsafe extern "C" fn(cinfo: j_decompress_ptr)>,
    pub fill_input_buffer: Option<unsafe extern "C" fn(cinfo: j_decompress_ptr) -> boolean>,
    pub skip_input_data: Option<unsafe extern "C" fn(cinfo: j_decompress_ptr, num_bytes: c_long)>,
    pub resync_to_restart:
        Option<unsafe extern "C" fn(cinfo: j_decompress_ptr, desired: c_int) -> boolean>,
    pub term_source: Option<unsafe extern "C" fn(cinfo: j_decompress_ptr)>,
}

// Opaque types for memory manager and internal structures
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jpeg_memory_mgr {
    pub alloc_small: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            sizeofobject: size_t,
        ) -> *mut c_void,
    >,
    pub alloc_large: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            sizeofobject: size_t,
        ) -> *mut c_void,
    >,
    pub alloc_sarray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            samplesperrow: JDIMENSION,
            numrows: JDIMENSION,
        ) -> JSAMPARRAY,
    >,
    pub alloc_barray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            blocksperrow: JDIMENSION,
            numrows: JDIMENSION,
        ) -> JBLOCKARRAY,
    >,
    pub request_virt_sarray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            pre_zero: boolean,
            samplesperrow: JDIMENSION,
            numrows: JDIMENSION,
            maxaccess: JDIMENSION,
        ) -> jvirt_sarray_ptr,
    >,
    pub request_virt_barray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            pool_id: c_int,
            pre_zero: boolean,
            blocksperrow: JDIMENSION,
            numrows: JDIMENSION,
            maxaccess: JDIMENSION,
        ) -> jvirt_barray_ptr,
    >,
    pub realize_virt_arrays: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub access_virt_sarray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            ptr: jvirt_sarray_ptr,
            start_row: JDIMENSION,
            num_rows: JDIMENSION,
            writable: boolean,
        ) -> JSAMPARRAY,
    >,
    pub access_virt_barray: Option<
        unsafe extern "C" fn(
            cinfo: j_common_ptr,
            ptr: jvirt_barray_ptr,
            start_row: JDIMENSION,
            num_rows: JDIMENSION,
            writable: boolean,
        ) -> JBLOCKARRAY,
    >,
    pub free_pool: Option<unsafe extern "C" fn(cinfo: j_common_ptr, pool_id: c_int)>,
    pub self_destruct: Option<unsafe extern "C" fn(cinfo: j_common_ptr)>,
    pub max_memory_to_use: c_long,
    pub max_alloc_chunk: c_long,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jvirt_sarray_control {
    _unused: [u8; 0],
}
pub type jvirt_sarray_ptr = *mut jvirt_sarray_control;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jvirt_barray_control {
    _unused: [u8; 0],
}
pub type jvirt_barray_ptr = *mut jvirt_barray_control;

// Opaque module structs
macro_rules! opaque_struct {
    ($name:ident) => {
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct $name {
            pub _address: u8,
        }
    };
}

opaque_struct!(jpeg_comp_master);
opaque_struct!(jpeg_c_main_controller);
opaque_struct!(jpeg_c_prep_controller);
opaque_struct!(jpeg_c_coef_controller);
opaque_struct!(jpeg_marker_writer);
opaque_struct!(jpeg_color_converter);
opaque_struct!(jpeg_downsampler);
opaque_struct!(jpeg_forward_dct);
opaque_struct!(jpeg_entropy_encoder);
opaque_struct!(jpeg_decomp_master);
opaque_struct!(jpeg_d_main_controller);
opaque_struct!(jpeg_d_coef_controller);
opaque_struct!(jpeg_d_post_controller);
opaque_struct!(jpeg_input_controller);
opaque_struct!(jpeg_marker_reader);
opaque_struct!(jpeg_entropy_decoder);
opaque_struct!(jpeg_inverse_dct);
opaque_struct!(jpeg_upsampler);
opaque_struct!(jpeg_color_deconverter);
opaque_struct!(jpeg_color_quantizer);

// ============================================================================
// External function declarations (jpegli API - uses jpegli_* symbols)
// ============================================================================

extern "C" {
    // Error handling
    #[link_name = "jpegli_std_error"]
    pub fn jpeg_std_error(err: *mut jpeg_error_mgr) -> *mut jpeg_error_mgr;

    // Compression lifecycle
    #[link_name = "jpegli_CreateCompress"]
    pub fn jpeg_CreateCompress(cinfo: j_compress_ptr, version: c_int, structsize: size_t);
    #[link_name = "jpegli_destroy_compress"]
    pub fn jpeg_destroy_compress(cinfo: j_compress_ptr);
    #[link_name = "jpegli_set_defaults"]
    pub fn jpeg_set_defaults(cinfo: j_compress_ptr);
    #[link_name = "jpegli_set_colorspace"]
    pub fn jpeg_set_colorspace(cinfo: j_compress_ptr, colorspace: J_COLOR_SPACE);
    #[link_name = "jpegli_default_colorspace"]
    pub fn jpeg_default_colorspace(cinfo: j_compress_ptr);
    #[link_name = "jpegli_set_quality"]
    pub fn jpeg_set_quality(cinfo: j_compress_ptr, quality: c_int, force_baseline: boolean);
    #[link_name = "jpegli_set_linear_quality"]
    pub fn jpeg_set_linear_quality(
        cinfo: j_compress_ptr,
        scale_factor: c_int,
        force_baseline: boolean,
    );
    #[link_name = "jpegli_add_quant_table"]
    pub fn jpeg_add_quant_table(
        cinfo: j_compress_ptr,
        which_tbl: c_int,
        basic_table: *const c_uint,
        scale_factor: c_int,
        force_baseline: boolean,
    );
    #[link_name = "jpegli_quality_scaling"]
    pub fn jpeg_quality_scaling(quality: c_int) -> c_int;
    #[link_name = "jpegli_simple_progression"]
    pub fn jpeg_simple_progression(cinfo: j_compress_ptr);
    #[link_name = "jpegli_suppress_tables"]
    pub fn jpeg_suppress_tables(cinfo: j_compress_ptr, suppress: boolean);
    #[link_name = "jpegli_alloc_quant_table"]
    pub fn jpeg_alloc_quant_table(cinfo: j_common_ptr) -> *mut JQUANT_TBL;
    #[link_name = "jpegli_alloc_huff_table"]
    pub fn jpeg_alloc_huff_table(cinfo: j_common_ptr) -> *mut JHUFF_TBL;
    #[link_name = "jpegli_start_compress"]
    pub fn jpeg_start_compress(cinfo: j_compress_ptr, write_all_tables: boolean);
    #[link_name = "jpegli_write_scanlines"]
    pub fn jpeg_write_scanlines(
        cinfo: j_compress_ptr,
        scanlines: JSAMPARRAY,
        num_lines: JDIMENSION,
    ) -> JDIMENSION;
    #[link_name = "jpegli_finish_compress"]
    pub fn jpeg_finish_compress(cinfo: j_compress_ptr);
    #[link_name = "jpegli_write_raw_data"]
    pub fn jpeg_write_raw_data(
        cinfo: j_compress_ptr,
        data: JSAMPIMAGE,
        num_lines: JDIMENSION,
    ) -> JDIMENSION;
    #[link_name = "jpegli_write_marker"]
    pub fn jpeg_write_marker(
        cinfo: j_compress_ptr,
        marker: c_int,
        dataptr: *const JOCTET,
        datalen: c_uint,
    );
    #[link_name = "jpegli_write_m_header"]
    pub fn jpeg_write_m_header(cinfo: j_compress_ptr, marker: c_int, datalen: c_uint);
    #[link_name = "jpegli_write_m_byte"]
    pub fn jpeg_write_m_byte(cinfo: j_compress_ptr, val: c_int);
    #[link_name = "jpegli_write_tables"]
    pub fn jpeg_write_tables(cinfo: j_compress_ptr);
    #[link_name = "jpegli_write_icc_profile"]
    pub fn jpeg_write_icc_profile(
        cinfo: j_compress_ptr,
        icc_data_ptr: *const JOCTET,
        icc_data_len: c_uint,
    );

    // Memory destination
    #[link_name = "jpegli_mem_dest"]
    pub fn jpeg_mem_dest(
        cinfo: j_compress_ptr,
        outbuffer: *mut *mut c_uchar,
        outsize: *mut c_ulong,
    );

    // Decompression lifecycle
    #[link_name = "jpegli_CreateDecompress"]
    pub fn jpeg_CreateDecompress(cinfo: j_decompress_ptr, version: c_int, structsize: size_t);
    #[link_name = "jpegli_destroy_decompress"]
    pub fn jpeg_destroy_decompress(cinfo: j_decompress_ptr);
    #[link_name = "jpegli_read_header"]
    pub fn jpeg_read_header(cinfo: j_decompress_ptr, require_image: boolean) -> c_int;
    #[link_name = "jpegli_start_decompress"]
    pub fn jpeg_start_decompress(cinfo: j_decompress_ptr) -> boolean;
    #[link_name = "jpegli_read_scanlines"]
    pub fn jpeg_read_scanlines(
        cinfo: j_decompress_ptr,
        scanlines: JSAMPARRAY,
        max_lines: JDIMENSION,
    ) -> JDIMENSION;
    #[link_name = "jpegli_skip_scanlines"]
    pub fn jpeg_skip_scanlines(cinfo: j_decompress_ptr, num_lines: JDIMENSION) -> JDIMENSION;
    #[link_name = "jpegli_crop_scanline"]
    pub fn jpeg_crop_scanline(
        cinfo: j_decompress_ptr,
        xoffset: *mut JDIMENSION,
        width: *mut JDIMENSION,
    );
    #[link_name = "jpegli_finish_decompress"]
    pub fn jpeg_finish_decompress(cinfo: j_decompress_ptr) -> boolean;
    #[link_name = "jpegli_read_raw_data"]
    pub fn jpeg_read_raw_data(
        cinfo: j_decompress_ptr,
        data: JSAMPIMAGE,
        max_lines: JDIMENSION,
    ) -> JDIMENSION;
    #[link_name = "jpegli_has_multiple_scans"]
    pub fn jpeg_has_multiple_scans(cinfo: j_decompress_ptr) -> boolean;
    #[link_name = "jpegli_start_output"]
    pub fn jpeg_start_output(cinfo: j_decompress_ptr, scan_number: c_int) -> boolean;
    #[link_name = "jpegli_finish_output"]
    pub fn jpeg_finish_output(cinfo: j_decompress_ptr) -> boolean;
    #[link_name = "jpegli_input_complete"]
    pub fn jpeg_input_complete(cinfo: j_decompress_ptr) -> boolean;
    #[link_name = "jpegli_new_colormap"]
    pub fn jpeg_new_colormap(cinfo: j_decompress_ptr);
    #[link_name = "jpegli_consume_input"]
    pub fn jpeg_consume_input(cinfo: j_decompress_ptr) -> c_int;
    #[link_name = "jpegli_calc_output_dimensions"]
    pub fn jpeg_calc_output_dimensions(cinfo: j_decompress_ptr);
    #[link_name = "jpegli_save_markers"]
    pub fn jpeg_save_markers(cinfo: j_decompress_ptr, marker_code: c_int, length_limit: c_uint);

    // Memory source
    #[link_name = "jpegli_mem_src"]
    pub fn jpeg_mem_src(cinfo: j_decompress_ptr, inbuffer: *const c_uchar, insize: c_ulong);

    // Coefficient access
    #[link_name = "jpegli_read_coefficients"]
    pub fn jpeg_read_coefficients(cinfo: j_decompress_ptr) -> *mut jvirt_barray_ptr;
    #[link_name = "jpegli_write_coefficients"]
    pub fn jpeg_write_coefficients(cinfo: j_compress_ptr, coef_arrays: *mut jvirt_barray_ptr);
    #[link_name = "jpegli_copy_critical_parameters"]
    pub fn jpeg_copy_critical_parameters(srcinfo: j_decompress_ptr, dstinfo: j_compress_ptr);

    // Abort/destroy
    #[link_name = "jpegli_abort_compress"]
    pub fn jpeg_abort_compress(cinfo: j_compress_ptr);
    #[link_name = "jpegli_abort_decompress"]
    pub fn jpeg_abort_decompress(cinfo: j_decompress_ptr);
    #[link_name = "jpegli_abort"]
    pub fn jpeg_abort(cinfo: j_common_ptr);
    #[link_name = "jpegli_destroy"]
    pub fn jpeg_destroy(cinfo: j_common_ptr);

    // ICC profile
    #[link_name = "jpegli_read_icc_profile"]
    pub fn jpeg_read_icc_profile(
        cinfo: j_decompress_ptr,
        icc_data_ptr: *mut *mut JOCTET,
        icc_data_len: *mut c_uint,
    ) -> boolean;
}

// ============================================================================
// Helper macros
// ============================================================================

#[macro_export]
macro_rules! jpeg_create_compress {
    ($cinfo:expr) => {
        unsafe {
            jpeg_CreateCompress(
                $cinfo,
                JPEG_LIB_VERSION as i32,
                std::mem::size_of::<jpeg_compress_struct>() as size_t,
            )
        }
    };
}

#[macro_export]
macro_rules! jpeg_create_decompress {
    ($cinfo:expr) => {
        unsafe {
            jpeg_CreateDecompress(
                $cinfo,
                JPEG_LIB_VERSION as i32,
                std::mem::size_of::<jpeg_decompress_struct>() as size_t,
            )
        }
    };
}

// ============================================================================
// Butteraugli FFI bindings
// ============================================================================

/// Butteraugli error codes
pub const BUTTERAUGLI_OK: c_int = 0;
pub const BUTTERAUGLI_ERROR_MEMORY: c_int = 1;
pub const BUTTERAUGLI_ERROR_INVALID_INPUT: c_int = 2;
pub const BUTTERAUGLI_ERROR_INTERNAL: c_int = 3;

extern "C" {
    /// Compute butteraugli score between two linear RGB images.
    pub fn butteraugli_compare(
        rgb0: *const f32,
        rgb1: *const f32,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_score: *mut f64,
    ) -> c_int;

    /// Compute butteraugli score with full parameters.
    pub fn butteraugli_compare_full(
        rgb0: *const f32,
        rgb1: *const f32,
        width: size_t,
        height: size_t,
        hf_asymmetry: f32,
        xmul: f32,
        intensity_target: f32,
        out_score: *mut f64,
        out_diffmap: *mut f32,
    ) -> c_int;

    /// Convert sRGB u8 to linear RGB for butteraugli input.
    pub fn butteraugli_srgb_to_linear(
        srgb: *const u8,
        width: size_t,
        height: size_t,
        out_linear: *mut f32,
    );

    /// Compute butteraugli Gamma function value.
    pub fn butteraugli_gamma(v: f32) -> f32;

    /// Compute butteraugli FastLog2f.
    pub fn butteraugli_fast_log2f(v: f32) -> f32;

    /// Compute OpsinDynamicsImage output (XYB values).
    pub fn butteraugli_opsin_dynamics(
        linear_rgb: *const f32,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_xyb: *mut f32,
    ) -> c_int;

    /// Compute Gaussian blur on a single plane.
    pub fn butteraugli_blur(
        input: *const f32,
        width: size_t,
        height: size_t,
        sigma: f32,
        out_blurred: *mut f32,
    ) -> c_int;

    /// Compute frequency separation from LINEAR RGB image.
    pub fn butteraugli_separate_frequencies(
        linear_rgb: *const f32,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_lf_x: *mut f32,
        out_lf_y: *mut f32,
        out_lf_b: *mut f32,
        out_mf_x: *mut f32,
        out_mf_y: *mut f32,
        out_mf_b: *mut f32,
        out_hf_x: *mut f32,
        out_hf_y: *mut f32,
        out_uhf_x: *mut f32,
        out_uhf_y: *mut f32,
    ) -> c_int;

    /// Compute Malta filter on a single plane.
    pub fn butteraugli_malta(
        input: *const f32,
        width: size_t,
        height: size_t,
        use_lf: c_int,
        out_malta: *mut f32,
    ) -> c_int;

    /// Compute mask from linear RGB image.
    pub fn butteraugli_compute_mask(
        linear_rgb: *const f32,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_mask: *mut f32,
    ) -> c_int;
}

/// Safe wrapper to compute butteraugli score between two sRGB images.
///
/// # Safety
/// This function calls into C++ FFI. The caller must ensure the jpegli C++ library
/// was built with butteraugli support enabled.
#[cfg(feature = "butteraugli")]
pub unsafe fn compute_butteraugli_cpp(
    srgb0: &[u8],
    srgb1: &[u8],
    width: usize,
    height: usize,
    intensity_target: f32,
) -> Result<f64, c_int> {
    let num_pixels = width * height;
    assert_eq!(srgb0.len(), num_pixels * 3);
    assert_eq!(srgb1.len(), num_pixels * 3);

    let mut linear0 = vec![0.0f32; num_pixels * 3];
    let mut linear1 = vec![0.0f32; num_pixels * 3];

    butteraugli_srgb_to_linear(srgb0.as_ptr(), width, height, linear0.as_mut_ptr());
    butteraugli_srgb_to_linear(srgb1.as_ptr(), width, height, linear1.as_mut_ptr());

    let mut score = 0.0f64;
    let result = butteraugli_compare(
        linear0.as_ptr(),
        linear1.as_ptr(),
        width,
        height,
        intensity_target,
        &mut score,
    );

    if result == BUTTERAUGLI_OK {
        Ok(score)
    } else {
        Err(result)
    }
}

// ============================================================================
// XYB Color Conversion FFI
// ============================================================================

extern "C" {
    /// Convert sRGB u8 to linear RGB float [0, 1]
    pub fn jpegli_srgb_to_linear(
        srgb: *const u8,
        width: size_t,
        height: size_t,
        out_linear: *mut f32,
    );

    /// Convert linear RGB to XYB (unscaled, as used in butteraugli)
    pub fn jpegli_linear_to_xyb(
        linear_rgb: *const f32,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_xyb: *mut f32,
    );

    /// Convert XYB to scaled XYB [0, 1] range (as stored in JPEG)
    pub fn jpegli_scale_xyb(xyb: *mut f32, width: size_t, height: size_t);

    /// All-in-one: sRGB u8 -> scaled XYB
    pub fn jpegli_srgb_to_scaled_xyb(
        srgb: *const u8,
        width: size_t,
        height: size_t,
        intensity_target: f32,
        out_scaled_xyb: *mut f32,
    );

    /// Get XYB constants for verification
    pub fn jpegli_get_xyb_constants(
        opsin_matrix: *mut f32,
        opsin_bias: *mut f32,
        scaled_xyb_offset: *mut f32,
        scaled_xyb_scale: *mut f32,
    );

    /// PQ EOTF (display from encoded)
    pub fn jpegli_pq_eotf(encoded: f32) -> f32;

    /// PQ inverse EOTF (encoded from display)
    pub fn jpegli_pq_inv_eotf(display: f32) -> f32;

    /// HLG EOTF (display from encoded)
    pub fn jpegli_hlg_eotf(encoded: f32) -> f32;

    /// HLG inverse EOTF (encoded from display)
    pub fn jpegli_hlg_inv_eotf(display: f32) -> f32;

    /// sRGB to linear (single value)
    pub fn jpegli_srgb_to_linear_single(srgb: f32) -> f32;

    /// Linear to sRGB (single value)
    pub fn jpegli_linear_to_srgb_single(linear: f32) -> f32;

    /// Rec2408 tone mapping
    pub fn jpegli_rec2408_tone_map(
        source_nits: f32,
        target_nits: f32,
        luminances: *const f32,
        rgb: *mut f32,
    );

    /// HLG OOTF
    pub fn jpegli_hlg_ootf(
        source_nits: f32,
        target_nits: f32,
        luminances: *const f32,
        rgb: *mut f32,
    );

    /// Gamut mapping
    pub fn jpegli_gamut_map(preserve_saturation: f32, luminances: *const f32, rgb: *mut f32);

    // ========================================================================
    // Fast Math Functions (for AQ parity testing)
    // ========================================================================

    /// Fast log2 approximation
    pub fn jpegli_fast_log2f(x: f32) -> f32;

    /// Fast pow2 approximation
    pub fn jpegli_fast_pow2f(x: f32) -> f32;

    /// Fast power: base^exponent
    pub fn jpegli_fast_powf(base: f32, exponent: f32) -> f32;

    /// ComputeMask - perceptual masking curve
    pub fn jpegli_compute_mask(out_val: f32) -> f32;

    /// MaskingSqrt
    pub fn jpegli_masking_sqrt(v: f32) -> f32;

    /// RatioOfDerivativesOfCubicRootToSimpleGamma
    pub fn jpegli_ratio_of_derivatives(v: f32, invert: c_int) -> f32;
}

// ============================================================================
// Safe Rust wrappers for XYB conversion
// ============================================================================

/// Safe wrapper for C++ sRGB to scaled XYB conversion.
#[cfg(feature = "butteraugli")]
pub fn cpp_srgb_to_scaled_xyb(
    srgb: &[u8],
    width: usize,
    height: usize,
    intensity_target: f32,
) -> Vec<f32> {
    assert_eq!(srgb.len(), width * height * 3);
    let mut out = vec![0.0f32; width * height * 3];
    unsafe {
        jpegli_srgb_to_scaled_xyb(
            srgb.as_ptr(),
            width,
            height,
            intensity_target,
            out.as_mut_ptr(),
        );
    }
    out
}

/// Safe wrapper to get XYB constants from C++.
#[cfg(feature = "butteraugli")]
pub fn cpp_get_xyb_constants() -> (Vec<f32>, Vec<f32>, Vec<f32>, Vec<f32>) {
    let mut opsin_matrix = vec![0.0f32; 9];
    let mut opsin_bias = vec![0.0f32; 3];
    let mut scaled_xyb_offset = vec![0.0f32; 3];
    let mut scaled_xyb_scale = vec![0.0f32; 3];
    unsafe {
        jpegli_get_xyb_constants(
            opsin_matrix.as_mut_ptr(),
            opsin_bias.as_mut_ptr(),
            scaled_xyb_offset.as_mut_ptr(),
            scaled_xyb_scale.as_mut_ptr(),
        );
    }
    (
        opsin_matrix,
        opsin_bias,
        scaled_xyb_offset,
        scaled_xyb_scale,
    )
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_constants() {
        assert_eq!(DCTSIZE, 8);
        assert_eq!(DCTSIZE2, 64);
        assert_eq!(JPEG_LIB_VERSION, 62);
    }

    #[test]
    fn test_color_space_values() {
        assert_eq!(JCS_UNKNOWN, 0);
        assert_eq!(JCS_GRAYSCALE, 1);
        assert_eq!(JCS_RGB, 2);
        assert_eq!(JCS_YCbCr, 3);
    }

    #[test]
    fn test_struct_sizes() {
        // These sizes should match what the C library expects
        println!(
            "sizeof(jpeg_compress_struct) = {}",
            std::mem::size_of::<jpeg_compress_struct>()
        );
        println!(
            "sizeof(jpeg_decompress_struct) = {}",
            std::mem::size_of::<jpeg_decompress_struct>()
        );
        println!(
            "sizeof(jpeg_error_mgr) = {}",
            std::mem::size_of::<jpeg_error_mgr>()
        );
        println!(
            "sizeof(jpeg_component_info) = {}",
            std::mem::size_of::<jpeg_component_info>()
        );

        // The compress struct should be ~520 bytes on 64-bit for v62
        // (without the v70+ fields)
        let compress_size = std::mem::size_of::<jpeg_compress_struct>();
        assert!(
            (400..=600).contains(&compress_size),
            "jpeg_compress_struct size {} seems wrong",
            compress_size
        );
    }

    /// Validates that the instrumented C++ FFI is properly linked.
    #[test]
    fn test_instrumented_ffi_available() {
        unsafe {
            let log2_1 = jpegli_fast_log2f(1.0);
            assert!(
                log2_1.abs() < 0.001,
                "jpegli_fast_log2f(1.0) = {}, expected ~0.0",
                log2_1
            );

            let pow2_0 = jpegli_fast_pow2f(0.0);
            assert!(
                (pow2_0 - 1.0).abs() < 0.001,
                "jpegli_fast_pow2f(0.0) = {}, expected ~1.0",
                pow2_0
            );

            let log2_8 = jpegli_fast_log2f(8.0);
            assert!(
                (log2_8 - 3.0).abs() < 0.01,
                "jpegli_fast_log2f(8.0) = {}, expected ~3.0",
                log2_8
            );

            let x = 42.5;
            let roundtrip = jpegli_fast_pow2f(jpegli_fast_log2f(x));
            assert!(
                (roundtrip - x).abs() < 0.01,
                "Roundtrip failed: 2^log2({}) = {}",
                x,
                roundtrip
            );
        }

        println!("✓ Instrumented C++ FFI is properly linked and functional");
    }

    /// Test that compute_mask produces reasonable values.
    #[test]
    fn test_compute_mask_ffi() {
        unsafe {
            for v in [0.0, 0.5, 1.0, 2.0, 5.0, 10.0] {
                let mask = jpegli_compute_mask(v);
                assert!(
                    mask.is_finite(),
                    "jpegli_compute_mask({}) returned non-finite: {}",
                    v,
                    mask
                );
            }
        }
        println!("✓ jpegli_compute_mask FFI works");
    }
}
